navikt/testnorge

apps/testnorge-arena/arena-core/src/main/java/no/nav/registre/arena/core/consumer/rs/TilleggSyntConsumer.java
apps/testnorge-arena/arena-core/src/main/java/no/nav/registre/arena/core/consumer/rs/util/ConsumerUtils.java
apps/testnorge-arena/arena-local/src/main/resources/application.properties

Satt en startdato limit for tilleggstønad tilsyn familiemedlemmer. Det er fordi det er ingen gyldige målgrupper for tilsyn familiemedlemmer etter 29.02.2020 (har blitt avviklet).

REG-8496 satt en startdatolimit for tilsyn_familiemedlemmer

---

pom.xml

De ubrukte repositoriene øker byggetiden dramatisk for ucachede dependencies

testnorge-fjernet repositories som ikke er i bruk

---

apps/testnorge-arena/arena-core/src/main/java/no/nav/registre/arena/core/service/RettighetTiltakService.java

Fjernet throw exception statement og la til log.error i stedet for at generering av vedtakshistorikk skal fortsette selv om det er en feil.

Fjernet throw exception statement

---

apps/testnorge-arena/arena-core/src/main/java/no/nav/registre/arena/core/consumer/rs/AapSyntConsumer.java
apps/testnorge-arena/arena-core/src/main/java/no/nav/registre/arena/core/service/VedtakshistorikkService.java

Tiltakspenger kan ikke bli satt på en tiltaksdeltakelse som er avsluttet. Har dermed gjort endringer sånn at endre deltakerstatus blir sendt inn etter tiltakspenger og barnetillegg.
La også til en midlertidig minimum date for vedtakshistorikk lik 1.6.2017. Dette er fordi arena mangler for øyeblikket støtte for å legge til historiske tiltakspenger lenger tilbake enn 2-3 år, men de jobber med å legge til støtte.

REG-8711 endret rekkefoelge innsendelse vedtakshistorikk

---

apps/testnorge-arena/arena-core/src/main/java/no/nav/registre/arena/core/service/VedtakshistorikkService.java

For at tiltaksdeltakelse skal gi støtte for tiltakspenger og barnetillegg må tiltakYtelse være lik J.

Satt tiltakytelse lik J i tiltaksdeltakelse

---

apps/testnorge-inntekt/README.md
apps/testnorge-inntekt/src/main/java/no/nav/registre/inntekt/consumer/rs/altinnInntekt/dto/enums/AltinnEnum.java
apps/testnorge-inntekt/src/main/java/no/nav/registre/inntekt/utils/JsonAltinnEnumSerializer.java

La til en JsonSerializer for AltinnEnum, slik at verdiene til enum blir oversatt til riktig kodeverk når de sendes forå bli oversatt til xml.

La til en JsonSerializer for AltinnEnum

---

apps/testnorge-inntekt/src/main/java/no/nav/registre/inntekt/consumer/rs/dokmot/dto/RsJoarkMetadata.java
apps/testnorge-inntekt/src/main/java/no/nav/registre/inntekt/factories/RsJoarkMetadataFactory.java
apps/testnorge-inntekt/src/main/java/no/nav/registre/inntekt/service/AltinnInntektService.java

Det er unødvendig at JoarkMetadata blir sendt inn fra endepunktet, siden verdiene kan bestemmes ut fra innholdet i inntektsmeldingen. Metadata som blir sendt inn fra request blir nå overstyrt av logikk fra RsJoarkMetadataFactory.
Logikk som satte avsendermottakerIdType i dolly er duplisert i fabrikken.

Endret opprettelse av JoarkMetadata

---

apps/person-api/src/main/resources/application.yml
apps/testnorge-spion/src/main/resources/application.properties

La til logback i logging config for testnorge-spion og person-api. Litt usikker på om dette hjelper for peson-api, da spring bør hente logback fila når den heter nettopp "logback.xml".

Konfigurering av logback

---

apps/syntrest/src/main/java/no/nav/registre/syntrest/controllers/SyntController.java
apps/syntrest/src/test/java/no/nav/registre/syntrest/controllers/SyntControllerTest.java

Det kommet et ønske fra arena om å gjøre det mulig å sende inn meldekort uten arbeidstimer for gitte personer/tilfeller. Dermed er synt-meldekort blitt oppdatert sånn at det er blitt mulig å sende in request param `arbeidstimer` som da overskriver alle `ArbeidetTimerSum` i meldekortene. Har nå oppdatert syntrest til å også ta inn og videresende denne verdien.

Oppdatert meldekort endepunkt med arbeidstimer request param

---

apps/testnorge-hodejegeren/README.md
apps/testnorge-hodejegeren/hodejegeren-core/src/main/resources/application-prod.properties
apps/testnorge-hodejegeren/hodejegeren-local/src/main/resources/application-local.properties
apps/testnorge-skd/README.md
apps/testnorge-skd/skd-core/src/main/java/no/nav/registre/skd/commands/HodejegerenStatusQuoCommand.java
apps/testnorge-skd/skd-core/src/main/java/no/nav/registre/skd/consumer/HodejegerenConsumerSkd.java
apps/testnorge-skd/skd-core/src/main/java/no/nav/registre/skd/service/EksisterendeIdenterService.java
apps/testnorge-skd/skd-core/src/test/java/no/nav/registre/skd/service/EksisterendeIdenterServiceTest.java
apps/testnorge-skd/skd-local/src/main/resources/application.properties

Gjenstår fortsatt arbeid på å evt. få flere av kallene til hodejegeren til å bruke kommando-patternet og etterhvert fjerne HodejegerenConsumer-artifakten.
Denne branchen fikser dog vigsels-meldingen og andre som henter status-quo ved samme metode.

Testnorge skd/vigsels bug

---

apps/testnorge-arena/arena-core/src/main/java/no/nav/registre/arena/core/service/VedtakshistorikkService.java

Hvis vedtakshistorikk originalt bare inneholder vedtak for tiltaksdeltakelse og tiltakspenger og et passenede tiltak ikke blir funnet så blir vedtakene fjernet fra historikken. Dette gir oss en tom historikk og det ender det opp med at VedtakshistorikkException blir kastet. Har oppdatert koden nå sånn at i sånn at det blir i stedet logget at vi ikke kunne opprette noen rettigheter for ident og ingen exception blir kastet.

Oppdatert exception handling i testnorge-arena

---

apps/testnorge-statisk-data-forvalter/src/main/java/no/nav/registre/sdforvalter/adapter/TpsIdenterAdapter.java
apps/testnorge-statisk-data-forvalter/src/main/java/no/nav/registre/sdforvalter/database/repository/TpsIdenterRepository.java
apps/testnorge-statisk-data-forvalter/src/main/java/no/nav/registre/sdforvalter/provider/rs/PersonController.java
apps/testnorge-statisk-data-forvalter/src/main/java/no/nav/registre/sdforvalter/service/PersonService.java

Endepunkt for å sjekke om fnr/dnr finnes i blant de faste dataene. Hent orgnr fantes allerede, men gir 500 i stedenfor 404 hvis den ikke finnes.

Sjekke om ident ligger i faste data-db

---

apps/testnorge-arena/arena-core/src/main/java/no/nav/registre/arena/core/service/RettighetTiltakService.java
apps/testnorge-arena/arena-core/src/main/java/no/nav/registre/arena/core/service/VedtakshistorikkService.java
apps/testnorge-arena/arena-core/src/main/java/no/nav/registre/arena/core/service/util/ServiceUtils.java
apps/testnorge-arena/arena-core/src/main/java/no/nav/registre/arena/core/service/util/VedtakUtils.java
apps/testnorge-arena/arena-core/src/main/resources/adminkode_til_deltakerstatus_endring.json
apps/testnorge-arena/arena-core/src/main/resources/application.properties
apps/testnorge-arena/arena-core/src/main/resources/vedtak_til_statuskode.json
apps/testnorge-arena/arena-core/src/test/java/no/nav/registre/arena/core/consumer/rs/AapSyntConsumerTest.java
apps/testnorge-arena/arena-core/src/test/java/no/nav/registre/arena/core/consumer/rs/BrukereArenaForvalterConsumerTest.java
apps/testnorge-arena/arena-core/src/test/java/no/nav/registre/arena/core/provider/rs/AapControllerIntegrationTest.java
apps/testnorge-arena/arena-core/src/test/java/no/nav/registre/arena/core/provider/rs/BrukereControllerIntegrationTest.java
apps/testnorge-arena/arena-core/src/test/java/no/nav/registre/arena/core/provider/rs/IdentControllerIntegrationTest.java
apps/testnorge-arena/arena-core/src/test/java/no/nav/registre/arena/core/provider/rs/TilleggsstoenadControllerIntegrationTest.java
apps/testnorge-arena/arena-core/src/test/java/no/nav/registre/arena/core/provider/rs/TiltakControllerIntegrationTest.java
apps/testnorge-arena/arena-core/src/test/java/no/nav/registre/arena/core/service/RettighetTiltakServiceTest.java
apps/testnorge-arena/arena-core/src/test/java/no/nav/registre/arena/core/service/VedtakshistorikkServiceTest.java
apps/testnorge-arena/arena-local/src/main/resources/application.properties
libs/testnorge-domain/src/main/java/no/nav/registre/testnorge/domain/dto/arena/testnorge/brukere/Deltakerstatuser.java

Har oppdatert endring av tiltaksdeltakelse. Før ble alle tiltaksdeltakelser først satt til gjennomføres ("GJENN"), så ble relaterte BASI/BTIL vedtak sendt inn, og til slutt ble tiltaksdeltakelsen endret til enten fullført ("FULLF") eller del-avbrudd("DELAVB") basert på datoene i tiltaksdeltakelsen. 
Nå har jeg oppdatert sånn at det er mulig at tiltaksdeltakelsen blir satt til "TILBUD", "IKKEM", "IKKEAKTUELL", "VENTELISTE", eller "NEITAKK" i stedet for kun "GJENN". Hvis dette skjer så blir heller ikke BASI/BTIL vedtak sendt inn siden tiltaksdeltakelsen må være satt til gjennomføres for at vedtakene skal gå gjennom. Tiltaksdeltakelsen blir heller ikke endret til "FULLF" eller "DELAVB".

Testnorge arena/legge til mer variasjon deltakerstatus

---

apps/orkestratoren/src/main/java/no/nav/registre/orkestratoren/batch/v1/JobController.java

Har oppdatert batch kjøring for arena i orkestratoren. Fjernet opprettelse av enkelt vedtak for aap sånn at kun vedtakshistorikk blir sendt inn. Har også oppdatert scheduling sånn at vedtakshistorikk blir sendt inn hver andre time i stedet for kun kl. 6. Har ikke brukt cron før så det hadde vært greit hvis noen kunne dobbelsjekke at det ble endret korrekt ;)

Oppdatert batch kjoering for arena

---

apps/testnorge-arena/arena-core/src/main/java/no/nav/registre/arena/core/service/util/VedtakUtils.java

Tidligere ble alle tiltakspenger og barnetillegg vedtak datoer satt til dato for funnet tiltak. Dette skaper negative perioder for vedtakene da følge vedtak (E, S eller G) ikke kan ha samme fradato som det første vedtaket (O). Nå har jeg endret det sånn at kun O-vedtak får samme tildato og fradato som funnet tiltak. Vedtakene som følger (E, S eller G) får samme tildato som funnet tiltak mens fradato blir satt til tiltak-fradato pluss original forskjell mellom fradato til O-vedtak og det følgende vedtakets fradato. 
Jeg fant også en feil i `getVedtakSequence`-metoden som jeg fikset.

Testnorge arena/hindre negative perioder tiltak

---

apps/testnorge-arena/arena-core/src/main/java/no/nav/registre/arena/core/service/VedtakshistorikkService.java
apps/testnorge-arena/arena-core/src/main/java/no/nav/registre/arena/core/service/util/VedtakUtils.java

Arena har oppdatert endepunktet for finn-tiltak sånn at det nå også returnerer `tiltakProsentDeltid` for tiltaket. Filtrering av tiltak er nå blitt oppdatert sånn at det kan være overlappende tiltak så lenge sammenlagt prosentdeltid på tiltakene ikke overstiger 100%.
Har også ryddet litt i koden.

Testnorge arena/stãoette overlappende tiltak

---

apps/mn-synt-arbeidsforhold-service/src/main/java/no/nav/registre/testnorge/mn/syntarbeidsforholdservice/consumer/SyntrestConsumer.java
apps/mn-synt-arbeidsforhold-service/src/main/java/no/nav/registre/testnorge/mn/syntarbeidsforholdservice/consumer/command/GenerateArbeidsforholdHistorikkCommand.java
apps/mn-synt-arbeidsforhold-service/src/main/java/no/nav/registre/testnorge/mn/syntarbeidsforholdservice/domain/Arbeidsforhold.java
apps/mn-synt-arbeidsforhold-service/src/main/java/no/nav/registre/testnorge/mn/syntarbeidsforholdservice/domain/Opplysningspliktig.java
apps/mn-synt-arbeidsforhold-service/src/main/java/no/nav/registre/testnorge/mn/syntarbeidsforholdservice/domain/Organisajon.java
apps/mn-synt-arbeidsforhold-service/src/main/java/no/nav/registre/testnorge/mn/syntarbeidsforholdservice/exception/MNOrganisasjonException.java
apps/mn-synt-arbeidsforhold-service/src/main/java/no/nav/registre/testnorge/mn/syntarbeidsforholdservice/exception/SyntetiseringException.java
apps/mn-synt-arbeidsforhold-service/src/main/java/no/nav/registre/testnorge/mn/syntarbeidsforholdservice/provider/IdentController.java
apps/mn-synt-arbeidsforhold-service/src/main/java/no/nav/registre/testnorge/mn/syntarbeidsforholdservice/provider/OpplysningspliktigController.java
apps/mn-synt-arbeidsforhold-service/src/main/java/no/nav/registre/testnorge/mn/syntarbeidsforholdservice/service/ArbeidsfoholdService.java
apps/mn-synt-arbeidsforhold-service/src/main/java/no/nav/registre/testnorge/mn/syntarbeidsforholdservice/service/ArbeidsforholdService.java
apps/mn-synt-arbeidsforhold-service/src/test/java/no/nav/registre/testnorge/mn/syntarbeidsforholdservice/provider/assertions/OpplysningspliktigDTOAssert.java

Syntrest returnerer nå liste (med ukjent lengde) med fremtidig arbeidforhold i stedet for kun neste måneds arbeidsforhold. Har oppdatert koden sånn at det støtter dette og fikset litt code smells og skrivefeil. 
Har ikke klart å teste koden lokalt enda, da jeg ikke får AccessTokenService til å funke lokalt, men jeg tenkte det var greit å ha en PR på det jeg har endret mens jeg finner ut av det.

Byttet til bruk av char-rnn

---

apps/orkestratoren/src/main/java/no/nav/registre/orkestratoren/batch/v1/JobController.java

Har endret batch kjøringen til Arena i orkestratoren til å kjøre hver time mellom 18:00 - 05:00 i stedet for annen hver time gjennom hele dagen. Har endret sånn at det kun blir registrert en arbeidsøker i arena med oppfølging hver gang og skal også minke antall identer med vedtakshistorikk som blir generert hver gang (må endre det i vault) fra 50 til 15.
Minker antallet da for å se om det fikser litt performance issues testnorge-arena har hatt.

Oppdatert arena batch kjoring

---

apps/syntrest/src/main/java/no/nav/registre/syntrest/domain/amelding/Permisjon.java

Liten fiks for å kunne sende "permisjoner" med i input til synt_amelding.

Endret Localdate til string i permisjonsdatoer

---

.gitignore
apps/brreg-stub/build.gradle
apps/brreg-stub/src/main/xsd/HentRoller.xsd
apps/brreg-stub/src/main/xsd/Rolleutskrift.xsd

Team Arbeidsforhold er foreløpig fornøyd med denne løsningen, men den trenger nok litt mer kjærlighet før IntelliJ godtar den. HentRolleMapper og Rolleoversikt finner ikke `tjenestekontrakter` selv om den er en del av build.

Fjerne namespace fra xsd

---

apps/testnorge-arena/nais.yaml

Siden du har så mange aktive brancher på arena ser jeg for meg at det fort kan bli tull hvis jeg begynner å bytte namespace samtidig. Du kan bare merge inn denne når du er klar for det, og så eventuelt merge inn master i de aktive branchene 😄 Jeg har kopiert alle credentials i vault fra default til dolly, så jeg tror det skal fungere så snart denne er deploya.

testnorge-arena til dolly namespace

---

apps/testnorge-arena/arena-core/src/main/java/no/nav/registre/arena/core/service/VedtakshistorikkService.java
apps/testnorge-arena/arena-core/src/main/java/no/nav/registre/arena/core/service/util/DatoUtils.java
apps/testnorge-arena/arena-core/src/main/java/no/nav/registre/arena/core/service/util/VedtakUtils.java
apps/testnorge-arena/arena-core/src/test/java/no/nav/registre/arena/core/service/VedtakshistorikkServiceTest.java
apps/testnorge-arena/arena-core/src/test/java/no/nav/registre/arena/core/service/util/DatoUtilsTest.java
libs/testnorge-domain/src/main/java/no/nav/registre/testnorge/domain/dto/arena/testnorge/vedtak/NyttVedtakTillegg.java

Tilleggsstønad-vedtak i historikken med et par spesifikke målgruppekoder må ha et nødvendig gyldig tilknyttet vedtak (perioden for Tilleggsstønad-vedtak er innenfor perioden til tilknyttet vedtak) (for eks tilleggstønad vedtak med målgruppekode MOTILPEN må ha tiltakspenger vedtak). Hvis et gyldig tilknyttet vedtak mangler blir nå tilleggsstønad-vedtakene med den spesifikke målgruppekoden fjernet fra historikken. 
Har også (som vanlig 🤣) ryddet litt i koden sånn at dato relaterte metoder i vedtakshistorikkservice er flyttet til en egen `DatoUtils`-fil og  `genererVedtakshisorikk`-metoden er blitt litt midre kompleks med at den nå bruker en `getMaksimumAlder`-metode.

Testnorge arena/tilleggsstonad malgruppe sjekk

---

apps/helsepersonell-api/config.yml

Er vel greit å endre denne tilbake nå, og fikse opp i vault URLene ved merge?

Endret tilbake til helsepersonell url uten tmp

---

apps/orkestratoren/src/main/java/no/nav/registre/orkestratoren/batch/v1/JobController.java
apps/testnorge-arena/src/main/java/no/nav/registre/testnorge/arena/consumer/rs/InnsatsArenaForvalterConsumer.java
apps/testnorge-arena/src/main/java/no/nav/registre/testnorge/arena/consumer/rs/command/HentVedtakshistorikkCommand.java
apps/testnorge-arena/src/main/java/no/nav/registre/testnorge/arena/consumer/rs/command/PostEndreInnsatsbehovCommand.java
apps/testnorge-arena/src/main/java/no/nav/registre/testnorge/arena/consumer/rs/command/PostFinnTiltakCommand.java
apps/testnorge-arena/src/main/java/no/nav/registre/testnorge/arena/consumer/rs/command/PostRettighetCommand.java
apps/testnorge-arena/src/main/java/no/nav/registre/testnorge/arena/consumer/rs/command/PostSyntAapRequestCommand.java
apps/testnorge-arena/src/main/java/no/nav/registre/testnorge/arena/consumer/rs/command/PostSyntTilleggRequestCommand.java
apps/testnorge-arena/src/main/java/no/nav/registre/testnorge/arena/consumer/rs/command/PostSyntTiltakRequestCommand.java
apps/testnorge-arena/src/main/java/no/nav/registre/testnorge/arena/service/VedtakshistorikkService.java
apps/testnorge-arena/src/main/java/no/nav/registre/testnorge/arena/service/util/IdenterUtils.java

Har oppdatert generering av vedtakshistorikk i testnorge-arena til å kjøre i parallell for å korte ned tiden det tar å sende inn historikken. Mens jeg testet endringen oppdaget jeg et par småfeil andre steder i koden som jeg også har fisket.
Sist oppdaterte jeg batch-kjøringen for arena i orkestratoren.

Testnorge arena/parallell kjoring

---

apps/testnorge-arena/src/main/java/no/nav/registre/testnorge/arena/service/VedtakshistorikkService.java

Har oppdatert vedtakshistorikk-service sånn at hver enkelt vedtak blir sendt inn som en egen request. Tidligere har alle vedtak med samme rettighet blitt sendt inn sammen (eks: alle AAP sammen eller alle Tiltakspenger sammen).
Dette er gjort for å unngå følgefeil som kan oppstå når flere vedtak blir sendt inn sammen.

Oppdatert innsendelse av rettigheter testnorge-arena

---

apps/testnorge-arena/src/main/java/no/nav/registre/testnorge/arena/service/VedtakshistorikkService.java

Har oppdatert sånn at ident som får vedtakshistorikk også blir registert med ident i POPP hvis det er finnes 11.5 vedtak i historikken og ikke bare AAP.

Ident registert i popp for 11.5 vedtak

---

apps/testnorge-arena/src/main/java/no/nav/registre/testnorge/arena/service/util/IdenterUtils.java

Sjekker ofte om en ident eksisterer i arena sånn at de ikke blir prøvd registrert når de allerede er det. Når da loggene ofte sier "`Fant ingen eksisterende identer`" virker det som noe er feil, når det stemmer at idente(r) ikke eksisterer i arena enda. Fjernet dermed log.info-en.

Fjernet misvisende logging

---

apps/syntrest/src/main/java/no/nav/registre/syntrest/consumer/SyntConsumer.java

Endepunkt for meldekort får 
```
There was an unexpected error (type=Internal Server Error, status=500).
Exceeded limit on max bytes to buffer : 262144
```
når numToGenerate er 45 eller større. 
Som løsning har jeg oppdatert webClient i SyntConsumer. Fant ikke en måte å gjøre det kun for webClient til meldekort siden alle bruker felles webclientBuilder (se SyntConsymerConfig), så hvis noen har en god ide er det bare å si ifra ;)

Oppdatert maxinMemorysize for webclient

---

libs/testnorge-avro-schema/build.gradle

Gammel versjon for avro plugin finnes ikke lenger. Byttet til ny versjon som jeg fikk bygget lokalt. Har ikke testet endringen mer enn det.

Endret avro plugin

---

apps/testnorge-arena/src/main/java/no/nav/registre/testnorge/arena/service/ArbeidssoekerService.java
apps/testnorge-arena/src/main/java/no/nav/registre/testnorge/arena/service/BrukereService.java
apps/testnorge-arena/src/main/java/no/nav/registre/testnorge/arena/service/RettighetAapService.java
apps/testnorge-arena/src/main/java/no/nav/registre/testnorge/arena/service/RettighetTiltakService.java
apps/testnorge-arena/src/main/java/no/nav/registre/testnorge/arena/service/VedtakshistorikkService.java
libs/testnorge-domain/src/main/java/no/nav/registre/testnorge/domain/dto/arena/testnorge/brukere/NyBruker.java

Registrering av brukere i Arena har fått et nytt felt som heter `aktiveringsDato`. Denne datoen bestemmer dato for 14a-vedtak  som automatisk genereres for ident. Hvis `aktiveringsDato` mangler blir denne satt til dagens dato, som ikke er logisk når første vedtak for ident er tilbake i tid. Har oppdatert koden sånn at `aktiveringsDato` blir nå satt lik fra-datoen til tidligste vedtak i historikken.

Lagt til støtte for aktiveringsdato i brukerregistrering

---

apps/dolly-frontend/src/main/js/src/components/fagsystem/aareg/form/initialValues.js
apps/dolly-frontend/src/main/js/src/components/fagsystem/aareg/form/validation.js

Fikset sånn at initial date for ansettelsesstart alltid har 00:00:00 for time. Endret også fom og tom for genererperiode fra string til date.

Oppdatert initialvalues og validering aareg

---

apps/dolly-frontend/src/main/js/src/components/layout/header/Header.tsx
apps/dolly-frontend/src/main/js/src/components/ui/appError/AppError.js

Har endret "her" knapp til å redirecte til oauth basert på location.
Har endret "API-dok" til å redirecte til dolly-backend-dev for dolly-frontend-dev.

Dolly frontend/oppdater redirect basert på location

---

apps/syntrest/src/main/java/no/nav/registre/syntrest/config/SyntConsumerConfig.java

Syntrest sliter med å få tak i sister versjon av image tag for synt-pakkene (pga guthub endringer). Midlertidig fiks er at vi deployer alle synt-appene og at syntrest ikke tar dem ned etter kall.

Fjernet takedown

---

apps/dolly-backend/src/main/java/no/nav/dolly/bestilling/aareg/util/AaregMergeUtil.java
apps/testnorge-inntekt/src/main/java/no/nav/registre/inntekt/config/JsonMapperConfig.java
apps/testnorge-skd/build.gradle
apps/testnorge-skd/src/main/java/no/nav/registre/skd/service/FasteMeldingerService.java
apps/udi-stub/src/main/java/no/nav/udistub/provider/web/PersonStatusService.java

Logback encoder er blitt oppdatert og import av org.apache.commons.lang3 via den funker ikke. Endret til direkte import vis org.apache.commons.lang3 i stedet.

Fiks for org.apache.commons.lang3

---

apps/dolly-backend/src/main/java/no/nav/dolly/bestilling/skjermingsregister/SkjermingsRegisterClient.java
apps/dolly-frontend/src/main/js/src/components/bestillingsveileder/stegVelger/steg/steg1/paneler/Personinformasjon.tsx

- Fjerner hele skjermingsobjektet dersom skjerming avhukes i Dolly frontend
- Lagt på ekstra sjekk i backend for å filtrere ut tomme skjermingsobjekter

Skjermingsregister innsending av tomt objekt fiks

---

apps/generer-arbeidsforhold-populasjon-service/config.yml
apps/generer-arbeidsforhold-populasjon-service/src/main/java/no/nav/registre/testnav/genererarbeidsforholdpopulasjonservice/consumer/SyntArbeidsforholdConsumer.java
apps/generer-arbeidsforhold-populasjon-service/src/main/java/no/nav/registre/testnav/genererarbeidsforholdpopulasjonservice/consumer/command/GenererArbeidsforholdHistorikkCommand.java
apps/generer-arbeidsforhold-populasjon-service/src/main/java/no/nav/registre/testnav/genererarbeidsforholdpopulasjonservice/consumer/command/GenererStartArbeidsforholdCommand.java
apps/generer-arbeidsforhold-populasjon-service/src/main/java/no/nav/registre/testnav/genererarbeidsforholdpopulasjonservice/consumer/credentials/SyntAmeldingProperties.java
apps/generer-arbeidsforhold-populasjon-service/src/main/resources/application.yml

Har oppdatert  generer-arbeidsforhold-populasjon-service til å bruke synt-amelding direkte i stedet for syntrest-proxy. Glemte å gjøre det før jeg fjernet støtten i syntrest tidligere.

Byttet til synt-amelding

---

.github/workflows/app.person-search-service.yml
apps/dolly-frontend/src/main/js/src/pages/testnorgePage/TestnorgePage.tsx
apps/dolly-frontend/src/main/js/src/pages/testnorgePage/search/SearchView.tsx
apps/dolly-frontend/src/main/js/src/pages/testnorgePage/search/SearchViewConnector.tsx
apps/dolly-frontend/src/main/js/src/pages/testnorgePage/utils.ts
apps/person-search-service/src/main/java/no/nav/registre/testnorge/personsearchservice/adapter/PersonSearchAdapter.java

Har ryddet i Dolly-frontend sånn at søk returnerer maks 100 identer om gangen og man ikke trenger å gjøre et nytt søk for hver paginering da vi henter alle 100 ved søk og DollyTable har en egen paginering som er lettere å bruke.
Har også justert litt i person-search-service. Har satt timeout til 3 sekunder og har justert alder query (etter tips fra Kristen) :)

Testnorge-sok/forenkle sok

---

apps/dolly-frontend/src/main/js/src/components/fagsystem/aareg/form/partials/orgnummerToggle.js

Fikset sånn at det er feilmelding når miljø ikke er valg for inntektskomponenten -> skriv inn org

Dolly-frontend - Fiks for orgnummer feilmelding

---

apps/dolly-frontend/src/main/js/src/components/fagsystem/pdlf/form/partials/adresser/bostedsadresse/Bostedsadresse.tsx
apps/dolly-frontend/src/main/js/src/pages/gruppe/PersonVisning/PersonVisning.js
apps/dolly-frontend/src/main/js/src/pages/gruppe/PersonVisning/PersonVisningConnector.js
apps/dolly-frontend/src/main/js/src/service/SelectOptions.tsx

Begrenset boadresse muligheter for DNR og BOST sånn at de kun kan ha utenlandsk adresse.
Fikset også at identtype er korrekt for legg til.

Begrenset boadresse valg for DNR og BOST

---

apps/dolly-frontend/src/main/js/src/components/bestilling/sammendrag/miljoeStatus/MiljoeStatus.js
apps/dolly-frontend/src/main/js/src/utils/BestillingStatusFormattering.tsx

Endret slik at vi viser alle statuser når f.eks. én ident har feilet i ett miljø.
Slår sammen visning i de tilfellene status fra tpsf og tpsmessaging er 100% lik.
(Pinlig liten PR, men jeg lovet at jeg har jobbet hardt 😅  )

Ny mapping av bestillingsstatuser

---

apps/dolly-frontend/src/main/js/src/pages/gruppe/PersonListe/PersonListe.js
apps/dolly-frontend/src/main/js/src/pages/gruppe/PersonVisning/PersonMiljoeinfo/PersonMiljoeinfo.tsx
apps/dolly-frontend/src/main/js/src/pages/gruppe/PersonVisning/PersonVisning.js

Oppdatert tps miljoe visning sånn at info fra alle relevante miljoe blir vist og ikke bare de tilknyttet siste bestilling. Unntaket er hvis man er innlogget med bankid, da vises kun q1.

Dolly frontend/oppdatering tps miljoe visning

---

apps/dolly-frontend/src/main/js/src/components/fagsystem/brregstub/form/partials/orgnrToggle.tsx
apps/dolly-frontend/src/main/js/src/components/fagsystem/inntektsmelding/form/partials/orgnrToogle.tsx
apps/dolly-frontend/src/main/js/src/components/fagsystem/inntektstub/form/partials/orgnummerToggle.js
apps/dolly-frontend/src/main/js/src/components/organisasjonSelect/OrganisasjonToogleGruppe.tsx

Oppdatert org valg i A-ordningen sånn at den inkluderer egne organisasjoner.
Lagde også en egen OrganisasjonToogleGruppe komponent for å fjerne duplikat kode.

Dolly frontend/utvide org valg

---

apps/dolly-frontend/src/main/js/src/components/ui/button/FrigjoerButton/FrigjoerButton.tsx
apps/dolly-frontend/src/main/js/src/components/ui/button/FrigjoerButton/FrigjoerModal.less
apps/dolly-frontend/src/main/js/src/pages/gruppe/PersonVisning/PersonVisning.js

Har endret "SLETT"-knappen for testnorge-identer til en "FRIGJØR/SLETT" knapp i stedet. Har også lagt til info om hva dette innebærer i modal-teksten.

Dolly-frontend : Frigjør/slett knapp for testnorge identer

---

apps/dolly-frontend/src/main/js/src/components/bestilling/sammendrag/kriterier/BestillingKriterieMapper.js
apps/dolly-frontend/src/main/js/src/components/bestillingsveileder/stegVelger/steg/steg1/paneler/ArbeidInntekt.js
apps/dolly-frontend/src/main/js/src/components/fagsystem/inntektstub/form/Form.tsx
apps/dolly-frontend/src/main/js/src/components/fagsystem/inntektstub/visning/Visning.tsx
apps/dolly-frontend/src/main/js/src/components/fagsystem/pensjon/visning/PensjonVisning.js
apps/dolly-frontend/src/main/js/src/components/ui/brukerAlert/AlertInntektskomponentenRequired.tsx

Forslag til ny visning av Pensjonsinntekter:
Har også endet "Inntektskomponenten" til "Inntekstub"

Dolly frontend/popp visning oppdatering

---

apps/dolly-frontend/src/main/js/src/components/inntektStub/validerInntekt/index.js

Var ikke så rett frem som å bare sette alle undefined til TOM ved validering, da fikk vi ikke tilbake alle mulige felt.. Fikk testet en del uten å få noe feil og la ikke merke til noen manglende felt i response så tror dette løste problemet.

Inntektstub endringer for å håndtere feilende validering etter submit

---

apps/synt-vedtakshistorikk-service/src/main/java/no/nav/testnav/apps/syntvedtakshistorikkservice/service/BrukerService.java
apps/synt-vedtakshistorikk-service/src/main/java/no/nav/testnav/apps/syntvedtakshistorikkservice/service/IdentService.java
apps/synt-vedtakshistorikk-service/src/main/java/no/nav/testnav/apps/syntvedtakshistorikkservice/service/VedtakshistorikkService.java
apps/synt-vedtakshistorikk-service/src/test/java/no/nav/testnav/apps/syntvedtakshistorikkservice/service/BrukerServiceTest.java

Liten oppdatering for bosatt status. Ikke lenger nødvendig å sjekke dato for hvor lenge identene har vært bosatt.

Synt vedtakshistoriukk service/bosatt fiks

---

apps/dolly-frontend/src/main/js/src/components/fagsystem/pdl/visning/partials/relasjoner/PdlForeldreBarn.tsx
apps/dolly-frontend/src/main/js/src/components/fagsystem/pdlf/form/partials/pdlPerson/PdlEksisterendePerson.tsx
apps/dolly-frontend/src/main/js/src/components/fagsystem/pdlf/visning/partials/RelatertPersonUtenId.tsx

* Infoboks ved valg av eksisterende person i tom gruppe.
* Fix visning av forelder/barn uten id på pdl-visning.

Personvalg tom gruppe + visning person uten id

---

apps/dolly-frontend/src/main/js/src/components/bestillingsveileder/stateModifier.js
apps/dolly-frontend/src/main/js/src/components/bestillingsveileder/stegVelger/steg/steg1/paneler/Arena.js
apps/dolly-frontend/src/main/js/src/components/bestillingsveileder/stegVelger/steg/steg1/paneler/Personinformasjon.tsx
apps/dolly-frontend/src/main/js/src/components/bestillingsveileder/stegVelger/steg/steg3/IdentVelger.tsx

Fiks for "Velg alle" og "Fjern alle" knappene i steg 1 i bestilling (disse funket ikke i det hele tatt).
Fjernet også arena-advarsel for nav-syntetisk ident da det støttes nå.

Dolly frontend/velg alle og fjern alle attributter fiks

---

apps/dolly-frontend/src/main/js/src/components/adresseVelger/AdresseSok.tsx
apps/dolly-frontend/src/main/js/src/components/adresseVelger/AdresseVelger.tsx

Endret adressesøk for vegadresse til å søke etter fritekst i stedet for adressenavn. Dette gjør at du ikke må ha fullstendig match for adressenavn når du søker.

Dolly frontend - Byttet til fritekst sok

---

libs/reactive-proxy/src/main/java/no/nav/testnav/libs/reactiveproxy/config/SecurityConfig.java
libs/security-core/build.gradle
proxies/aareg-proxy/src/main/java/no/nav/testnav/proxies/aaregproxy/AaregProxyApplicationStarter.java
proxies/aareg-proxy/src/main/java/no/nav/testnav/proxies/aaregproxy/DevVaultConfig.java
proxies/aareg-proxy/src/main/resources/application.yml
proxies/aareg-proxy/src/test/java/no/nav/testnav/proxies/aaregproxy/AaregProxyApplicationStarterTest.java
proxies/aareg-proxy/src/test/resources/application-test.properties
proxies/aareg-proxy/src/test/resources/logback-test.xml

Prøver å emulere endepunkt slik det brukes av dolly-backend for REST for å ende opp hos [modapp](https://modapp-q2.adeo.no/aareg-services/api/swagger-ui/index.html). Innebærer valg av miljø basert på HTTP query og setting av miljø basert på HTTP header.
Eksisterende routing er ikke berørt. Lagt til test, som SonarCloud ikke virker å detektere.

Routing basert på query

---

apps/dolly-frontend/src/main/js/src/components/ui/button/PartnerImportButton/PartnerImportButton.less
apps/dolly-frontend/src/main/js/src/components/ui/button/PartnerImportButton/PartnerImportButton.tsx

Fiks sånn at feilmelding ikke lenger vises etter at partner er blitt importert. Endret det også sånn at bruker i stedet blir bedt om å lukke visning hvis alt går bra med import.

Dolly Frontend - Partner import fiks

---

apps/synt-vedtakshistorikk-service/src/main/java/no/nav/testnav/apps/syntvedtakshistorikkservice/provider/BatchController.java
apps/synt-vedtakshistorikk-service/src/main/java/no/nav/testnav/apps/syntvedtakshistorikkservice/provider/BrukerController.java
apps/synt-vedtakshistorikk-service/src/main/java/no/nav/testnav/apps/syntvedtakshistorikkservice/service/ArenaDagpengerService.java
apps/synt-vedtakshistorikk-service/src/main/java/no/nav/testnav/apps/syntvedtakshistorikkservice/service/ArenaForvalterService.java
apps/synt-vedtakshistorikk-service/src/main/java/no/nav/testnav/apps/syntvedtakshistorikkservice/service/ArenaTiltakService.java
apps/synt-vedtakshistorikk-service/src/main/java/no/nav/testnav/apps/syntvedtakshistorikkservice/service/IdentService.java
apps/synt-vedtakshistorikk-service/src/main/java/no/nav/testnav/apps/syntvedtakshistorikkservice/service/TagsService.java
apps/synt-vedtakshistorikk-service/src/main/java/no/nav/testnav/apps/syntvedtakshistorikkservice/service/VedtakshistorikkService.java
apps/synt-vedtakshistorikk-service/src/test/java/no/nav/testnav/apps/syntvedtakshistorikkservice/consumer/PdlConsumerTest.java
apps/synt-vedtakshistorikk-service/src/test/java/no/nav/testnav/apps/syntvedtakshistorikkservice/consumer/SyntVedtakshistorikkConsumerTest.java
apps/synt-vedtakshistorikk-service/src/test/java/no/nav/testnav/apps/syntvedtakshistorikkservice/provider/BrukerControllerTest.java
apps/synt-vedtakshistorikk-service/src/test/java/no/nav/testnav/apps/syntvedtakshistorikkservice/service/ArenaTiltakServiceTest.java

Fjernet oppretting av tag "DOLLY" og endret det sånn at ident og eventuell partner til ident begge kun får tag "ARENASYNT"

Synt vedtakshistorikk service/oppretter tag på partner også

---

apps/dolly-frontend/src/main/js/src/components/bestilling/sammendrag/miljoeStatus/fagsystemStatus/IdentList.tsx
apps/dolly-frontend/src/main/js/src/components/ui/button/ExpandButton/ExpandButton.less
apps/dolly-frontend/src/main/js/src/components/ui/button/ExpandButton/ExpandButton.tsx
apps/dolly-frontend/src/main/js/src/components/ui/dollyTable/table/TableRow.js
apps/dolly-frontend/src/main/js/src/components/ui/form/fieldArray/ExpandableBlokk.tsx
apps/dolly-frontend/src/main/js/src/components/ui/icon/Icon.js
apps/dolly-frontend/src/main/js/src/components/ui/panel/Panel.js
apps/dolly-frontend/src/main/js/src/pages/testnorgePage/search/optionsPanel/OptionsPanel.tsx
apps/dolly-frontend/src/main/js/src/pages/testnorgePage/search/partials/Identer.tsx
apps/dolly-frontend/src/main/js/src/pages/ui/index.js

FIks for følgende wcag feil:
- 1.1.1 Ikke-tekstlig innhold - mangler role = 'img' on SVG / svg mangler Aria under Person. Seks ulike feil
- 4.1.2 Navn, rolle, verdi - ingen knappetekst. Fire steder
- 3.3.2 Ledetekster eller instruksjoner - plassholder brukt til merkelapp

Dolly frontend/ fiks for tre WCAG feil

---

apps/tps-messaging-service/build.gradle

Forsøk på å hjelpe Gradle gjennom feil av typen "Could not find netty-transport-native-epoll-4.1.70.Final-linux-x86_64.jar (io.netty:netty-transport-native-epoll:4.1.70.Final)."
Transitiv dependency gjennom spring-boot-starter-webflux. Finnes native for Linux og Mac som alternativ til NIO, ref. https://netty.io/wiki/native-transports, men feiler altså på "andre OS".

Workaround for netty-transport-native-epoll

---

apps/dolly-frontend/src/main/js/src/components/fagsystem/pdlf/visning/Visning.js
apps/dolly-frontend/src/main/js/src/ducks/fagsystem/index.js

Fikset manglende visning av dødsfall og boadresse for TPS identer. 
Fikset også sånn at det står (død) etter alder for TPS identer når det er blitt opprettet dødsfall via PDL.

Dolly- Frontend / Fikset manglende visning dødsfall og boadresse tps

---

.github/workflows/app.testnorge-inst.yml
.github/workflows/app.testnorge-skd.yml
apps/testnorge-inst/nais.yaml

Stopper deploy av testnorge-inst og testnorge-skd (og tar ned deployet versjon) da disse skal ikke være i bruk lenger. Venter litt med å fjerne dem fra monorepo.

Stoppet deploy av testnorge inst og testnorge skd

---

apps/arbeidsforhold-service/config.yml
apps/helsepersonell-service/config.yml
apps/organisasjon-service/config.yml
proxies/pdl-proxy/config.yml

Jobber med å flytte testnorge-synt-sykemelding-api ut på gcp. Har dermed lagt til ny app i inbound rules for å teste at ny versjon funker som den skal.

Oppdatert inbound rules

---

apps/dolly-backend/config.yml
proxies/pdl-proxy/config.yml

Jobber med ny versjon av helsepersonell-service som bruker dolly og pdl i stedet for hodejegeren for å hente info om helsepersonell. Har dermed lagt til appen i inbound rules for dolly-backend og pdl-proxy for å kunne teste ny versjon.

Lagt til helsepersonell-service i inbound

---

apps/oversikt-frontend/src/main/js/src/pages/Page/Page.tsx

Oppdatert headerlink sånn at du får token for dolly-backend dev-gcp og ikke dev-fss.

Oversikt frontend - Oppdatert default header link

---

apps/dolly-frontend/src/main/js/src/components/fagsystem/pdlf/visning/VisningRedigerbar.tsx
apps/dolly-frontend/src/main/js/src/components/fagsystem/pdlf/visning/partials/Innvandring.tsx
apps/dolly-frontend/src/main/js/src/components/fagsystem/pdlf/visning/partials/Nasjonalitet.tsx
apps/dolly-frontend/src/main/js/src/components/fagsystem/pdlf/visning/partials/Utvandring.tsx

Har lagt til at kun den siste Inn-eller utvandring kan bli slettet fra personvisning. Du kan altså ikke slette en utvandring hvis personen har innvandret etter utvandringen og vice versa.
Merger denne inn i den andre pr-en jeg har for inn- og utvandring begrensninger.

Dolly frontend/inn utvandring slett disabling

---

apps/dolly-frontend/src/main/js/src/components/bestillingsveileder/stegVelger/steg/steg1/paneler/Personinformasjon.tsx
apps/dolly-frontend/src/main/js/src/components/bestillingsveileder/utils.js
apps/dolly-frontend/src/main/js/src/components/fagsystem/pdlf/form/initialValues.ts
apps/dolly-frontend/src/main/js/src/components/fagsystem/pdlf/form/partials/innvandring/Innvandring.tsx
apps/dolly-frontend/src/main/js/src/components/fagsystem/pdlf/form/partials/utvandring/Utvandring.tsx
apps/dolly-frontend/src/main/js/src/components/fagsystem/pdlf/form/validation.js
apps/dolly-frontend/src/main/js/src/components/fagsystem/pdlf/visning/VisningRedigerbar.tsx
apps/dolly-frontend/src/main/js/src/components/fagsystem/pdlf/visning/partials/Innvandring.tsx
apps/dolly-frontend/src/main/js/src/components/fagsystem/pdlf/visning/partials/Nasjonalitet.tsx
apps/dolly-frontend/src/main/js/src/components/fagsystem/pdlf/visning/partials/Utvandring.tsx
apps/dolly-frontend/src/main/js/src/components/ui/form/fieldArray/DollyFieldArray.js

Har oppdatert bestilling av inn- og utvandring. Du kan nå kun bestille en av hver om gangen. Og hvis en person allerede er innvandret så er bestilling av innvandring disabled. Det samme gjelder også for utvandring. 
I tillegg så kan du nå bare legge til innvandring/utvandring med dato etter siste utvandring/innvandring. Når du lager en ny person kan du velge både inn- og utvandring, men disse kan ikke ha samme dato.

Dolly frontend/innvandring utvandring begrensing

---

apps/dolly-frontend/src/main/js/src/components/bestilling/statusListe/BestillingProgresjon/BestillingProgresjon.tsx
apps/dolly-frontend/src/main/js/src/utils/hooks/useOrganisasjoner.tsx

Tror ikke dette skal føre til noen feil med gjeldende implementasjon siden erOrganisasjon sjekken blir utført i useEffect under hvor statusen tas i bruk, men er jo et unødvendig kall så greit å fjerne😅

Sender ikke orgStatus kall for organisasjon dersom det er identbestilling

---

apps/pdl-forvalter/src/main/java/no/nav/pdl/forvalter/consumer/GeografiskeKodeverkConsumer.java

Testet kontaktinfo for dødsbo, som er den eneste som bruker postnummer kodeverket i pdl forvalteren og den fikk også lik feil som for embete. Har dermed oppdatert query for begge kall.

Pdl-forvalter - Fikset query for geografiske kodeverk

---

apps/dolly-frontend/src/main/js/src/components/ui/form/inputs/datepicker/Datepicker.js

Fiks for string konvertering når man bruker addHours i bostedadresse. Må konvertere den for at validering av dato når man redigerer bostedadresse direkte i personvisning skal funke.

Dolly frontend/fiks string konvertering addHours

---

apps/dolly-frontend/src/main/js/src/components/inntektStub/validerInntekt/Inntekt.js

Liten fiks i inntektstub for sjekking av feil i felt. Nå inkluderer dette også hvis et felt er satt til en verdi som ikke lenger er inkludering i options.

Dolly frontend/inntektstub fiks

---

apps/dolly-frontend/src/main/js/src/components/bestillingsveileder/stegVelger/steg/steg1/attributtVelger/AttributtVelger.less
apps/dolly-frontend/src/main/js/src/components/fagsystem/pdl/visning/PdlVisning.tsx
apps/dolly-frontend/src/main/js/src/pages/gruppe/PersonVisning/PersonMiljoeinfo/PdlDataVisning.tsx

Fikset PDL visning for test-norge identer sånn at alle komponenter strekker seg helt ut til siden. Har også fikset størrelsen (gjort den mindre) på subtittel i bestilling steg 1.

Dolly frontend/fikse visning test norge identer

---

docs/applications/dolly/brukerveiledning.md

Oppdatert brukerveiledning for Dolly til å inkludere link til manuell utlogging i Dolly, som kan brukes hvis du har problemer med å logge inn (som følge av feil med cookies i nettleseren)

Oppdatert brukerveiledning Dolly

---

apps/dolly-frontend/src/main/js/src/pages/testnorgePage/search/partials/Adresser.tsx
apps/dolly-frontend/src/main/js/src/pages/testnorgePage/search/partials/Identifikasjon.tsx

Flyttet adressebeskyttelse option i testnorge søk fra under "Identifikasjon" til øverst under "Adresser":

Dolly frontend - Flyttet adressebeskyttelse option

---

apps/dolly-frontend/src/main/js/src/pages/gruppeOversikt/FinnPersonBestilling.tsx

Har lagt til filtering på søkeresultat fra TPSF. Hvis en ident fra TPSF allerede finnes i søkeresultatet fra PDLF så blir ikke TPSF objectet lagt til (dette for å unngå duplikater med forskjellig navn). Fikk ikke testet ordentlig da jeg ikke kunne gjenskape feilen med duplikater lokalt.

Dolly frontend/filtrere sokeresultat

---

apps/dolly-frontend/src/main/js/src/components/fagsystem/arena/visning/ArenaVisning.js

Data fra arenaforvalteren er ustabilt, fjerner dermed error miljø i arena visning da dette var basert på data fra arena forvalteren.

Dolly frontend - Fjernet errormiljoe arena

---

apps/dolly-frontend/src/main/js/src/components/fagsystem/pdlf/visning/partials/Adressebeskyttelse.tsx
apps/dolly-frontend/src/main/js/src/components/fagsystem/pdlf/visning/partials/Boadresse.tsx
apps/dolly-frontend/src/main/js/src/components/fagsystem/pdlf/visning/partials/Doedsfall.tsx
apps/dolly-frontend/src/main/js/src/components/fagsystem/pdlf/visning/partials/Foedsel.tsx
apps/dolly-frontend/src/main/js/src/components/fagsystem/pdlf/visning/partials/Innvandring.tsx
apps/dolly-frontend/src/main/js/src/components/fagsystem/pdlf/visning/partials/Kontaktadresse.tsx
apps/dolly-frontend/src/main/js/src/components/fagsystem/pdlf/visning/partials/Oppholdsadresse.tsx
apps/dolly-frontend/src/main/js/src/components/fagsystem/pdlf/visning/partials/Persondetaljer.tsx
apps/dolly-frontend/src/main/js/src/components/fagsystem/pdlf/visning/partials/Statsborgerskap.tsx
apps/dolly-frontend/src/main/js/src/components/fagsystem/pdlf/visning/partials/Utvandring.tsx
apps/dolly-frontend/src/main/js/src/components/fagsystem/pdlf/visning/partials/Vergemaal.tsx
apps/dolly-frontend/src/main/js/src/components/fagsystem/sigrunstub/form/Form.js
apps/dolly-frontend/src/main/js/src/ducks/fagsystem/index.js
apps/dolly-frontend/src/main/js/src/utils/hooks/useOrganisasjoner.tsx

Sonarcloud liker ikke lenger når du definerer komponenter inni andre komponenter fordi: _"React will see a new component type on every render and destroy the entire subtree's DOM and nodes."_ . Har dermed oppdatert Pdlf visning partials som har brukt dette. Har ikke gjort noe mer enn å flytte komponentene ut og oppdatert props.
Var flere filer med samme problem igjen, men syns PR-en er stor nok.

Dolly frontend/fikset sonarcloud issue med nested components

---

proxies/arbeidsplassencv-proxy/src/main/java/no/nav/testnav/proxies/arbeidsplassencvproxy/consumer/FakedingsConsumer.java
proxies/arbeidsplassencv-proxy/src/main/resources/application.yml

The old url is deprecated and will be removed soon.

chore(arbeidsplassencv-proxy): update fakedings url

---

.github/workflows/idporten.yml
.github/workflows/maskinporten.yml
.nais/idporten.yml
.nais/maskinporten.yml
apps/dolly-frontend/config.idporten.yml
apps/dolly-frontend/config.yml
apps/organisasjon-tilgang-service/config.yml
apps/person-organisasjon-tilgang-service/config.yml

Spesialoppsett for Dolly som lever i dev men som trenger integrasjoner mot prod-tjenester.
/cc @krharum

legg til oppsett for idporten og maskinporten

---

apps/person-search-service/build.gradle
apps/person-search-service/src/main/java/no/nav/registre/testnorge/personsearchservice/consumer/ElasticSearchConsumer.java
apps/person-search-service/src/main/java/no/nav/registre/testnorge/personsearchservice/service/IdentService.java
apps/person-search-service/src/main/java/no/nav/registre/testnorge/personsearchservice/service/PersonSearchService.java
apps/person-search-service/src/main/java/no/nav/registre/testnorge/personsearchservice/service/utils/AdresserUtils.java
apps/person-search-service/src/main/java/no/nav/registre/testnorge/personsearchservice/service/utils/AlderUtils.java
apps/person-search-service/src/main/java/no/nav/registre/testnorge/personsearchservice/service/utils/IdentifikasjonUtils.java
apps/person-search-service/src/main/java/no/nav/registre/testnorge/personsearchservice/service/utils/NasjonalitetUtils.java
apps/person-search-service/src/main/java/no/nav/registre/testnorge/personsearchservice/service/utils/QueryBuilder.java
apps/person-search-service/src/main/java/no/nav/registre/testnorge/personsearchservice/service/utils/QueryUtils.java
apps/person-search-service/src/main/java/no/nav/registre/testnorge/personsearchservice/service/utils/RelasjonerUtils.java
apps/person-search-service/src/main/java/no/nav/registre/testnorge/personsearchservice/service/utils/StatusUtils.java
apps/person-search-service/src/main/resources/application.yml
apps/person-search-service/src/main/resources/bootstrap.yml

Ser ut som noen elasticSearch dependencies har krasjet med oppsettet vårt etter spring oppdatering, endrer til opensearch implementasjon
#deploy-person-search-service

Refaktorert person-search-service fra elasticSearch -> opensearch

---

apps/dolly-backend/src/main/java/no/nav/dolly/bestilling/tpsmessagingservice/MiljoerConsumer.java
apps/dolly-backend/src/main/java/no/nav/dolly/bestilling/tpsmessagingservice/TpsMessagingClient.java
apps/dolly-backend/src/main/java/no/nav/dolly/bestilling/tpsmessagingservice/command/MiljoerGetCommand.java
apps/dolly-backend/src/main/java/no/nav/dolly/provider/api/BestillingController.java
apps/dolly-backend/src/main/java/no/nav/dolly/service/BestillingService.java
apps/dolly-backend/src/test/java/no/nav/dolly/service/BestillingServiceTest.java

The code has been modified to import 'MiljoerConsumer' and the necessary changes have been made to the 'BestillingServiceTest.java' test cases to handle valid environments only. Also, redundant variables 'BRUKERNAVN' and 'EPOST' were removed. A method has been added to filter available environments and ensure that only valid environments are included while processing. Classes 'TpsMessagingClient.java' and 'BestillingController.java' were also adjusted accordingly to use the new method.

Refactor BestillingServiceTest to handle valid environments

---

apps/dolly-backend/src/main/java/no/nav/dolly/bestilling/aareg/AaregClient.java
apps/dolly-backend/src/main/java/no/nav/dolly/bestilling/aareg/amelding/AmeldingConsumer.java
apps/dolly-backend/src/main/java/no/nav/dolly/bestilling/aareg/amelding/AmeldingService.java
apps/dolly-backend/src/main/java/no/nav/dolly/bestilling/aareg/command/AmeldingPutCommand.java
apps/dolly-backend/src/main/java/no/nav/dolly/bestilling/pdldata/command/PdlDataOppdateringCommand.java
apps/dolly-backend/src/main/java/no/nav/dolly/bestilling/pdldata/command/PdlDataOpprettingCommand.java
apps/dolly-backend/src/main/java/no/nav/dolly/bestilling/pdldata/command/PdlDataOrdreCommand.java
apps/dolly-backend/src/main/java/no/nav/dolly/bestilling/pensjonforvalter/PensjonforvalterConsumer.java
apps/dolly-backend/src/main/java/no/nav/dolly/bestilling/pensjonforvalter/command/LagreAlderspensjonCommand.java
apps/dolly-backend/src/main/java/no/nav/dolly/bestilling/pensjonforvalter/command/LagrePoppInntektCommand.java
apps/dolly-backend/src/main/java/no/nav/dolly/bestilling/pensjonforvalter/command/LagreTpForholdCommand.java
apps/dolly-backend/src/main/java/no/nav/dolly/bestilling/pensjonforvalter/command/LagreTpYtelseCommand.java
apps/dolly-backend/src/main/java/no/nav/dolly/bestilling/pensjonforvalter/command/LagreUforetrygdCommand.java
apps/dolly-backend/src/main/java/no/nav/dolly/bestilling/tpsmessagingservice/command/EgenansattPostCommand.java
apps/dolly-backend/src/main/java/no/nav/dolly/bestilling/tpsmessagingservice/command/TpsMessagingPostCommand.java
apps/dolly-backend/src/main/java/no/nav/dolly/util/RequestTimeout.java

#deploy-test-dolly-backend #deploy-dolly-backend
Implemented a standard timeout defined as REQUEST_DURATION constant used across multiple classes' httpClientRequests. This refactoring ensures the application aborts requests to prevent hang-ups due to slow or unresponsive servers.

Refactor httpClientRequests to add responseTimeout

---

.github/workflows/app.team-dolly-lokal-app.yml
.nais/team-dolly-lokal-app.yml

This commit creates a new AzureAdApplication named team-dolly-lokal-app. The configuration includes specific pre-authorized applications, a logoutURL, and various other details. Additionally, a new GitHub workflow file for deploying this application is added, which includes the necessary steps, permissions, and uses the new team-dolly-lokal-app.yml for deployment.

Add new AzureAdApplication and GitHub workflow files

---

apps/dolly-frontend/src/main/js/src/components/adresseVelger/AdresseSok.tsx
apps/dolly-frontend/src/main/js/src/components/fagsystem/organisasjoner/form/partials/Adresser.tsx
apps/dolly-frontend/src/main/js/src/components/fagsystem/pdlf/form/partials/foedsel/Foedsel.tsx
apps/kodeverk-service/src/main/java/no/nav/testnav/kodeverkservice/consumer/KodeverkConsumer.java
apps/kodeverk-service/src/main/java/no/nav/testnav/kodeverkservice/provider/KodeverkController.java
apps/kodeverk-service/src/main/java/no/nav/testnav/kodeverkservice/utility/FilterUtility.java
apps/kodeverk-service/src/main/java/no/nav/testnav/kodeverkservice/utility/KommunerUtility.java

The logic for filtering "kommune" codes based on the year 2024 has been shifted to the KodeverkConsumer class from the Kodeverk controller class. A utility function filterKommuner2024 has also been updated to work with KodeverkBetydningerResponse type instead of KodeverkDTO and KodeverkAdjustedDTO. This change improves the structure and organization of the code.

Refaktorert Kommuner2024

---

apps/organisasjon-faste-data-service/src/main/java/no/nav/registre/testnorge/organisasjonfastedataservice/consumer/OrganisasjonMottakConsumer.java

Denne sjekken gjør at resten av adresse ikke sendes inn dersom kommunenummer mangler, men ser det er flere tilfeller av slike org i q2 og de andre miljøene allerede, tilsynelatende uten feil.

Fjerner sjekk for kommunenr på adresser i org-faste-data-service

---

apps/dolly-frontend/src/main/js/src/components/fagsystem/pdlf/form/partials/familierelasjoner/foreldreansvar/Foreldreansvar.tsx

Changed condition to display the PdlEksisterendePerson component when `ansvar` equals 'ANDRE' instead of only `kanHaForeldreansvar`. This ensures the correct UI behavior based on the specified responsibility criteria.

Update condition for displaying existing person component

---

apps/pdl-forvalter/src/main/java/no/nav/pdl/forvalter/service/AdresseService.java
apps/pdl-forvalter/src/main/java/no/nav/pdl/forvalter/service/BostedAdresseService.java
apps/pdl-forvalter/src/main/java/no/nav/pdl/forvalter/service/KontaktAdresseService.java
apps/pdl-forvalter/src/main/java/no/nav/pdl/forvalter/service/OppholdsadresseService.java
apps/pdl-forvalter/src/main/java/no/nav/pdl/forvalter/utils/ArtifactUtils.java
apps/pdl-forvalter/src/test/java/no/nav/pdl/forvalter/service/AdressebeskyttelseServiceTest.java
apps/pdl-forvalter/src/test/java/no/nav/pdl/forvalter/service/FolkeregisterPersonstatusServiceTest.java
apps/pdl-forvalter/src/test/java/no/nav/pdl/forvalter/service/InnflyttingServiceTest.java
apps/pdl-forvalter/src/test/java/no/nav/pdl/forvalter/service/UtflyttingServiceTest.java

#deploy-test-pdl-forvalter #deploy-pdl-forvalter
Added support for setting person identification (FNR_IDENT and DNR_IDENT) in various tests to ensure correct data handling. Enhanced validation logic for address handling based on the type of identification in service classes.

Add support for person identification in tests

---

apps/pdl-forvalter/src/main/java/no/nav/pdl/forvalter/service/ForeldreansvarService.java
apps/pdl-forvalter/src/main/java/no/nav/pdl/forvalter/service/MetadataTidspunkterService.java
apps/pdl-forvalter/src/main/java/no/nav/pdl/forvalter/service/PdlOrdreService.java

#deploy-pdl-forvalter
Converted several private methods to static for consistent access. Introduced the fixOpphoert method to handle address cessation timestamps. This change improves code readability and maintainability in the MetadataTidspunkterService class.

Refactor MetadataTidspunkterService to use static methods

---

apps/person-service/src/main/java/no/nav/testnav/apps/personservice/consumer/v1/PdlApiConsumer.java
apps/person-service/src/main/java/no/nav/testnav/apps/personservice/consumer/v1/pdl/graphql/HentPerson.java
apps/person-service/src/main/resources/pdl/pdl-api-schema.graphql
apps/person-service/src/main/resources/pdl/pdlPersonQuery.graphql

#deploy-person-service
Added new metadata fields to the PdlApiConsumer and updated related GraphQL queries to fetch comprehensive person details. This enhancement includes fields like address protection, birthplaces, and security measures, improving the data completeness for consumer operations.

Enhance PdlApiConsumer with additional metadata fields

---

apps/dolly-backend/README.md
apps/dolly-backend/src/main/java/no/nav/dolly/bestilling/pensjonforvalter/PensjonforvalterClient.java
apps/dolly-backend/src/main/java/no/nav/dolly/bestilling/pensjonforvalter/PensjonforvalterConsumer.java
apps/dolly-backend/src/main/java/no/nav/dolly/bestilling/pensjonforvalter/command/LagreAfpOffentligCommand.java
apps/dolly-backend/src/main/java/no/nav/dolly/elastic/ElasticTyper.java
apps/dolly-backend/src/main/java/no/nav/dolly/elastic/dto/Kategori.java
apps/dolly-backend/src/main/java/no/nav/dolly/elastic/dto/Type.java
apps/dolly-backend/src/main/java/no/nav/dolly/elastic/mapper/ElasticBestillingStrategyMapping.java
apps/dolly-backend/src/main/java/no/nav/dolly/elastic/service/OpenSearchService.java
apps/dolly-backend/src/main/java/no/nav/dolly/provider/api/OpensearchController.java

#deploy-test-dolly-backend
Updated `ElasticTyper` with more intuitive descriptions and alphabetical order. Added a new `Type` class and corresponding `/typer` endpoint for fetching all searchable types. Improved indexing and mapping strategies in `ElasticBestillingStrategyMapping` and adjusted `PensjonforvalterConsumer` methods to pass `ident` parameter directly.

Refactor ElasticTyper descriptions and add Type endpoint

---

apps/dolly-frontend/src/main/js/package-lock.json
apps/dolly-frontend/src/main/js/package.json
apps/dolly-frontend/src/main/js/src/api/index.ts
apps/dolly-frontend/src/main/js/src/components/fagsystem/pdlf/visning/visningRedigerbar/VisningRedigerbarPersondetaljer.tsx
apps/dolly-frontend/src/main/js/src/service/services/skjerming/SkjermingService.tsx

This pull request updates several dependencies in the `package-lock.json` file to their latest versions. The changes primarily focus on updating versions to improve security, performance, and compatibility.
Code refactor/Bug fixes:
* Fixed faulty deletion of skjerming in personVisningRedigering
* Changed fetch_retry to skip retrying if endpoint returns a 404 status
Dependency updates:
* Updated the project version to `3.0.41` (`apps/dolly-frontend/src/main/js/package-lock.json`).
Major dependency updates:
* Updated `@inquirer/confirm` from `3.2.0` to `4.0.1`, along with its dependencies (`@inquirer/core` and `@inquirer/type`) to newer versions (`apps/dolly-frontend/src/main/js/package-lock.json`) [[1]](diffhunk://#diff-f927473d3cafe422c5ebd1b4ac3667070f49100c00f35f5054faadf3433a6434L1531-R …

Fikset sletting av skjerming og oppdatert brukte dependencies

---

apps/dolly-frontend/src/main/js/src/api/index.ts
apps/dolly-frontend/src/main/js/src/app/App.tsx

This pull request introduces a new function to clear large cookies before making network requests and includes a temporary useEffect hook to create test cookies in the `App` component. The most important changes are as follows:
* Added a `clearLargeCookies` function to remove cookies larger than 1000 characters. This function is called before making requests in `fetcher`, `imageFetcher`, and `_fetch` functions in `apps/dolly-frontend/src/main/js/src/api/index.ts`. [[1]](diffhunk://#diff-5646f504929598c66db8abe597b5eb5b67bb1d83e3de6df6de24cfee3e4a3c22L133-R146) [[2]](diffhunk://#diff-5646f504929598c66db8abe597b5eb5b67bb1d83e3de6df6de24cfee3e4a3c22R167-R174) [[3]](diffhunk://#diff-5646f504929598c66db8abe597b5eb5b67bb1d83e3de6df6de24cfee3e4a3c22L169-R186) …

Fix for frontend cookie haandtering

---

apps/person-service/src/main/resources/pdl/pdlPerson2Query.graphql
apps/person-service/src/main/resources/pdl/pdlPersonQuery.graphql
apps/person-service/src/main/resources/pdl/pdlbolkquery.graphql

Removed 'fullmakt' field from pdlbolkquery.graphql, pdlPerson2Query.graphql, and pdlPersonQuery.graphql. This exclusion simplifies the query structure and eliminates redundant data retrieval related to fullmakt details.

Remove 'fullmakt' from GraphQL queries

---

.nais/idporten.yml

Dolly shouldn't be a part of the SSO circle-of-trust with many other public services.
See https://docs.digdir.no/docs/idporten/oidc/oidc_func_nosso.html.

disable SSO for ID-porten

---

.github/workflows/common.workflow.backend.yml
.github/workflows/common.workflow.frontend.yml

Mindre endringer, ref. https://nav-it.slack.com/archives/C01DE3M9YBV/p1737982464376109.

Removes deprecated identity_provider and project_id from docker-build-push.

---

apps/levende-arbeidsforhold-ansettelse/src/main/resources/application-local.yml
apps/levende-arbeidsforhold-ansettelse/src/main/resources/db/local/V1.0.1__AddLocalTestData.sql
apps/levende-arbeidsforhold-ansettelse/src/main/resources/db/local/default-config.sql

Fikser oppstart lokalt med tom DB, ref. `docker-compose.yml`.

Refactored default localhost test data initialization as a Flyway (minor) migration, to avoid a chicken-and-egg situation on starting a clean DB.

---

apps/dolly-backend/src/main/java/no/nav/dolly/bestilling/pensjonforvalter/PensjonforvalterClient.java
apps/dolly-backend/src/main/java/no/nav/dolly/bestilling/pensjonforvalter/PensjonforvalterConsumer.java
apps/dolly-backend/src/main/java/no/nav/dolly/bestilling/pensjonforvalter/command/LagreAlderspensjonCommand.java
apps/dolly-backend/src/main/java/no/nav/dolly/bestilling/pensjonforvalter/command/SlettePoppInntektCommand.java

This pull request includes several changes to the `pensjonforvalter` module in the `dolly-backend` application, mainly focusing on adding support for deleting POPP income data and updating existing endpoints.
* Added a new method `slettePoppinntekt` in `PensjonforvalterConsumer` to handle the deletion of POPP income data.
* Introduced a new command class `SlettePoppInntektCommand` to execute the deletion of POPP income data.
* Updated the `release` method in `PensjonforvalterClient` to include the deletion of POPP income data.
* Added `com.sun.jna.Function` import in `PensjonforvalterConsumer`.
* Updated the endpoint URL for saving alderspensjon applications in `LagreAlderspensjonCommand`.…-test-dolly-backend

Pensjon nytt endepunkt for AP søknad + sletting av POPP-inntekt

---

apps/dolly-frontend/src/main/js/src/components/bestillingsveileder/stegVelger/StegVelger.tsx
apps/dolly-frontend/src/main/js/src/components/fagsystem/pdlf/visning/visningRedigerbar/VisningRedigerbar.tsx
apps/dolly-frontend/src/main/js/src/pages/organisasjoner/OrganisasjonTenorSoek/SoekFormOrg.tsx
apps/dolly-frontend/src/main/js/src/pages/tenorSoek/SoekForm.tsx

This pull request includes changes to the `apps/dolly-frontend` project, primarily focusing on enhancing the visibility of form state and errors for administrators. The main changes involve importing a new utility function and updating conditional rendering logic to include checks for admin status.
Enhancements for admin visibility:
* [`apps/dolly-frontend/src/main/js/src/components/bestillingsveileder/stegVelger/StegVelger.tsx`](diffhunk://#diff-e1870d3da9228c44262d963cbb671e54a8850ad5160eb6d38a0a0d2c6f18da6bR33): Added import for `erDollyAdmin` utility function and updated conditional rendering to display form state and errors if the user is an admin. [[1]](diffhunk://#diff-e1870d3da9228c44262d963cbb671e54a8850ad5160eb6d38a0a0d2c6f18da6bR33) …

Viser form values i "prod" dersom man er dollyAdmin

---

.github/workflows/common.workflow.libs.frontend.yml
apps/dollystatus/src/main/js/package-lock.json
apps/dollystatus/src/main/js/package.json
apps/endringsmelding-frontend/src/main/js/package-lock.json
apps/endringsmelding-frontend/src/main/js/package.json
apps/faste-data-frontend/src/main/js/package-lock.json
apps/faste-data-frontend/src/main/js/package.json
apps/oversikt-frontend/src/main/js/package-lock.json
apps/oversikt-frontend/src/main/js/package.json
navikt/dolly-assets/package-lock.json
navikt/dolly-assets/package.json
navikt/dolly-komponenter/package-lock.json
navikt/dolly-komponenter/package.json
navikt/dolly-lib/package-lock.json
navikt/dolly-lib/package.json

This pull request includes several changes to the project, primarily focusing on updating package versions and improving the release process. The most important changes are detailed below:
* Enhanced the npm release process in `.github/workflows/common.workflow.libs.frontend.yml` by adding steps to configure git, commit, and push changes automatically after publishing a new version.
* Updated the version numbers in various `package.json` files to reflect new releases:
- `apps/dollystatus/src/main/js/package.json` from `1.1.14` to `1.1.15`
- `apps/endringsmelding-frontend/src/main/js/package.json` from `1.2.30` to `1.2.31`
- `apps/faste-data-frontend/src/main/js/package.json` from `1.2.16` to `1.2.17`
- `apps/oversikt-frontend/src/main/js/package.json` from `1.2.18` to `1.2.19`
- …

Fikset Publish workflow som feiler ved push til master

---

apps/dolly-frontend/src/main/js/package-lock.json
apps/dolly-frontend/src/main/js/package.json
apps/dolly-frontend/src/main/js/src/components/fagsystem/afpOffentlig/form/Form.tsx
apps/dolly-frontend/src/main/js/src/components/fagsystem/afpOffentlig/visning/AfpOffentligVisning.tsx
apps/dolly-frontend/src/main/js/src/components/fagsystem/tjenestepensjon/visning/TpYtelse.tsx
apps/dolly-frontend/src/main/js/src/pages/gruppe/PersonVisning/PersonVisning.tsx
apps/dolly-frontend/src/main/js/src/utils/SjekkBestillingFagsystem.tsx
apps/dolly-frontend/src/main/js/src/utils/hooks/useFagsystemer.tsx
apps/dolly-frontend/src/main/js/src/utils/hooks/usePensjon.tsx

- Lagt til henting og visning av TpYtelse
- Mindre refaktorering rundt pensjon intgrasjon i Dolly frontend
- Oppdateringer

Henting og visning av Pensjonsytelse

---

apps/faste-data-frontend/src/main/js/package-lock.json
apps/faste-data-frontend/src/main/js/package.json
apps/faste-data-frontend/src/main/js/src/index.tsx

This pull request updates the frontend application to use the latest React rendering API and bumps several package versions. The most significant change is migrating from the legacy `ReactDOM.render` method to the modern `createRoot` API, which is recommended for React 18 and above. Additionally, some dependencies are updated for improved compatibility and features.
**React 18 migration:**
* Refactored the entry point in `index.tsx` to use `createRoot` from `react-dom/client` instead of `ReactDOM.render`, adding a runtime check for the root element.
**Dependency updates:**
* Updated `@vitejs/plugin-react` from version `4.0.0` to `5.0.2` in `package.json` for improved Vite and React integration.
* Bumped the application version from `1.2.21` to `1.2.22` in `package.json`.

Fix faste data frontend

---

apps/dolly-frontend/src/main/js/src/components/bestillingsveileder/stegVelger/steg/steg1/paneler/Sykdom.tsx
apps/dolly-frontend/src/main/js/src/components/bestillingsveileder/stegVelger/steg/steg3/Steg3.tsx
apps/dolly-frontend/src/main/js/src/components/fagsystem/sykdom/form/partials/DetaljertSykemelding.tsx
apps/dolly-frontend/src/main/js/src/components/fagsystem/sykdom/form/validation.tsx
apps/dolly-frontend/src/main/js/src/components/fagsystem/sykdom/visning/Visning.tsx
apps/dolly-frontend/src/main/js/src/components/miljoVelger/MiljoVelger.tsx
apps/dolly-frontend/src/main/js/src/components/miljoVelger/MiljoeInfo.tsx

This pull request refactors how "sykemelding" (sick leave) data is handled across several components by removing the use of the `detaljertSykemelding` property and simplifying logic to check for the presence of `sykemelding` directly. This results in cleaner, more maintainable code and more consistent handling of the "sykemelding" attribute throughout the application.
**Refactoring and simplification of "sykemelding" handling:**
* Removed all logic and UI that specifically checked for `sykemelding.detaljertSykemelding`, now checking for the presence of `sykemelding` instead in `MiljoVelger.tsx`, `MiljoeInfo.tsx`, and `Steg3.tsx`. [[1]](diffhunk://#diff-8b82f2cfcc1edfc332e0141f007bf44cfd6722c284a477dc0c537d84c025a147L35-R35) [[2]](diffhunk://#diff-389809370cbf65c811e23ea23948983c96d06bc0790 …

Innsending av flere sykemeldinger
