navikt/testnorge

- apps/testnorge-skd/README.md
- apps/testnorge-skd/pom.xml
- apps/testnorge-skd/skd-core/pom.xml
- apps/testnorge-skd/skd-core/src/main/java/no/nav/registre/skd/config/dev/VaultConfig.java
- apps/testnorge-skd/skd-core/src/main/resources/application.properties
- apps/testnorge-skd/skd-core/src/main/resources/bootstrap-prod.yml
- apps/testnorge-skd/skd-core/src/test/java/no/nav/registre/skd/comptests/FeilhaandteringCompTest.java
- apps/testnorge-skd/skd-core/src/test/java/no/nav/registre/skd/consumer/TpConsumerTest.java
- apps/testnorge-skd/skd-core/src/test/java/no/nav/registre/skd/consumer/TpsSyntetisererenConsumerTest.java
- apps/testnorge-skd/skd-core/src/test/java/no/nav/registre/skd/consumer/TpsfConsumerTest.java
- apps/testnorge-skd/skd-core/src/test/resources/application-test.properties
- apps/testnorge-skd/skd-local/src/main/resources/application-local.properties
- apps/testnorge-skd/skd-local/src/main/resources/application.properties
- apps/testnorge-skd/skd-local/src/main/resources/bootstrap-local.yml
Lagt til vault lokalt for testnorge-skd og flyttet url i properties til vault.
> REG-8731 lagt til vault lokalt for testnorge-skd

- apps/testnorge-populasjoner/src/main/resources/application-local.properties
- apps/testnorge-populasjoner/src/main/resources/bootstrap-local.yml
Fikk feil i deployment for populasjoner, så jeg endret det tilbake.
> Fjernet endringer populasjoner

- apps/testnorge-populasjoner/Dockerfile
- apps/testnorge-populasjoner/src/main/resources/application-local.properties
- apps/testnorge-populasjoner/src/main/resources/bootstrap-local.yml
Feilet igjen å deploye populasjoner så jeg har oppdatert dockerfile.
> REG-8732 oppdatert properties og dockerfile for populasjoner

- apps/testnorge-token-provider/Dockerfile
Tror jeg fant hvorfor appen ikke ville deploye, profile ble ikke satt til prod i dockerfile.
> Satt profile lik prod i dockerfile

- apps/testnorge-aareg/README.md
- apps/testnorge-token-provider/README.md
Nå skal alle apps i testnorge ha en readme fil med generell beskrivelse og info om hvordan de kan kjøres lokalt :D
> REG-8732 oppdatert readme for aareg og token-provider

- apps/testnorge-arena/arena-core/pom.xml
La merke til at lokal kjøring ikke lenger funket for testnorge-arena. Fikk fikset det, men det er mulig at det er samme feil i andre applikasjoner også.
> Oppdatert pom i testnorge-arena for lokal kjoering

- .github/workflows/deploy-syntrest.yml
> Endret api key

- apps/testnorge-spion/README.md
- apps/testnorge-spion/pom.xml
- apps/testnorge-spion/src/main/java/no/nav/registre/spion/config/dev/VaultConfig.java
- apps/testnorge-spion/src/main/resources/bootstrap-dev.yaml
- apps/testnorge-spion/src/test/resources/application-test.properties
- apps/testnorge-spion/src/test/resources/bootstrap-test.yaml
Aileen har testet at denne fiksen kjører lokalt.
Det som var feil, var antakelig bare konfigurering av vault, og at pom'en hentet sin egen versjon av spring-core/cloud.
> Testnorge spion deployment fix

- apps/syntrest/src/main/java/no/nav/registre/syntrest/consumer/SyntConsumer.java
- apps/syntrest/src/main/resources/application-prod.properties
- apps/syntrest/src/main/resources/application.properties
Dette siden `.dev.adeo.no` ikke sees ut som den kan nås "innenfra".
> Foreløpig rollback av isAlive parameteren

- apps/syntrest/src/main/java/no/nav/registre/syntrest/config/AppConfig.java
- apps/syntrest/src/main/java/no/nav/registre/syntrest/kubernetes/KubernetesController.java
Siden vi fikk hadde problemer med timeout for synt-meldekort i går, gikk jeg gjennom og testet de andre synt-applikasjonene som er flyttet til github for å dobbelsjekke at de funket som de skal. Så at synt-sam også hadde timeout error så jeg økte timeout verdi igjen for å se om det fikser problemet.
> Satt hoeyere timeout verdi

- apps/helsepersonell-api/src/main/java/no/nav/registre/testnorge/helsepersonell/adapter/HelsepersonellAdapter.java
- apps/helsepersonell-api/src/main/java/no/nav/registre/testnorge/helsepersonell/consumer/HodejegerenConsumer.java
- apps/helsepersonell-api/src/main/java/no/nav/registre/testnorge/helsepersonell/domain/Helsepersonell.java
- apps/helsepersonell-api/src/main/java/no/nav/registre/testnorge/helsepersonell/domain/HelsepersonellListe.java
- apps/helsepersonell-api/src/main/java/no/nav/registre/testnorge/helsepersonell/domain/Samhandler.java
- apps/helsepersonell-api/src/main/java/no/nav/registre/testnorge/helsepersonell/provider/HelsepersonellController.java
- apps/helsepersonell-api/src/main/resources/application-prod.properties
- apps/helsepersonell-api/src/test/java/no/nav/registre/testnorge/helsepersonell/provider/HelsepersonellControllerIntegrationTest.java
- apps/helsepersonell-api/src/test/resources/application-test.properties
- apps/sykemelding-api/src/main/java/no/nav/registre/testnorge/sykemelding/domain/Dokument.java
- apps/sykemelding-api/src/main/java/no/nav/registre/testnorge/sykemelding/domain/Helsepersonell.java
- apps/sykemelding-api/src/main/java/no/nav/registre/testnorge/sykemelding/domain/Pasient.java
- apps/sykemelding-api/src/main/java/no/nav/registre/testnorge/sykemelding/domain/Sykemelding.java
- apps/sykemelding-api/src/test/java/no/nav/registre/testnorge/sykemelding/provider/SykemeldingControllerTest.java
- apps/synt-sykemelding-api/src/main/java/no/nav/registre/testnorge/synt/sykemelding/consumer/HelsepersonellConsumer.java
- apps/synt-sykemelding-api/src/main/java/no/nav/registre/testnorge/synt/sykemelding/domain/Helsepersonell.java
- apps/synt-sykemelding-api/src/main/java/no/nav/registre/testnorge/synt/sykemelding/domain/HelsepersonellListe.java
- apps/synt-sykemelding-api/src/main/java/no/nav/registre/testnorge/synt/sykemelding/domain/Sykemelding.java
- apps/synt-sykemelding-api/src/main/java/no/nav/registre/testnorge/synt/sykemelding/service/SykemeldingService.java
- apps/synt-sykemelding-api/src/test/java/no/nav/registre/testnorge/synt/sykemelding/provider/SyntSykemeldingControllerIntegrationTest.java
- apps/synt-sykemelding-api/src/test/java/no/nav/registre/testnorge/synt/sykemelding/util/TestUtil.java
- libs/testnorge-data-transfer-objects/src/main/java/no/nav/registre/testnorge/libs/dto/helsepersonell/v1/HelsepersonellDTO.java
- libs/testnorge-data-transfer-objects/src/main/java/no/nav/registre/testnorge/libs/dto/helsepersonell/v1/HelsepersonellListeDTO.java
- libs/testnorge-data-transfer-objects/src/main/java/no/nav/registre/testnorge/libs/dto/sykemelding/v1/HelsepersonellDTO.java
- libs/testnorge-data-transfer-objects/src/main/java/no/nav/registre/testnorge/libs/dto/sykemelding/v1/SykemeldingDTO.java
Lagt til samhandlertype og endret fra lege til helsepersonell
> Lagt til samhandlertype til helsepersonell

- apps/testnorge-frikort/src/main/java/no/nav/registre/frikort/consumer/rs/response/SyntFrikortResponseDTO.java
- apps/testnorge-frikort/src/main/java/no/nav/registre/frikort/exceptions/UgyldigEgenandelskodeException.java
- apps/testnorge-frikort/src/main/java/no/nav/registre/frikort/exceptions/UgyldigSamhandlerdataException.java
- apps/testnorge-frikort/src/main/java/no/nav/registre/frikort/provider/rs/IdentController.java
- apps/testnorge-frikort/src/main/java/no/nav/registre/frikort/service/IdentService.java
- apps/testnorge-frikort/src/main/java/no/nav/registre/frikort/service/KonverteringService.java
- apps/testnorge-frikort/src/main/java/no/nav/registre/frikort/service/util/ServiceUtils.java
Refaktorerte testnorge frikort til å ikke bruke muterende metoder for klassen SyntFrikortResponse.
> Testnorge frikort/oversiktelig logging

- apps/person-api/src/main/java/no/nav/registre/testnorge/person/adapter/PdlPersonAdapter.java
- apps/person-api/src/main/java/no/nav/registre/testnorge/person/adapter/PersonAdapter.java
- apps/person-api/src/main/java/no/nav/registre/testnorge/person/adapter/TpsPersonAdapter.java
- apps/person-api/src/main/java/no/nav/registre/testnorge/person/consumer/PdlTestdataConsumer.java
- apps/person-api/src/main/java/no/nav/registre/testnorge/person/consumer/command/PostAdresseCommand.java
- apps/person-api/src/main/java/no/nav/registre/testnorge/person/consumer/command/PostNavnCommand.java
- apps/person-api/src/main/java/no/nav/registre/testnorge/person/consumer/command/PostOpprettPersonCommand.java
- apps/person-api/src/main/java/no/nav/registre/testnorge/person/consumer/dto/pdl/AdresseDTO.java
- apps/person-api/src/main/java/no/nav/registre/testnorge/person/consumer/dto/pdl/NavnDTO.java
- apps/person-api/src/main/java/no/nav/registre/testnorge/person/consumer/header/PdlHeaders.java
- apps/person-api/src/main/java/no/nav/registre/testnorge/person/provider/PersonController.java
- apps/person-api/src/main/java/no/nav/registre/testnorge/person/service/PersonService.java
- apps/testnorge-statisk-data-forvalter/src/main/java/no/nav/registre/sdforvalter/consumer/rs/command/PostPersonCommand.java
Lagt til mulighet for å velge kilde selv. Hvis ikke er default DOLLY. Tycks? Alternativet blir å ha en ``if (kilde == null) {kilde = "DOLLY"} else {kilde = kilde}``
> Legge til kilde som optional requestparameter til create person

- apps/person-api/src/main/java/no/nav/registre/testnorge/person/consumer/PdlTestdataConsumer.java
Har du et mer elegant forslag?
> Sjekke om navn og adresse finnes på person før de legges til i PDL

- apps/testnorge-statisk-data-forvalter/src/main/java/no/nav/registre/sdforvalter/adapter/AaregAdapter.java
- apps/testnorge-statisk-data-forvalter/src/main/java/no/nav/registre/sdforvalter/adapter/EregAdapter.java
- apps/testnorge-statisk-data-forvalter/src/main/java/no/nav/registre/sdforvalter/adapter/FasteDataAdapter.java
- apps/testnorge-statisk-data-forvalter/src/main/java/no/nav/registre/sdforvalter/adapter/KrrAdapter.java
- apps/testnorge-statisk-data-forvalter/src/main/java/no/nav/registre/sdforvalter/adapter/TpsIdenterAdapter.java
- apps/testnorge-statisk-data-forvalter/src/main/java/no/nav/registre/sdforvalter/database/model/EregTagModel.java
- apps/testnorge-statisk-data-forvalter/src/main/java/no/nav/registre/sdforvalter/database/model/TpsIdentTagModel.java
- apps/testnorge-statisk-data-forvalter/src/main/java/no/nav/registre/sdforvalter/database/repository/AaregRepository.java
- apps/testnorge-statisk-data-forvalter/src/main/java/no/nav/registre/sdforvalter/database/repository/EregRepository.java
- apps/testnorge-statisk-data-forvalter/src/main/java/no/nav/registre/sdforvalter/database/repository/KrrRepository.java
- apps/testnorge-statisk-data-forvalter/src/main/java/no/nav/registre/sdforvalter/database/repository/TpsIdenterRepository.java
- apps/testnorge-statisk-data-forvalter/src/test/java/no/nav/registre/sdforvalter/provider/rs/v2/StaticDataControllerV2EregIntegrationTest.java
Den ene testen feiler fortsatt (StaticDataControllerV2EregIntegrationTest.java). Tror problemet er at gruppe-parameteren ikke blir med i mvc.perform, men da skjønner jeg ikke hvordan den kunne fungere før heller.
> Filtrere faste data i sql-spørring

- apps/testnorge-arena/arena-core/src/main/java/no/nav/registre/arena/core/service/RettighetTiltakService.java
- apps/testnorge-arena/arena-core/src/main/java/no/nav/registre/arena/core/service/VedtakshistorikkService.java
- apps/testnorge-arena/arena-core/src/main/java/no/nav/registre/arena/core/service/util/ServiceUtils.java
Har fått tilbakemelding fra Arena at tiltaksdeltakelse, tiltakspenger og barnetillegg vedtak bør ha samme dato som tiltaket man finner for tiltaksdeltakelse.
> Oppdatert datoer for tiltak vedtak

- apps/testnorge-arena/arena-core/src/main/java/no/nav/registre/arena/core/consumer/rs/command/PostRettighetCommand.java
Liten fiks. Har oppdatert exception handling for innsendelse av rettighet til arena sånn at uforutsette feiler ikke stopper innsendelse av resten av historikk.
> Oppdatert exception handling

- apps/syntrest/src/main/java/no/nav/registre/syntrest/config/AppConfig.java
- apps/syntrest/src/main/java/no/nav/registre/syntrest/controllers/SyntController.java
Vil teste og se om egen consumer for et av synthdata-amelding endepunktene vil fikse deploy problemene.
> Lagd egen consumer for arbeidsforhold start

- apps/syntrest/src/main/java/no/nav/registre/syntrest/config/AppConfig.java
- apps/syntrest/src/main/java/no/nav/registre/syntrest/controllers/SyntController.java
> Lagt consumer for hvert amelding endepunkt

- apps/syntrest/build.gradle
- apps/syntrest/src/main/java/no/nav/registre/syntrest/config/AppConfig.java
- apps/syntrest/src/main/java/no/nav/registre/syntrest/consumer/SyntAmeldingConsumer.java
- apps/syntrest/src/main/java/no/nav/registre/syntrest/consumer/SyntConsumer.java
- apps/syntrest/src/main/java/no/nav/registre/syntrest/consumer/command/PostArbeidsforholdCommand.java
- apps/syntrest/src/main/java/no/nav/registre/syntrest/consumer/command/PostArbeidsforholdStartCommand.java
- apps/syntrest/src/main/java/no/nav/registre/syntrest/controllers/SyntController.java
- apps/syntrest/src/main/resources/application-dev.properties
- apps/syntrest/src/main/resources/application-prod.properties
- apps/syntrest/src/main/resources/nais/synthdata-amelding.yaml
- apps/syntrest/src/test/java/no/nav/registre/syntrest/consumer/SyntConsumerTest.java
- apps/syntrest/src/test/java/no/nav/registre/syntrest/controllers/SyntControllerTest.java
Har lagd en egen consumer for synthdata-amelding som er en subclass av `SyntConsumer`. Har også økt minne i `synthdata-amelding.yml.`
> Lagt til egen consumer for syntamelding

- apps/oversikt-frontend/src/main/resources/application.yml
Får ikke kjørt oversikt lokalt fordi azure client ID og secret ikke blir hentet lokalt :/
> Lagt til ident-check-in-prod app til oversikt

- apps/testnorge-statisk-data-forvalter/build.gradle
- apps/testnorge-statisk-data-forvalter/src/main/java/no/nav/registre/sdforvalter/provider/rs/v1/OrganisasjonControllerV1.java
- apps/testnorge-statisk-data-forvalter/src/test/java/no/nav/registre/sdforvalter/provider/rs/v1/StaticDataControllerV1OrganisasjonIntegrationTest.java
Fant ikke ut av hvorfor den delen av testen jeg fjerna fungerte lokalt, men ikke remote. Testen burde være grei uten.
> Bugfix test testnorge-sdf

- .github/workflows/deploy.tps-ident-service.yml
- apps/oversikt-frontend/src/main/resources/application.yml
- apps/tps-ident-service/Dockerfile
- apps/tps-ident-service/README.md
- apps/tps-ident-service/build.gradle
- apps/tps-ident-service/config.yml
- apps/tps-ident-service/src/main/java/no/nav/registre/tpsidentservice/TpsIdentServiceApplicationStarter.java
- apps/tps-ident-service/src/main/java/no/nav/registre/tpsidentservice/config/ApplicationConfig.java
- apps/tps-ident-service/src/main/java/no/nav/registre/tpsidentservice/config/OpenApiConfig.java
- apps/tps-ident-service/src/main/java/no/nav/registre/tpsidentservice/config/SecurityConfig.java
- apps/tps-ident-service/src/main/java/no/nav/registre/tpsidentservice/config/VaultConfig.java
- apps/tps-ident-service/src/main/java/no/nav/registre/tpsidentservice/consumer/TpsfConsumer.java
- apps/tps-ident-service/src/main/java/no/nav/registre/tpsidentservice/consumer/command/GetTpsStatusCommand.java
- apps/tps-ident-service/src/main/java/no/nav/registre/tpsidentservice/consumer/dto/TpsStatus.java
- apps/tps-ident-service/src/main/java/no/nav/registre/tpsidentservice/provider/IdentController.java
- apps/tps-ident-service/src/main/resources/application-dev.yml
- apps/tps-ident-service/src/main/resources/application-prod.yml
- apps/tps-ident-service/src/main/resources/application.yml
- apps/tps-ident-service/src/main/resources/bootstrap-dev.yml
- apps/tps-ident-service/src/main/resources/bootstrap-prod.yml
- apps/tps-ident-service/src/main/resources/logback.xml
- settings.gradle
Tjeneste for å checke om ident ligger i TPS og hvilket test miljø.
> Opprett testnorge-tps-ident-service

- apps/oversikt-frontend/src/main/resources/application.yml
- apps/person-api/config.dev.yaml
- apps/person-api/config.yaml
- apps/person-api/src/main/resources/application-dev.yml
- apps/person-api/src/main/resources/application-prod.yml
- apps/person-api/src/main/resources/application.yml
Jeg får hentet token for `person-api-dev`, men ikke for `person-api` via oversikt-frontend. Ideer til hvorfor?
> Person api i oversikt frontend

- .github/workflows/deploy.person-api.yml
- .github/workflows/deploy.profil-api.dev.yml
- .github/workflows/deploy.profil-api.yml
- apps/profil-api/build.gradle
- apps/profil-api/config.dev.yml
- apps/profil-api/config.yml
- apps/profil-api/src/main/java/no/nav/registre/testnorge/profil/ProfilApiApplicationStarter.java
- apps/profil-api/src/main/resources/application-dev.yml
- apps/profil-api/src/main/resources/application-prod.yml
- apps/tilbakemelding-api/src/main/resources/application.yml
Er ikke så mye som skal til når forarbeidet med tokens er gjort
> Migerer til GCp

- apps/testnorge-arena/arena-core/src/main/java/no/nav/registre/arena/core/service/util/VedtakUtils.java
Fikset nullpointer exception i dato sammenligning.
> Fikset nullpointer exception

- apps/testnorge-arena/arena-core/src/main/java/no/nav/registre/arena/core/service/VedtakshistorikkService.java
Har oppdatert innsendelse av AA115 vedtak i vedtakshistorikken. AA115 stans-vedtak sendes nå inn etter AAP-vedtak.
> Oppdatert innsendelse av aa115 vedtak i vedtakshistorikk

- apps/testnorge-arena/arena-core/src/main/java/no/nav/registre/arena/core/service/util/VedtakUtils.java
Arena forvalterern har oppdatert request format for endre deltakerstatus til å ta inn spesifikk tiltakid i stedet for tiltakskarakteristikk og dato.
> Oppdatert endre deltakerstatus request

- apps/syntrest/README.md
- apps/syntrest/src/main/java/no/nav/registre/syntrest/consumer/SyntAmeldingConsumer.java
- apps/syntrest/src/main/java/no/nav/registre/syntrest/consumer/command/PostArbeidsforholdHistorikkCommand.java
- apps/syntrest/src/main/java/no/nav/registre/syntrest/controllers/SyntController.java
Arbeidsforhold-endepunkt i synt_amelding returnerer nå liste med arbeidsforhold. Har oppdatert syntrest basert på dette.
> Lagt til endepunkt for char-rnn

- apps/testnorge-statisk-data-forvalter/src/main/java/no/nav/registre/sdforvalter/service/IdentService.java
Testnorge-skd legger til personer i TPS. De to appene som bruker denne er orkestratoren og statisk-data-forvalter. I testnorge-skd blir alle personer som legges til i Mini-Norge også lagt til i PDL (orkestrator). Statisk-data-forvalter bruker egne endepunkt i testnorge-skd som ikke fører til at personene blir lagt til i PDL. I endepunktet som sender til tps jobbes det kun med skd-melding-id'er, og jeg tenker at det er like greit å legge til personene i PDL i statisk data forvalter som å begynne å slå opp hvilke fnr de ulike skd-melding-id'ene tilhører i testnorge-skd.
> Personer som opprettes i TPS blir også opprettet i PDL for å få aktørid

- apps/oversikt-frontend/src/main/java/no/nav/registre/testnorge/oversiktfrontend/config/ApplicationConfig.java
- apps/oversikt-frontend/src/main/java/no/nav/registre/testnorge/oversiktfrontend/config/SessionTimeoutCookieFilter.java
- apps/oversikt-frontend/src/main/js/package-lock.json
- apps/oversikt-frontend/src/main/js/package.json
- apps/oversikt-frontend/src/main/js/src/App.tsx
- apps/oversikt-frontend/src/main/js/src/components/Header/Header.tsx
- apps/oversikt-frontend/src/main/js/src/components/SessionTimer/SessionTimer.tsx
- apps/oversikt-frontend/src/main/js/src/components/SessionTimer/index.ts
Dette var et problem som har plaget meg lenge å måtte prøve å finne en løsning på
> Legger til session timer pa oversikt

- .github/workflows/deploy.testnorge-aareg.prepord.yml
- apps/testnorge-aareg/aareg-core/src/main/java/no/nav/registre/aareg/config/SecurityConfig.java
- apps/testnorge-aareg/aareg-core/src/main/java/no/nav/registre/aareg/consumer/ws/AaregBehandleArbeidsforhold.java
- apps/testnorge-aareg/aareg-core/src/test/java/no/nav/registre/aareg/consumer/ws/AaregBehandleArbeidsforholdTest.java
Måtte legge tilbake csrf disable for å fikse forbidden feil, fikset versjon av aareg er deployet. La til miljø henting fra miljoer-service et annet sted hvor det var hardkodet også
> Aareg forbidden fix

- apps/testnorge-arena/arena-core/src/main/java/no/nav/registre/arena/core/consumer/rs/AapSyntConsumer.java
- apps/testnorge-arena/arena-core/src/main/java/no/nav/registre/arena/core/consumer/rs/VedtakshistorikkSyntConsumer.java
- apps/testnorge-arena/arena-core/src/main/java/no/nav/registre/arena/core/consumer/rs/command/HentVedtakshistorikkCommand.java
- apps/testnorge-arena/arena-core/src/main/java/no/nav/registre/arena/core/service/VedtakshistorikkService.java
- apps/testnorge-arena/arena-core/src/test/java/no/nav/registre/arena/core/service/VedtakshistorikkServiceTest.java
Har lagd en egen consumer for synt-vedtakshistorikk som bruker webclient og har bedre feilhåndtering.
> Testnorge arena/vedtakshistorikk consumer

- apps/testnorge-arena/arena-core/src/main/java/no/nav/registre/arena/core/consumer/rs/BrukereArenaForvalterConsumer.java
- apps/testnorge-arena/arena-core/src/main/java/no/nav/registre/arena/core/consumer/rs/command/DeleteArenaBrukerCommand.java
- apps/testnorge-arena/arena-core/src/main/java/no/nav/registre/arena/core/consumer/rs/command/GetArenaBrukereCommand.java
- apps/testnorge-arena/arena-core/src/main/java/no/nav/registre/arena/core/consumer/rs/command/PostArenaBrukerCommand.java
- apps/testnorge-arena/arena-core/src/test/java/no/nav/registre/arena/core/consumer/rs/BrukereArenaForvalterConsumerTest.java
- libs/testnorge-domain/src/main/java/no/nav/registre/testnorge/domain/dto/arena/testnorge/vedtak/NyeBrukereResponse.java
Har oppdatert brukereArenaForvalterConsumer til å ta i bruk webclient i stedet for resttemplate.
> Testnorge arena/oppdatere brukere arena forvalter consumer

- .github/workflows/deploy.miljoer-service.yml
- apps/miljoer-service/src/main/resources/bootstrap-prod.yml
Ser ut som det bare skyldtes manglende bootstrap-prod, men rart det bare plutselig skjedde en dag😅
> Miljoer service deploy fix

- apps/testnorge-arena/arena-core/src/main/java/no/nav/registre/arena/core/service/VedtakshistorikkService.java
- apps/testnorge-arena/arena-core/src/main/java/no/nav/registre/arena/core/service/util/DatoUtils.java
- libs/testnorge-domain/src/main/java/no/nav/registre/testnorge/domain/dto/arena/testnorge/vedtak/NyttVedtak.java
- libs/testnorge-domain/src/main/java/no/nav/registre/testnorge/domain/dto/arena/testnorge/vedtak/NyttVedtakAap.java
- libs/testnorge-domain/src/main/java/no/nav/registre/testnorge/domain/dto/arena/testnorge/vedtak/NyttVedtakTillegg.java
- libs/testnorge-domain/src/main/java/no/nav/registre/testnorge/domain/dto/arena/testnorge/vedtak/NyttVedtakTiltak.java
- libs/testnorge-domain/src/main/java/no/nav/registre/testnorge/domain/dto/arena/testnorge/vedtak/RettighetType.java
Fikk feil når jeg prøvde å sende inn vedtakshistorikk etter at rettighettype ble lagt til. Fjernet det nå for å se om det funker igjen.
> Fjernet rettighettype

- apps/helsepersonell-api/src/main/java/no/nav/registre/testnorge/helsepersonell/consumer/HodejegerenConsumer.java
- apps/helsepersonell-api/src/main/java/no/nav/registre/testnorge/helsepersonell/consumer/command/GetSamhandlerCommand.java
- apps/helsepersonell-api/src/main/java/no/nav/registre/testnorge/helsepersonell/provider/HelsepersonellController.java
- apps/testnorge-hodejegeren/hodejegeren-core/src/main/resources/application-prod.properties
Fungerer fint etter henting fra q2 isteden, da kommer det med en hel liste med helsepersonell istedenfor bare en lege.
> Helsepersonell endringer

- apps/testnorge-arena/src/main/java/no/nav/registre/testnorge/arena/service/util/ArbeidssoekerUtils.java
Har lagt til en liten delay før endring av innsatsbehov etter ønske fra Arena.
> lagt til delay for endring av innsatsbehov

- apps/testnorge-skd/skd-core/src/main/java/no/nav/registre/skd/consumer/PersonConsumer.java
- apps/testnorge-skd/skd-core/src/main/java/no/nav/registre/skd/service/PersonService.java
- apps/testnorge-skd/skd-core/src/main/java/no/nav/registre/skd/service/SyntetiseringService.java
- apps/testnorge-skd/skd-core/src/main/resources/application.properties
- apps/testnorge-skd/skd-core/src/test/resources/application-test.properties
Hvis ident som sendes inn i PDL er fra MiniNorge får den kilde lik "MiniNorge".
> Lagt til kilde for mini norge i innsending pdl

- apps/testnorge-arena/src/main/java/no/nav/registre/testnorge/arena/consumer/rs/RettighetArenaForvalterConsumer.java
Har oppdatert feilhåndtering for post rettighet i testnorge-arena
> Oppdatert feilhaandtering

- apps/orkestratoren/src/main/java/no/nav/registre/orkestratoren/batch/v1/JobController.java
Fikk melding fra Torbjørn at innsending av vedtakshistorikk bør stanses midlertidig mens de tømmer arena.
> Midlertidig stanset batch kjoring arena

- apps/testnorge-arena/src/main/java/no/nav/registre/testnorge/arena/service/VedtakshistorikkService.java
- apps/testnorge-arena/src/main/java/no/nav/registre/testnorge/arena/service/util/DatoUtils.java
- libs/testnorge-domain/src/main/java/no/nav/registre/testnorge/domain/dto/arena/testnorge/vedtak/NyttVedtak.java
- libs/testnorge-domain/src/main/java/no/nav/registre/testnorge/domain/dto/arena/testnorge/vedtak/NyttVedtakAap.java
- libs/testnorge-domain/src/main/java/no/nav/registre/testnorge/domain/dto/arena/testnorge/vedtak/NyttVedtakTillegg.java
- libs/testnorge-domain/src/main/java/no/nav/registre/testnorge/domain/dto/arena/testnorge/vedtak/NyttVedtakTiltak.java
- libs/testnorge-domain/src/main/java/no/nav/registre/testnorge/domain/dto/arena/testnorge/vedtak/RettighetType.java
Har lagt til RettighetType for vedtak i Arena for å lettere skille mellom de ulike vedtakene. Denne PR-en er nesten identisk med en tidligere PR jeg har hatt, men jeg måtte endre det tilbake fordi forrige PR skapte en feil som jeg ikke hadde tid til å fikse der å da. Men feilen skal være fikset nå.
> La til rettighettype

- apps/testnorge-arena/src/main/java/no/nav/registre/testnorge/arena/provider/rs/AapController.java
- apps/testnorge-arena/src/main/java/no/nav/registre/testnorge/arena/service/RettighetAapService.java
- apps/testnorge-arena/src/main/java/no/nav/registre/testnorge/arena/service/RettighetTiltakService.java
- apps/testnorge-arena/src/main/java/no/nav/registre/testnorge/arena/service/VedtakshistorikkService.java
- apps/testnorge-arena/src/main/java/no/nav/registre/testnorge/arena/service/util/ArbeidssoekerUtils.java
- apps/testnorge-arena/src/main/java/no/nav/registre/testnorge/arena/service/util/IdenterUtils.java
Oppdatert metoder for opprettelse av arbeidsøker i Arena.
> Testnorge arena/oppdatere arbeidssoker registrering

- apps/testnorge-arena/src/main/java/no/nav/registre/testnorge/arena/service/BrukereService.java
- apps/testnorge-arena/src/main/java/no/nav/registre/testnorge/arena/service/RettighetAapService.java
- apps/testnorge-arena/src/main/java/no/nav/registre/testnorge/arena/service/TpsForvalterService.java
- apps/testnorge-arena/src/main/java/no/nav/registre/testnorge/arena/service/VedtakshistorikkService.java
- apps/testnorge-arena/src/main/java/no/nav/registre/testnorge/arena/service/util/DatoUtils.java
- apps/testnorge-arena/src/main/java/no/nav/registre/testnorge/arena/service/util/IdenterUtils.java
- apps/testnorge-arena/src/test/java/no/nav/registre/testnorge/arena/consumer/rs/AapSyntConsumerTest.java
- apps/testnorge-arena/src/test/java/no/nav/registre/testnorge/arena/consumer/rs/BrukereArenaForvalterConsumerTest.java
- apps/testnorge-arena/src/test/java/no/nav/registre/testnorge/arena/consumer/rs/RettighetAapBrukereArenaForvalterConsumerTest.java
- apps/testnorge-arena/src/test/java/no/nav/registre/testnorge/arena/consumer/rs/RettighetTilleggBrukereArenaForvalterConsumerTest.java
- apps/testnorge-arena/src/test/java/no/nav/registre/testnorge/arena/consumer/rs/RettighetTiltakBrukereArenaForvalterConsumerTest.java
- apps/testnorge-arena/src/test/java/no/nav/registre/testnorge/arena/provider/rs/AapControllerIntegrationTest.java
- apps/testnorge-arena/src/test/java/no/nav/registre/testnorge/arena/provider/rs/IdentControllerTest.java
- apps/testnorge-arena/src/test/java/no/nav/registre/testnorge/arena/service/BrukereServiceTest.java
- apps/testnorge-arena/src/test/java/no/nav/registre/testnorge/arena/service/IdentServiceTest.java
- apps/testnorge-arena/src/test/java/no/nav/registre/testnorge/arena/service/RettighetAapServiceTest.java
- apps/testnorge-arena/src/test/java/no/nav/registre/testnorge/arena/service/VedtakshistorikkServiceTest.java
Har oppdatert sjekk om ident har bosatt personstatus i TPS eller ikke. Ny metode sjekker nå også om `fom_dato` for personsatus er før  en innsendt dato limit (eks. dato for tidligste AAP vedtak).
Har også ryddet litt i koden og i tester ;)
> Testnorge arena/oppdater personstatus sjekk

- apps/syntrest/src/main/java/no/nav/registre/syntrest/consumer/SyntAmeldingConsumer.java
- apps/syntrest/src/main/java/no/nav/registre/syntrest/consumer/command/PostArbeidsforholdMedTypeCommand.java
- apps/syntrest/src/main/java/no/nav/registre/syntrest/controllers/SyntController.java
- apps/syntrest/src/main/java/no/nav/registre/syntrest/domain/amelding/ArbeidsforholdPeriode.java
- apps/syntrest/src/main/java/no/nav/registre/syntrest/utils/InputValidator.java
- apps/syntrest/src/main/resources/application-dev.properties
- apps/syntrest/src/main/resources/application.properties
Har lagt til støtte i syntrest for nytt endepunkt i synt-amelding.
> Lagt til ekstra endepunkt for start arbeidsforhold amelding

- apps/testnorge-arena/src/main/java/no/nav/registre/testnorge/arena/consumer/rs/command/tpsf/GetPersonstatusOgAdresseCommand.java
- apps/testnorge-arena/src/main/java/no/nav/registre/testnorge/arena/service/IdentService.java
Ble litt mange unødvendige kall til TPSF så jeg oppdaterte filtreringsmetode. Fjernet også NavCallId og NavConsumerId fra tpsf command da de ikke trengs.
> Oppdatert filtering av identer med bosatt status

- .github/workflows/deploy.syntrest-proxy.yml
- apps/generer-synt-amelding-service/config.yml
- apps/generer-synt-amelding-service/src/main/java/no/nav/registre/testnorge/generersyntameldingservice/config/credentials/SyntrestProperties.java
- apps/generer-synt-amelding-service/src/main/java/no/nav/registre/testnorge/generersyntameldingservice/consumer/SyntrestConsumer.java
- apps/generer-synt-amelding-service/src/main/java/no/nav/registre/testnorge/generersyntameldingservice/consumer/command/PostArbeidsforholdCommand.java
- apps/generer-synt-amelding-service/src/main/java/no/nav/registre/testnorge/generersyntameldingservice/consumer/command/PostHistorikkCommand.java
- apps/generer-synt-amelding-service/src/main/resources/application.yml
- proxies/syntrest-proxy/Dockerfile
- proxies/syntrest-proxy/build.gradle
- proxies/syntrest-proxy/config.yml
- proxies/syntrest-proxy/src/main/java/no/nav/registre/testnorge/syntrestproxy/SyntrestProxyApplicationStarter.java
- proxies/syntrest-proxy/src/main/java/no/nav/registre/testnorge/syntrestproxy/config/ApplicationConfig.java
- proxies/syntrest-proxy/src/main/java/no/nav/registre/testnorge/syntrestproxy/config/DevConfig.java
- proxies/syntrest-proxy/src/main/java/no/nav/registre/testnorge/syntrestproxy/config/SecurityConfig.java
- proxies/syntrest-proxy/src/main/resources/application-dev.yml
- proxies/syntrest-proxy/src/main/resources/application.yml
- proxies/syntrest-proxy/src/main/resources/bootstrap-dev.yml
- proxies/syntrest-proxy/src/main/resources/bootstrap-prod.yml
- proxies/syntrest-proxy/src/main/resources/logback-spring.xml
- settings.gradle
Lagd en syntrest proxy som generer-synt-amelding-service tar i bruk.
> Syntrest proxy

- .github/workflows/deploy.testnorge-token-provider.yml
Fjernet deploy til t6 for testnorge-token-provider
> Oppdatert token provider workflow

- apps/ident-pool/README.md
- apps/orkestratoren/README.md
- apps/testnorge-hodejegeren/README.md
> Dokumentasjon

- apps/orkestratoren/src/main/java/no/nav/registre/orkestratoren/batch/v1/JobController.java
Arena-batch kjøring ble midlertidig stanset pga G-justeringer i Q2. Har denne PR-en klar til å merges når batch kjøringen kan starte igjen.
> Restart arena batch kjøring

- apps/joark-dokument-service/src/main/java/no/nav/testnav/joarkdokumentservice/consumer/SafConsumer.java
- apps/joark-dokument-service/src/main/java/no/nav/testnav/joarkdokumentservice/consumer/command/GetDokumentCommand.java
- apps/joark-dokument-service/src/main/java/no/nav/testnav/joarkdokumentservice/controller/v1/DokumentController.java
- apps/joark-dokument-service/src/main/java/no/nav/testnav/joarkdokumentservice/controller/v1/dto/DokumentInfoDTO.java
- apps/joark-dokument-service/src/main/java/no/nav/testnav/joarkdokumentservice/controller/v2/JournalpostController.java
- apps/joark-dokument-service/src/main/java/no/nav/testnav/joarkdokumentservice/controller/v2/dto/DokumentInfoDTO.java
- apps/joark-dokument-service/src/main/java/no/nav/testnav/joarkdokumentservice/controller/v2/dto/JournalpostDTO.java
- apps/joark-dokument-service/src/main/java/no/nav/testnav/joarkdokumentservice/domain/DokumentInfo.java
- apps/joark-dokument-service/src/main/java/no/nav/testnav/joarkdokumentservice/domain/DokumentType.java
- apps/joark-dokument-service/src/main/java/no/nav/testnav/joarkdokumentservice/domain/Journalpost.java
- apps/joark-dokument-service/src/main/java/no/nav/testnav/joarkdokumentservice/service/DokumentService.java
- apps/joark-dokument-service/src/main/resources/schema/safquery-journalpost.graphql
- proxies/saf-proxy/src/main/java/no.nav.testnav.safproxy/SafProxyApplicationStarter.java
- proxies/saf-proxy/src/main/java/no.nav.testnav.safproxy/config/AddRequestHeaderGatewayFilterFactory.java
Dette er måten vi burde versjons kontrolere. API. Nå har jeg tid til å migere begge appene uten at det må skje samtidig.
> Legg til v2 dokument

- apps/testnorge-arena/src/main/java/no/nav/registre/testnorge/arena/consumer/rs/PdlPersonConsumer.java
- apps/testnorge-arena/src/main/java/no/nav/registre/testnorge/arena/domain/FilLaster.java
`ClassPathResource.getInputStream()` funkert ikke i deployet versjon. Har lagd en egen FilLaster som forhåpentligvis løser problemet.
> Laget egen fillaster

- apps/person-service/README.md
Så feil i readme til person service når swagger-linken sendte meg til person-api i stedet.
> Oppdatert readme person service

- .github/workflows/deploy.profil-api.yml
- apps/profil-api/build.gradle
- apps/profil-api/gradlew
- apps/profil-api/gradlew.bat
- apps/profil-api/settings.gradle
- apps/profil-api/src/main/java/no/nav/registre/testnorge/profil/consumer/AzureAdProfileConsumer.java
- apps/profil-api/src/main/java/no/nav/registre/testnorge/profil/consumer/command/GetProfileImageCommand.java
- apps/profil-api/src/main/java/no/nav/registre/testnorge/profil/provider/ProfilController.java
- build.gradle
- settings.gradle
Fikset feilen på Dolly kanalen hvor Profil Api kastet IllegalStateException som stoppet bestilling når bruker manglet bilde og fikk Endret til composit build samtidig
> Profil api composit

- apps/dolly-frontend/src/main/js/src/ducks/bruker/index.js
- apps/dolly-frontend/src/main/js/src/pages/gruppe/PersonListe/PersonListe.js
- apps/dolly-frontend/src/main/js/src/service/services/tpsf/TpsfService.js
- libs/reactive-core/src/main/java/no/nav/testnav/libs/reactivecore/filter/LogServerHttpResponseDecorator.java
> FIks for unexpected json format

- apps/dolly-frontend/src/main/js/src/ducks/bruker/index.js
Fjernet midlertidig fiks for profilbilde.
> Dolly - Endret profilbilde tilbake

- apps/dolly-frontend/src/main/js/src/components/fagsystem/inntektstub/form/partials/inntektstubTypes.ts
- apps/dolly-frontend/src/main/js/src/components/inntektStub/validerInntekt/Inntekt.js
Bitteliten fix - har gjort alt jeg kan for å prøve å få den til å feile, men ser ok ut (bank i bordet) 😝
> Valider alle felter

- proxies/pdl-proxy/src/main/java/no/nav/testnav/proxies/pdlproxy/PdlProxyApplicationStarter.java
Snakket med Odin og vi skal aldri bruke pdl-testdata-feature med mindre noe er avtalt på forhånd. Fikset dette for pdl-proxy.
> Byttet til pdl-testdata.

- .github/workflows/deploy.testnorge-skd.yml
- apps/testnorge-skd/skd-core/src/main/java/no/nav/registre/skd/service/PersonService.java
- apps/testnorge-skd/skd-core/src/main/java/no/nav/registre/skd/utils/DatoFraIdentUtils.java
Lagt til fødselsdato for identer som registreres i PDL via testnorge-skd
> Testnorge- SKD- Lagt tilfoedselsdato pdl

- apps/dolly-frontend/src/main/js/src/components/fagsystem/aareg/form/validation.js
Satt yrke i arbeidsforhold til `requiredString`
> Satt yrke til required

- apps/dolly-frontend/src/main/js/src/components/miljoVelger/MiljoVelger.js
Lagt på midlertidig disabling av Q2 med tilhørende hjelpetekst for organisasjoner
> Midlertidig q2 disabling i organisasjoner

- .github/workflows/deploy.person-service.yml
- apps/person-service/config.yml
- apps/person-service/src/main/java/no/nav/testnav/apps/personservice/consumer/PdlTestdataConsumer.java
- apps/person-service/src/main/java/no/nav/testnav/apps/personservice/consumer/command/OpprettFoedselCommand.java
- apps/person-service/src/main/java/no/nav/testnav/apps/personservice/consumer/command/OpprettPersonCommand.java
- apps/person-service/src/main/java/no/nav/testnav/apps/personservice/consumer/command/PostAdresseCommand.java
- apps/person-service/src/main/java/no/nav/testnav/apps/personservice/consumer/command/PostNavnCommand.java
- apps/person-service/src/main/java/no/nav/testnav/apps/personservice/consumer/command/PostTagsCommand.java
- apps/person-service/src/main/java/no/nav/testnav/apps/personservice/consumer/exception/PdlCreatePersonException.java
- apps/person-service/src/main/java/no/nav/testnav/apps/personservice/controller/PersonController.java
- apps/person-service/src/main/java/no/nav/testnav/apps/personservice/service/PersonService.java
Jeg har lagt til det gamle endepunktet for createPerson som fantes i person-api tidligere.
> Lagt til create person endepunkt

- apps/dolly-frontend/src/main/js/src/components/layout/blankHeader/BlankHeader.tsx
Fjernet navlink for nav og dolly ikon i header på innloggingsside da den ikke funket.
> Dolly frontend/logg inn home redirect

- .github/workflows/deploy.person-service.yml
- apps/testnorge-skd/src/main/java/no/nav/registre/skd/consumer/SyntTpsConsumer.java
Webclient klarte ikke å hente ut over 200 endringsmeldinger, fikk minne problem. Har økt maxinmemorysize for å se om det løser problemet. La også workflow dispatch for person-service. Hadde feil hvor token var ugyldig for person-service, men ser at gammel versjon er blitt deployet.
> Testnorge skd/debugge

- apps/person-service/src/main/java/no/nav/testnav/apps/personservice/consumer/command/OpprettFoedselCommand.java
- apps/person-service/src/main/java/no/nav/testnav/apps/personservice/consumer/command/OpprettPersonCommand.java
- apps/person-service/src/main/java/no/nav/testnav/apps/personservice/consumer/command/PostAdresseCommand.java
- apps/person-service/src/main/java/no/nav/testnav/apps/personservice/consumer/command/PostNavnCommand.java
- apps/person-service/src/main/java/no/nav/testnav/apps/personservice/consumer/command/PostTagsCommand.java
Fikk feilmelding `block()/blockFirst()/blockLast() are blocking, which is not supported in thread`
Fjernet dermed block fra commands.
> Person service - Fjernet block fra pdltestdata commands

- apps/dolly-frontend/src/main/js/src/components/bestillingsveileder/stegVelger/steg/steg1/paneler/Personinformasjon.tsx
- apps/dolly-frontend/src/main/js/src/components/layout/header/Header.tsx
- apps/dolly-frontend/src/main/js/src/pages/gruppe/PersonListe/PersonListe.js
- apps/dolly-frontend/src/main/resources/application-dev.yml
- Byttet fra adeo.no til intern.nav.no for dolly backend siden de er på plass nå og adeo har sertifikat-problemer
- Simplifisert noe kode i PersonListe.js og fikset en bug ved manglende oppdatering av liste dersom man endrer ident
> Lagt til mulighet for å endre kjønn i legg til/endre + mindre endringer

- .github/workflows/deploy.oversikt-frontend.yml
- apps/oversikt-frontend/src/main/js/package-lock.json
- apps/oversikt-frontend/src/main/js/package.json
- apps/oversikt-frontend/src/main/js/src/components/LogoutButton/LogoutButton.less
- apps/oversikt-frontend/src/main/js/src/components/LogoutButton/LogoutButton.tsx
- apps/oversikt-frontend/src/main/js/src/components/LogoutButton/icons/logout.svg
- apps/oversikt-frontend/src/main/js/src/components/LogoutButton/index.ts
- apps/oversikt-frontend/src/main/js/src/pages/Page/Page.tsx
- apps/oversikt-frontend/src/main/js/webpack.dev.js
Har lagt til logg ut knapp for oversikt frontend. BankId logg ut funker fremdeles ikke 100%, da du blir logget ut på oversikt frontend, men ikke helt ordentlig ut fra bankid. Jeg jobber med å finne ut av det.
> Oversikt frontend/logg ut knapp

- apps/dolly-frontend/src/main/js/src/components/bestillingsveileder/stegVelger/steg/steg1/paneler/Personinformasjon.tsx
Fikset feil i datastruktur når man huker av for kjønn i bestilling.
> Bugfix - sette kjønn i bestilling

- apps/dolly-frontend/src/main/js/src/components/bestillingsveileder/stegVelger/steg/steg1/paneler/Personinformasjon.tsx
- apps/dolly-frontend/src/main/js/src/components/fagsystem/tpsf/form/personinformasjon/Personinformasjon.js
Tidligere førte identtype valget at man måtte velge alder, endret denne til å sette født før og født etter til fødselsdato på gjeldende ident uten muligheten til å endre
> Alder blir satt automatisk når identtype er valgt under legg til/endre

- apps/dolly-frontend/src/main/js/src/components/ui/appError/AppError.js
Lagt til info om å prøve å slette cache når man får error-side.
> Dolly frontend/oppdatere feilmelding AppError

- apps/dolly-frontend/src/main/java/no/nav/dolly/web/consumers/TilbakemeldingConsumer.java
- apps/dolly-frontend/src/main/java/no/nav/dolly/web/provider/web/LogController.java
- apps/dolly-frontend/src/main/js/src/components/fagsystem/aareg/form/Form.js
- apps/dolly-frontend/src/main/js/src/components/fagsystem/aareg/form/partials/arbeidsavtaleForm.js
- apps/dolly-frontend/src/main/js/src/components/fagsystem/tpsf/form/adresser/partials/midlertidigAdresse/Gateadresse.tsx
- apps/dolly-frontend/src/main/js/src/service/SelectOptionsOppslag.js
Fikset noen code smells fra sonarcloud.
> Dolly frontend/sonarcloud fixes

- apps/dolly-frontend/src/main/js/src/components/bestilling/sammendrag/kriterier/BestillingKriterieMapper.js
- apps/dolly-frontend/src/main/js/src/components/bestillingsveileder/stegVelger/steg/steg1/paneler/Adresse.js
- apps/dolly-frontend/src/main/js/src/components/bestillingsveileder/stegVelger/steg/steg2/Steg2.js
- apps/dolly-frontend/src/main/js/src/components/fagsystem/pdlf/form/Form.js
- apps/dolly-frontend/src/main/js/src/components/fagsystem/pdlf/form/initialValues.ts
- apps/dolly-frontend/src/main/js/src/components/fagsystem/pdlf/form/partials/bostedsadresse/UtenlandskAdresse.tsx
- apps/dolly-frontend/src/main/js/src/components/fagsystem/pdlf/form/validation.js
- apps/dolly-frontend/src/main/js/src/components/fagsystem/pdlf/visning/Visning.js
- apps/dolly-frontend/src/main/js/src/components/fagsystem/pdlf/visning/partials/PdlBoadresse.js
- apps/dolly-frontend/src/main/js/src/components/fagsystem/pdlf/visning/partials/UtenlandskBoadresse.tsx
- apps/dolly-frontend/src/main/js/src/components/miljoVelger/MiljoeInfo/MiljoeInfo.js
- apps/dolly-frontend/src/main/js/src/components/ui/form/formUtils.js
- apps/dolly-frontend/src/main/js/src/pages/gruppe/PersonVisning/PersonMiljoeinfo/PdlDataVisning.tsx
"Mellomløsning" for å få ut utenlandsk boadresse før vi skriver om alle adresser til å få PDL som master.
> Dolly frontend pdl utenlandskadresse

- .github/workflows/deploy.testnorge-inntekt.yml
- apps/testnorge-statisk-data-forvalter/src/test/java/no/nav/registre/sdforvalter/provider/rs/OrkestreringsControllerAaregIntegrationTest.java
- apps/testnorge-statisk-data-forvalter/src/test/java/no/nav/registre/sdforvalter/provider/rs/OrkestreringsControllerIdentIntegrationTest.java
- apps/testnorge-statisk-data-forvalter/src/test/java/no/nav/registre/sdforvalter/provider/rs/OrkestreringsControllerKrrIntegrationTest.java
Oppdatert deployt-workflow for testnorge-inntekt og disabled tester i testnorge-statisk-data-forvalter som feilet.
> Build fixes

- apps/dolly-frontend/src/main/java/no/nav/dolly/web/config/SecurityConfig.java
- apps/dolly-frontend/src/main/js/src/components/layout/header/Header.tsx
- apps/dolly-frontend/src/main/js/src/components/ui/appError/AppError.js
- apps/dolly-frontend/src/main/js/src/components/utlogging/Utlogging.tsx
- apps/dolly-frontend/src/main/js/webpack.dev.js
- apps/dolly-frontend/src/main/resources/application-prod.yml
Har endret logout fra POST til GET-request, endret litt på app error melding og doblet tiden man er logget inn (fra 30 min til 60 min)
> Dolly frontend/oppdatert logout og session time

- apps/dolly-frontend/src/main/js/src/pages/loginPage/LoginModal.tsx
- apps/dolly-frontend/src/main/js/src/pages/loginPage/LoginPage.less
> Lagt til hjelpetekst for bankid innlogging

- .github/workflows/app.dolly-backend.yml
- apps/dolly-backend/src/main/java/no/nav/dolly/config/OpenApiConfig.java
- apps/dolly-backend/src/main/resources/application.yaml
Testet for dolly-backend-dev og swagger funker der nå.
> Dolly-backend/swagger-fiks

- .github/workflows/app.person-search-service.yml
- apps/person-search-service/README.md
- apps/person-search-service/config.yml
- apps/person-search-service/src/main/java/no/nav/registre/testnorge/personsearchservice/adapter/PersonSearchAdapter.java
- apps/person-search-service/src/main/java/no/nav/registre/testnorge/personsearchservice/config/DevConfig.java
- apps/person-search-service/src/main/java/no/nav/registre/testnorge/personsearchservice/controller/dto/PersonDTO.java
- apps/person-search-service/src/main/java/no/nav/registre/testnorge/personsearchservice/controller/search/IdentSearch.java
- apps/person-search-service/src/main/java/no/nav/registre/testnorge/personsearchservice/controller/search/PersonSearch.java
- apps/person-search-service/src/main/java/no/nav/registre/testnorge/personsearchservice/domain/Person.java
- apps/person-search-service/src/main/resources/application-dev.yml
- apps/person-search-service/src/main/resources/application-prod.yml
- apps/person-search-service/src/main/resources/application.yml
- apps/person-search-service/src/main/resources/bootstrap.yml
- apps/person-search-service/src/test/resources/application-test.yml
- apps/person-search-service/src/test/resources/bootstrap.yml
Har lagt til søk på fnr/dnr og gjort det mulig å legge til en "excludeTag" som identene ikke skal ha (altså vi kan søke etter testnorge identer som ikke er i Dolly).
Har også gjort at alle tags blir returnert i stedet for kun den første i listen og fikset lokal kjøring.
> Person search service/soeke paa fnr

- apps/dolly-frontend/src/main/js/src/components/ui/form/inputs/textInput/TextInput.tsx
- apps/dolly-frontend/src/main/js/src/pages/testnorgePage/TestnorgePage.tsx
- apps/dolly-frontend/src/main/js/src/pages/testnorgePage/search/SearchOptions.tsx
- apps/dolly-frontend/src/main/js/src/service/services/personsearch/types.ts
Har oppdatert testnorge søk sånn at man kan søke på fnr/dnr. Har også gjort at initial søke verdier inkluderer alder 18-70.
> Dolly frontend/oppdatere testnorge soek

- apps/dolly-frontend/src/main/js/src/components/fagsystem/pdl/visning/partials/PdlBarn.tsx
- apps/dolly-frontend/src/main/js/src/components/ui/form/inputs/textInput/TextInput.tsx
- apps/dolly-frontend/src/main/js/src/pages/testnorgePage/TestnorgePage.tsx
- apps/dolly-frontend/src/main/js/src/pages/testnorgePage/search/SearchOptions.tsx
Lagt til søkemuligheter for testnorge søk (har barn, har dødfødt barn, har falsk identitet, har utenlands identitet)
> Dolly frontend/ekstra soekemuligheter testnorge

- .github/workflows/app.person-search-service.yml
- apps/person-search-service/src/main/java/no/nav/registre/testnorge/personsearchservice/adapter/PersonSearchAdapter.java
- apps/person-search-service/src/main/java/no/nav/registre/testnorge/personsearchservice/controller/search/UtflyttingFraNorgeSearch.java
Fikset søk på ident sånn at søket ikke prøver å matche tom string.
> Person search service/ident søk fiks

- apps/dolly-frontend/src/main/js/src/ducks/gruppe/index.js
- apps/dolly-frontend/src/main/js/src/pages/gruppe/EksporterExcel/EksporterExcel.js
- apps/dolly-frontend/src/main/js/src/pages/gruppe/Gruppe.js
- apps/dolly-frontend/src/main/js/src/pages/gruppe/GruppeConnector.js
- apps/dolly-frontend/src/main/js/src/pages/gruppe/GruppeHeader/GruppeHeader.js
- apps/dolly-frontend/src/main/js/src/service/services/Request.ts
- apps/dolly-frontend/src/main/js/src/service/services/dolly/DollyEndpoints.js
- apps/dolly-frontend/src/main/js/src/service/services/dolly/DollyService.js
Fikser slik at vi får feilmelding + knapp slutter å loade når vi får feil fra api.
> Omskrivning av excel-eksport

- .github/workflows/app.person-search-service.yml
- apps/person-search-service/src/main/java/no/nav/registre/testnorge/personsearchservice/adapter/PersonSearchAdapter.java
- apps/person-search-service/src/main/java/no/nav/registre/testnorge/personsearchservice/adapter/model/DoedsfallModel.java
- apps/person-search-service/src/main/java/no/nav/registre/testnorge/personsearchservice/adapter/model/HentPersonModel.java
- apps/person-search-service/src/main/java/no/nav/registre/testnorge/personsearchservice/adapter/model/PersonstatusModel.java
- apps/person-search-service/src/main/java/no/nav/registre/testnorge/personsearchservice/controller/search/PersonSearch.java
- apps/person-search-service/src/main/java/no/nav/registre/testnorge/personsearchservice/controller/search/PersonstatusSearch.java
Har lagt til søk på "Kun levende" personer, "kun døde" personer, på personstatus og gjort det mulig å sende med random seed for tilfeldig resultat.
> Person search service/nye soek

- apps/dolly-frontend/src/main/js/src/pages/testnorgePage/TestnorgePage.tsx
- apps/dolly-frontend/src/main/js/src/pages/testnorgePage/utils.ts
Har endret testnorge søk sånn at man sender med et random seed for at resultatet er shuffled
> Testnorge import - Soek med random seed

- apps/dolly-frontend/src/main/js/src/components/bestillingsveileder/stegVelger/steg/steg1/paneler/Personinformasjon.tsx
- apps/dolly-frontend/src/main/js/src/components/fagsystem/pdlf/visning/partials/Innvandring.tsx
- apps/dolly-frontend/src/main/js/src/components/fagsystem/pdlf/visning/partials/PdlNasjonalitet.js
- apps/dolly-frontend/src/main/js/src/components/fagsystem/pdlf/visning/partials/Utvandring.tsx
- apps/dolly-frontend/src/main/js/src/components/fagsystem/tpsf/visning/Visning.js
- apps/dolly-frontend/src/main/js/src/components/fagsystem/tpsf/visning/partials/Nasjonalitet.js
- apps/dolly-frontend/src/main/js/src/pages/gruppe/PersonVisning/PersonMiljoeinfo/PdlDataTyper.tsx
Har splittet opp nasjonalitet slik at vi kan vise elementene uavhengig av hverandre utifra hva vi får inn av data.
> Fix visning nasjonalitet

- apps/mn-organisasjon-api/config.yml
- apps/mn-synt-arbeidsforhold-service/config.yml
- apps/testnorge-arena/nais.yaml
- apps/testnorge-bisys/config.yml
- apps/testnorge-inntekt/nais.yaml
- apps/testnorge-nav-endringsmeldinger/nais.yaml
- apps/testnorge-sigrun/nais.yaml
- apps/testnorge-skd/nais.yaml
- apps/testnorge-token-provider/nais.yaml
- apps/tps-ident-service/config.yml
- apps/tps-identer-vedlikehold/nais.yml
Det var noen apper som ikke er tilknyttet Dolly som fikk økt replicas. Satt dem tilbake til 1.
> Feature/minske replicas for apper ikke tilknyttet Dolly

- apps/dolly-frontend/src/main/js/src/Routes.js
- apps/dolly-frontend/src/main/js/src/components/bestillingsveileder/Bestillingsveileder.js
- apps/dolly-frontend/src/main/js/src/components/bestillingsveileder/BestillingsveilederConnector.js
- apps/dolly-frontend/src/main/js/src/components/bestillingsveileder/stegVelger/StegVelger.js
- apps/dolly-frontend/src/main/js/src/components/bestillingsveileder/stegVelger/steg/steg3/Steg3.js
- apps/dolly-frontend/src/main/js/src/components/miljoVelger/MiljoVelger.js
- apps/dolly-frontend/src/main/js/src/components/miljoVelger/MiljoeInfo/MiljoeInfo.js
- apps/dolly-frontend/src/main/js/src/pages/gruppe/BestillingListe/BestillingListe.js
- apps/dolly-frontend/src/main/js/src/pages/gruppe/Gruppe.js
- apps/dolly-frontend/src/main/js/src/pages/gruppe/GruppeConnector.js
- apps/dolly-frontend/src/main/js/src/pages/gruppe/PersonListe/PersonListe.js
- apps/dolly-frontend/src/main/js/src/pages/searchPage/SearchPage.tsx
- apps/dolly-frontend/src/main/js/src/pages/searchPage/SearchPageConnector.js
- apps/dolly-frontend/src/main/js/src/pages/searchPage/index.ts
Lagt til begrensinger for bankid brukere sånn at de ikke kun kan importere testnorge identer
> Dolly frontend/bankid begrensing

- apps/dolly-frontend/src/main/js/src/app/App.js
- apps/dolly-frontend/src/main/js/src/pages/loginPage/LoginModal.tsx
Forslag for hvordan vi kan logge ut når det skjer en critical error, i stedet for å vise error side.
> Dolly frontend/logout ved critical error

- .github/workflows/app.person-search-service.yml
- apps/person-search-service/build.gradle
- apps/person-search-service/settings.gradle
- apps/person-search-service/src/main/java/no/nav/registre/testnorge/personsearchservice/config/OpenApiConfig.java
- apps/person-search-service/src/main/resources/application.yml
> Person search service/bankid stoette

- apps/dolly-frontend/src/main/js/src/components/SearchContainer/SearchContainer.tsx
- apps/dolly-frontend/src/main/js/src/components/ui/form/inputs/textInput/TextInput.tsx
- apps/dolly-frontend/src/main/js/src/pages/soekMiniNorge/search/Options.tsx
- apps/dolly-frontend/src/main/js/src/pages/soekMiniNorge/search/Search.tsx
- apps/dolly-frontend/src/main/js/src/pages/soekMiniNorge/search/SearchOptions.tsx
- apps/dolly-frontend/src/main/js/src/pages/testnorgePage/search/SearchOptions.tsx
- apps/dolly-frontend/src/main/js/src/pages/testnorgePage/search/options/IdentSearch.tsx
- apps/dolly-frontend/src/main/js/src/pages/testnorgePage/search/options/Options.tsx
- apps/dolly-frontend/src/main/js/src/pages/testnorgePage/search/options/OptionsPanel.less
- apps/dolly-frontend/src/main/js/src/pages/testnorgePage/search/options/OptionsPanel.tsx
- apps/dolly-frontend/src/main/js/src/pages/testnorgePage/search/options/OptionsSection.tsx
- apps/dolly-frontend/src/main/js/src/pages/testnorgePage/utils.ts
Har oppdatert søk i Mini Norge og Testnorge basert for Betsy sit design :)
> Dolly frontend/oppdatert søk design

- apps/dolly-frontend/src/main/js/src/components/bestilling/detaljer/BestillingDetaljer.js
- apps/dolly-frontend/src/main/js/src/components/bestilling/gjenopprett/GjenopprettBestilling.js
- apps/dolly-frontend/src/main/js/src/components/bestilling/gjenopprett/GjenopprettGruppe.tsx
- apps/dolly-frontend/src/main/js/src/components/bestilling/gjenopprett/GjenopprettGruppeConnector.js
- apps/dolly-frontend/src/main/js/src/components/bestilling/gjenopprett/GjenopprettModal.tsx
- apps/dolly-frontend/src/main/js/src/pages/gruppe/BestillingListe/BestillingListe.js
- apps/dolly-frontend/src/main/js/src/pages/organisasjoner/OrganisasjonBestilling.tsx
- apps/dolly-frontend/src/main/js/src/pages/organisasjoner/Organisasjoner.tsx
- apps/dolly-frontend/src/main/js/src/pages/organisasjoner/OrganisasjonerConnector.ts
Hadde glemt å begrense miljø valg for gjenopprett med bankid bruker.
> Dolly -frontend - Bankid begrensning miljoe for gjenopprett

- docs/applications/dolly/brukerveiledning.md
- docs/applications/dolly/testnorge.md
Lagt til demo-videoer og oppdatert litt gammel info i brukerveiledning.
> Dok/legge til demo videoer Dolly

- apps/dolly-frontend/README.md
- apps/dolly-frontend/src/main/js/src/Routes.js
- apps/dolly-frontend/src/main/js/src/components/bestilling/sammendrag/kriterier/BestillingKriterieMapper.js
- apps/dolly-frontend/src/main/js/src/components/bestillingsveileder/stegVelger/steg/steg3/IdentVelger.tsx
- apps/dolly-frontend/src/main/js/src/components/fagsystem/aareg/form/partials/ameldingForm.tsx
- apps/dolly-frontend/src/main/js/src/components/fagsystem/aareg/form/partials/arbeidsforholdToggle.tsx
- apps/dolly-frontend/src/main/js/src/components/fagsystem/brregstub/form/partials/egneOrganisasjoner.tsx
- apps/dolly-frontend/src/main/js/src/components/layout/header/Header.tsx
- apps/dolly-frontend/src/main/js/src/components/ui/button/Tags/TagsButton.tsx
- apps/dolly-frontend/src/main/js/src/components/varslinger/VarslingerTekster.tsx
- apps/dolly-frontend/src/main/js/src/pages/gruppeOversikt/GruppeOversikt.js
- apps/dolly-frontend/src/main/js/src/pages/gruppeOversikt/ImporterGrupper.tsx
- apps/dolly-frontend/src/main/js/src/pages/gruppeOversikt/Liste.js
- apps/dolly-frontend/src/main/js/src/pages/loginPage/LoginModal.tsx
- apps/dolly-frontend/src/main/js/src/pages/minSide/GruppeImport.tsx
- apps/dolly-frontend/src/main/js/src/pages/minSide/SlettBruker.tsx
- apps/dolly-frontend/src/main/js/src/pages/organisasjoner/Organisasjoner.tsx
- apps/dolly-frontend/src/main/js/src/pages/organisasjoner/TomOrgliste.tsx
- docs/applications/dolly/brukerveiledning.md
- docs/applications/dolly/index.md
- docs/applications/dolly/retningslinjer.md
Kan merges når Anders har publisert info om overgangen fra syntetiske testdata til syntetiske data.
> Skrevet om test-relaterte ord i tekster

- apps/dolly-frontend/src/main/js/src/components/fagsystem/pdl/visning/partials/PdlPersonInfo.js
- apps/dolly-frontend/src/main/js/src/pages/gruppe/PersonVisning/PersonMiljoeinfo/PdlDataTyper.tsx
Feil skap av forskjell mellom data fra PDL og PdlForvalter. PDL bruker `folkeregisterpersonstatus,` men PdlForvalter bruker `folkeregisterPersonstatus`. Må ta en prat sammen sånn at vi kan fikse dette ;)
> Manuell fiks personstatus

- apps/dolly-backend/src/main/java/no/nav/dolly/bestilling/aareg/AaregClient.java
- apps/dolly-backend/src/main/java/no/nav/dolly/bestilling/aktoeridsyncservice/AktoerIdSyncClient.java
- apps/dolly-backend/src/main/java/no/nav/dolly/bestilling/pdldata/PdlDataClient.java
- apps/dolly-backend/src/main/java/no/nav/dolly/bestilling/pdlforvalter/PdlForvalterClient.java
- apps/dolly-backend/src/main/java/no/nav/dolly/bestilling/tagshendelseslager/command/HendelseslagerPublishCommand.java
- apps/dolly-backend/src/main/java/no/nav/dolly/bestilling/tpsbackporting/TpsBackportingClient.java
- apps/dolly-backend/src/main/java/no/nav/dolly/bestilling/tpsmessagingservice/TpsMessagingClient.java
- apps/dolly-backend/src/main/java/no/nav/dolly/domain/jpa/Testgruppe.java
- apps/dolly-backend/src/main/java/no/nav/dolly/domain/jpa/Testident.java
- apps/dolly-backend/src/main/java/no/nav/dolly/mapper/strategy/PdlPersonStrategyMapper.java
> Fikset Internal Server Error og endret litt på Orderrekkefølge

- .github/workflows/app.person-search-service.yml
- apps/dolly-frontend/src/main/js/src/pages/testnorgePage/search/options/Relasjoner.tsx
- apps/person-search-service/src/main/java/no/nav/registre/testnorge/personsearchservice/adapter/utils/IdentifikasjonUtils.java
- apps/person-search-service/src/main/java/no/nav/registre/testnorge/personsearchservice/adapter/utils/NasjonalitetUtils.java
- apps/person-search-service/src/main/java/no/nav/registre/testnorge/personsearchservice/adapter/utils/QueryUtils.java
- apps/person-search-service/src/main/java/no/nav/registre/testnorge/personsearchservice/adapter/utils/RelasjonerUtils.java
- apps/person-search-service/src/main/java/no/nav/registre/testnorge/personsearchservice/adapter/utils/StatusUtils.java
Lagt til at søk filterer ut historiske verdier. La også til flere sivilstand valg i Dolly.
> Person search service/historisk filter

- .github/workflows/app.person-search-service.yml
- apps/dolly-frontend/src/main/js/src/pages/testnorgePage/search/SearchOptions.tsx
- apps/dolly-frontend/src/main/js/src/pages/testnorgePage/search/options/Identifikasjon.tsx
- apps/dolly-frontend/src/main/js/src/pages/testnorgePage/search/options/OptionsPanel.less
- apps/dolly-frontend/src/main/js/src/pages/testnorgePage/search/options/RadioGroupOptions.tsx
- apps/dolly-frontend/src/main/js/src/pages/testnorgePage/search/options/Relasjoner.tsx
- apps/dolly-frontend/src/main/js/src/pages/testnorgePage/utils.ts
- apps/dolly-frontend/src/main/js/src/service/services/personsearch/types.ts
- apps/person-search-service/src/main/java/no/nav/registre/testnorge/personsearchservice/adapter/utils/AdresserUtils.java
- apps/person-search-service/src/main/java/no/nav/registre/testnorge/personsearchservice/adapter/utils/IdentifikasjonUtils.java
- apps/person-search-service/src/main/java/no/nav/registre/testnorge/personsearchservice/adapter/utils/NasjonalitetUtils.java
- apps/person-search-service/src/main/java/no/nav/registre/testnorge/personsearchservice/adapter/utils/QueryUtils.java
- apps/person-search-service/src/main/java/no/nav/registre/testnorge/personsearchservice/adapter/utils/RelasjonerUtils.java
- apps/person-search-service/src/main/java/no/nav/registre/testnorge/personsearchservice/controller/search/RelasjonSearch.java
- apps/person-search-service/src/main/java/no/nav/registre/testnorge/personsearchservice/domain/ForelderBarnRelasjon.java
- apps/person-search-service/src/main/java/no/nav/registre/testnorge/personsearchservice/domain/PersonRolle.java
Har oppdatert testnorge søk til å kunne søke på om man har barn og dødfødt barn eller ikke (i motsetning til å kun kunne søke på om man har barn/dødfødt barn). Slik ser søket ut nå:
> Feature/testnorge søk barn oppdatering

- apps/dolly-frontend/src/main/js/src/components/ui/button/CopyButton/CopyButton.less
- apps/dolly-frontend/src/main/js/src/components/ui/button/CopyButton/CopyButton.tsx
- apps/dolly-frontend/src/main/js/src/pages/gruppe/PersonListe/PersonListe.js
- apps/dolly-frontend/src/main/js/src/pages/gruppe/PersonVisning/PersonVisning.less
- apps/dolly-frontend/src/main/js/src/pages/organisasjoner/OrganisasjonListe.tsx
- apps/dolly-frontend/src/main/js/src/pages/testnorgePage/search/SearchView.tsx
Har lagd en CopyButton og gjort at man kan kopiere ident fra testnorge søk.
> Dolly Frontend / copy button

- .github/workflows/app.person-search-service.yml
- apps/dolly-frontend/src/main/js/src/pages/testnorgePage/search/options/Adresser.tsx
- apps/dolly-frontend/src/main/js/src/pages/testnorgePage/search/options/Alder.tsx
- apps/dolly-frontend/src/main/js/src/pages/testnorgePage/search/options/IdentSearch.tsx
- apps/dolly-frontend/src/main/js/src/pages/testnorgePage/search/options/Identifikasjon.tsx
- apps/dolly-frontend/src/main/js/src/pages/testnorgePage/search/options/Nasjonalitet.tsx
- apps/dolly-frontend/src/main/js/src/pages/testnorgePage/search/options/Personstatus.tsx
- apps/dolly-frontend/src/main/js/src/pages/testnorgePage/search/options/Relasjoner.tsx
- apps/dolly-frontend/src/main/js/src/pages/testnorgePage/utils.ts
- apps/dolly-frontend/src/main/js/src/service/services/personsearch/types.ts
- apps/person-search-service/src/main/java/no/nav/registre/testnorge/personsearchservice/adapter/utils/AdresserUtils.java
- apps/person-search-service/src/main/java/no/nav/registre/testnorge/personsearchservice/controller/search/AdresserSearch.java
Testnorge søk på kontaktadresse for dødsbo.
> Feature/søk kontaktadresse dødsbo

- apps/dolly-frontend/src/main/js/src/components/fagsystem/pensjon/form/validation.js
Fiks for pensjon validering basert på alder.
> Dolly Frontend - Fikset pensjon validering

- apps/dolly-frontend/build.gradle
- apps/dolly-frontend/src/main/js/src/app/App.less
- apps/dolly-frontend/src/main/js/src/components/fagsystem/arena/form/Form.js
- apps/dolly-frontend/src/main/js/src/components/fagsystem/arena/form/partials/MedServicebehov.js
- apps/dolly-frontend/src/main/js/src/components/ui/button/SlettButton/SlettButton.tsx
- apps/dolly-frontend/src/main/js/src/pages/gruppe/GruppeHeader/GruppeHeader.js
Har ryddet litt i arena form og fikset litt css for alertstripe.
Har også lagt til betinget disabling av slett gruppe (kan kun slette hvis gruppen inneholder maks 15 personer)
> Dolly frontend/info og varsel tekst

- .github/workflows/app.adresse-service.yml
- .github/workflows/app.amelding-service.yml
- .github/workflows/app.dolly-backend.yml
- .github/workflows/app.dolly-frontend.yml
- .github/workflows/app.miljoer-service.yml
- .github/workflows/app.oppsummeringsdokument-service.yml
- .github/workflows/app.organisasjon-forvalter.yml
- .github/workflows/app.pdl-forvalter.yml
- .github/workflows/app.testnav-ident-pool.yml
- .github/workflows/app.udi-stub.yml
Kan deploye til dev for de appene vi gjør det mest ved å bruke `#deploy-app-navn-dev` i commit messagen
> Gjort det mulig å deploye til dev fra en spesifikk commit message

- apps/dolly-frontend/src/main/js/src/components/bestillingsveileder/stegVelger/steg/steg1/paneler/Arena.js
- apps/dolly-frontend/src/main/js/src/components/miljoVelger/MiljoeInfo/MiljoeInfo.js
Fjernet begrensning for opprettelse i Arena for test-norge identer
> Dolly -frontend / Fjernet begrensing arena

- apps/dolly-frontend/src/main/js/src/components/bestillingsveileder/stegVelger/steg/steg1/paneler/Pensjon.tsx
- apps/dolly-frontend/src/main/js/src/components/fagsystem/tjenestepensjon/form/Form.js
- apps/dolly-frontend/src/main/js/src/service/SelectOptions.tsx
- apps/dolly-frontend/src/main/js/src/service/services/pensjon/PensjonService.js
og set den til Options så den kan brukes i TP Form
> henting tp ordning nummer og navn fra pensjon data 

- apps/dolly-frontend/src/main/js/src/pages/gruppe/Gruppe.tsx
- apps/dolly-frontend/src/main/js/src/pages/gruppeOversikt/GruppeOversikt.js
- apps/dolly-frontend/src/main/js/src/pages/gruppeOversikt/Toggle.less
> Dolly Frontend - Justert css for gruppe toolbar

- apps/dolly-frontend/src/main/js/src/components/ui/button/FrigjoerButton/FrigjoerButton.tsx
- apps/dolly-frontend/src/main/js/src/components/ui/button/PartnerImportButton/PartnerImportButton.less
- apps/dolly-frontend/src/main/js/src/components/ui/button/PartnerImportButton/PartnerImportButton.tsx
- apps/dolly-frontend/src/main/js/src/ducks/fagsystem/index.js
- apps/dolly-frontend/src/main/js/src/ducks/redigertePersoner/index.tsx
- apps/dolly-frontend/src/main/js/src/pages/gruppe/Gruppe.tsx
- apps/dolly-frontend/src/main/js/src/pages/gruppe/GruppeConnector.tsx
- apps/dolly-frontend/src/main/js/src/pages/gruppe/GruppeHeader/GruppeHeader.tsx
- apps/dolly-frontend/src/main/js/src/pages/gruppe/GruppeHeader/GruppeHeaderConnector.tsx
- apps/dolly-frontend/src/main/js/src/pages/gruppe/PersonListe/PersonListe.js
- apps/dolly-frontend/src/main/js/src/pages/gruppe/PersonVisning/PersonVisning.js
- apps/dolly-frontend/src/main/js/src/pages/gruppe/PersonVisning/PersonVisning.less
- apps/dolly-frontend/src/main/js/src/pages/gruppe/PersonVisning/PersonVisningConnector.js
- apps/dolly-frontend/src/main/js/src/pages/testnorgePage/search/SearchView.tsx
- apps/dolly-frontend/src/main/js/src/pages/testnorgePage/search/importModal/ImportModal.less
- apps/dolly-frontend/src/main/js/src/pages/testnorgePage/search/importModal/ImportModal.tsx
- apps/dolly-frontend/src/main/js/src/service/services/dolly/DollyEndpoints.js
- apps/dolly-frontend/src/main/js/src/service/services/dolly/DollyService.js
- docs/applications/dolly/testnorge.md
Import av test-norge partner via søk og personvisning.
> Dolly frontend/partner import

- apps/dolly-backend/src/main/java/no/nav/dolly/bestilling/pensjonforvalter/PensjonforvalterClient.java
- apps/dolly-backend/src/main/java/no/nav/dolly/domain/resultset/pensjon/PensjonData.java
og sjekker ytelser array for å se hvis trenger å kjøre lagring requests
> Forhindre NPE i Pensjonforvalter

- apps/organisasjon-faste-data-service/config.yml
- proxies/inntektstub-proxy/config.yml
Inbound rule oppdatering for synt-vedtakshistorikk-service
> Oppdatert inbound rules

- apps/dolly-frontend/src/main/js/src/components/bestillingsveileder/stegVelger/Navigation/Navigation.js
- apps/dolly-frontend/src/main/js/src/components/bestillingsveileder/stegVelger/StegVelger.js
så hvis det var noen feil i submit, bruker kan prøve på nytt
> hvis klikke tilbake fra siste steg, set submitting til false

- .github/workflows/app.person-search-service.yml
- apps/person-search-service/src/main/java/no/nav/registre/testnorge/personsearchservice/service/utils/RelasjonerUtils.java
- libs/data-transfer-objects/src/main/java/no/nav/testnav/libs/dto/personsearchservice/v1/search/SivilstandSearch.java
> Person search service/mangler sivilstand

- apps/dolly-frontend/src/main/js/package-lock.json
- apps/dolly-frontend/src/main/js/package.json
- apps/dolly-frontend/src/main/js/src/allRoutes.js
- apps/dolly-frontend/src/main/js/src/components/layout/header/Header.tsx
- apps/dolly-frontend/src/main/js/src/pages/endringsmelding/Endringsmelding.less
- apps/dolly-frontend/src/main/js/src/pages/endringsmelding/Endringsmelding.tsx
Forslag til egen Endringsmelding side i Dolly med info om app og tilgang og med link/knapp til Endringsmelding.
> Dolly Frontend - Endringsmelding page

- apps/dolly-frontend/src/main/js/src/components/bestilling/detaljer/BestillingDetaljer.js
- apps/dolly-frontend/src/main/js/src/components/ui/button/LaasButton/LaasButton.tsx
- apps/dolly-frontend/src/main/js/src/components/ui/button/PartnerImportButton/PartnerImportButton.tsx
- apps/dolly-frontend/src/main/js/src/components/ui/button/Tags/TagsButton.tsx
- apps/dolly-frontend/src/main/js/src/components/ui/icon/Icon.less
- apps/dolly-frontend/src/main/js/src/pages/gruppe/PersonVisning/PersonVisning.js
- apps/dolly-frontend/src/main/js/src/service/services/dolly/DollyService.js
+ fikset knapper som har feil farge på ikon.
> Vis importer partner-knapp på alle personer med partner

- apps/dolly-frontend/src/main/js/src/components/fagsystem/pensjon/form/validation.js
Oppdatering av pensjon validering sånn at man kan ha maks alder 69. Har laget PR nå før jeg tar ferie, så det er bare å teste og eventuelt merge den inn når jeg er borte hvis det trengs ;)
> Dolly frontend/ekstra pensjon validering

- apps/dolly-frontend/src/main/js/src/pages/brukerPage/BrukernavnVelger.tsx
Begrenset valg av bankid brukernavn sånn at de kan kun inneholde (engelske) bokstaver og tall.
> Dolly Frontend - Begrenset valg av bankid brukernavn

- apps/dolly-frontend/src/main/js/src/components/ui/dollyTable/DollyTable.js
- apps/dolly-frontend/src/main/js/src/components/ui/dollyTable/pagination/SimplePagination.js
- apps/dolly-frontend/src/main/js/src/pages/gruppe/BestillingListe/BestillingListe.js
- apps/dolly-frontend/src/main/js/src/pages/gruppe/PersonListe/PersonListe.js
- apps/dolly-frontend/src/main/js/src/pages/gruppeOversikt/Liste.js
- apps/dolly-frontend/src/main/js/src/pages/minSide/maler/Maloversikt.js
- apps/dolly-frontend/src/main/js/src/pages/organisasjoner/OrganisasjonBestilling.tsx
- apps/dolly-frontend/src/main/js/src/pages/organisasjoner/OrganisasjonListe.tsx
- apps/dolly-frontend/src/main/js/src/pages/testnorgePage/search/SearchView.tsx
Ny versjon av Pagination for DollyTable funket ikke for testnorge søkeresultat. Byttet dermed til den gamle pagineringen for testnorge søk.
> Dolly Frontend - Oppdatert DollyTable paginering

- apps/orkestratoren/src/main/java/no/nav/registre/orkestratoren/provider/rs/IdentController.java
Fant et par SKD batch kjøringen jeg glemte å stoppe.
> Orkestratoren - Stoppet skd slett jobber

- apps/organisasjon-tilgang-frontend/build.gradle
- apps/organisasjon-tilgang-frontend/gradle/wrapper/gradle-wrapper.properties
- apps/organisasjon-tilgang-frontend/settings.gradle
Eneste appen i monorepo som ikke hadde oppdatert versjon av gradle og spring.
> Organisasjon-tilgang-frontend / Oppdatert versjoner

- apps/dolly-frontend/src/main/js/src/app/App.tsx
- apps/dolly-frontend/src/main/js/src/components/utlogging/logoutBruker.tsx
- apps/dolly-frontend/src/main/js/src/pages/testnorgePage/search/importModal/MalValg.tsx
Det ble veldig mye whitespace endringer av en eller annen grunn, men er få linjer endret 🤓
> Fikset issues under merge av SWR og lagt til noe lazy loading

- apps/dolly-backend/src/main/java/no/nav/dolly/bestilling/pdlforvalter/PdlForvalterClient.java
- apps/dolly-backend/src/main/java/no/nav/dolly/mapper/BestillingPdlDataStatusMapper.java
- apps/dolly-backend/src/main/java/no/nav/dolly/mapper/BestillingPdlForvalterStatusMapper.java
- apps/pdl-forvalter/src/main/java/no/nav/pdl/forvalter/mapper/FolkeregisterPersonstatusMappingStrategy.java
Ser ut til å være i orden nå, har lagt på litt feilmeldinger, ble ikke logget noe sted så måtte lete litt i blinde 😅 
Har pushet til dev så det kan testes på frontend-dev 👍
> Sender med status på FolkeregisterPersonStatus i pdl-forvalter

- apps/dolly-frontend/src/main/js/src/components/fagsystem/inntektsmelding/visning/Visning.tsx
- apps/dolly-frontend/src/main/js/src/service/services/JoarkDokumentService.ts
Kollapset inntektsmelding visning hvis mer enn 5 meldinger.
> Dolly frontend/kollapse inntekt visning

- apps/dolly-frontend/src/main/js/src/components/bestilling/sammendrag/kriterier/BestillingKriterieMapper.js
Har fikset nesten alle sonarcloud code smells i BestillingKriterieMapper filen. Hovedsakelig flyttet jeg bare kode ut i egne metoder da mapBestillingData-metoden hadde en kompleksitet på 345 og fikset deretter andre mindre code smells.
> Dolly frontend/ryddet i BestillingKriterieMapper

- apps/dolly-backend/src/main/java/no/nav/dolly/bestilling/tpsmessagingservice/TpsMessagingClient.java
- apps/dolly-backend/src/main/java/no/nav/dolly/domain/resultset/BestilteKriterier.java
- apps/dolly-backend/src/main/java/no/nav/dolly/domain/resultset/RsDollyBestilling.java
- apps/dolly-backend/src/main/java/no/nav/dolly/domain/resultset/tpsmessagingservice/BankkontoData.java
- apps/dolly-backend/src/main/java/no/nav/dolly/service/BestillingService.java
(men også i tps messaging for bakoverkompatibilitet)
> bankkonto har egen felt i bestillingskriterier 

- .github/workflows/app.testnorge-inntekt.yml
- .github/workflows/app.testnorge-medl.yml
- .github/workflows/app.testnorge-sam.yml
- .github/workflows/app.testnorge-sigrun.yml
Stoppet deploy av testnorge-sam, testnorge-medl, testnorge-sigrun og testnorge-inntekt da jeg ikke tror de lenger er i bruk. Skal teste dette ved å ta ned deployet versjon av disse, og hvis ingen klarer etter en stund så kan vi fjerne dem fra monorepo.
> Stoppet deploy av testnorge- apper

- apps/dolly-frontend/README.md
- apps/dolly-frontend/src/main/js/src/components/bestilling/detaljer/BestillingDetaljer.js
- apps/dolly-frontend/src/main/js/src/components/bestilling/sammendrag/BestillingSammendragModal.js
- apps/dolly-frontend/src/main/js/src/components/bestilling/sammendrag/kriterier/Bestillingskriterier.js
- apps/dolly-frontend/src/main/js/src/components/bestilling/sammendrag/kriterier/OrganisasjonKriterier.tsx
- apps/dolly-frontend/src/main/js/src/components/bestillingsveileder/stegVelger/steg/steg3/VelgGruppe.tsx
- apps/dolly-frontend/src/main/js/src/components/fagsystem/inntektsmelding/visning/partials/enkelInntektsmeldingVisning.tsx
- apps/dolly-frontend/src/main/js/src/components/fagsystem/inntektsmelding/visning/partials/personVisningContent.tsx
- apps/dolly-frontend/src/main/js/src/components/fagsystem/inst/form/utils.js
- apps/dolly-frontend/src/main/js/src/components/fagsystem/organisasjoner/visning/Visning.tsx
- apps/dolly-frontend/src/main/js/src/components/fagsystem/organisasjoner/visning/miljoevisning/OrganisasjonDataVisning.tsx
- apps/dolly-frontend/src/main/js/src/components/fagsystem/organisasjoner/visning/miljoevisning/OrganisasjonMiljoeinfo.tsx
- apps/dolly-frontend/src/main/js/src/components/fagsystem/pdlf/form/partials/sikkerhetstiltak/Sikkerhetstiltak.tsx
- apps/dolly-frontend/src/main/js/src/components/fagsystem/pdlf/form/partials/telefonnummer/Telefonnummer.tsx
- apps/dolly-frontend/src/main/js/src/components/fagsystem/tpsf/visning/partials/Barn.js
- apps/dolly-frontend/src/main/js/src/components/fagsystem/tpsf/visning/partials/Foreldre.tsx
- apps/dolly-frontend/src/main/js/src/components/fagsystem/tpsmessaging/form/utenlandskbankkonto/UtenlandskBankkonto.tsx
- apps/dolly-frontend/src/main/js/src/components/ui/button/FrigjoerButton/FrigjoerButton.tsx
- apps/dolly-frontend/src/main/js/src/components/ui/button/LaasButton/LaasButton.tsx
- apps/dolly-frontend/src/main/js/src/components/ui/button/PartnerImportButton/PartnerImportButton.tsx
- apps/dolly-frontend/src/main/js/src/components/ui/button/SlettButton/SlettButton.tsx
- apps/dolly-frontend/src/main/js/src/components/ui/dollyTable/table/TableRow.js
- apps/dolly-frontend/src/main/js/src/pages/gruppe/PersonVisning/PersonMiljoeinfo/PdlDataVisning.tsx
From React documentation:
Always use Hooks at the top level of your React function, before any early returns. By following this rule, you ensure that Hooks are called in the same order each time a component renders. That’s what allows React to correctly preserve the state of Hooks between multiple useState and useEffect calls.
> Dolly frontend/sonar fix 4

- apps/person-search-service/src/main/java/no/nav/registre/testnorge/personsearchservice/domain/IdentSearch.java
- apps/person-search-service/src/main/java/no/nav/registre/testnorge/personsearchservice/service/utils/QueryBuilder.java
- libs/data-transfer-objects/src/main/java/no/nav/testnav/libs/dto/personsearchservice/v1/search/PersonSearch.java
Lagt til mulighet til å søke etter person med multiple tags.
> Person search service/multiple tags

- apps/dolly-frontend/src/main/js/src/components/fagsystem/arena/visning/ArenaVisning.js
- apps/dolly-frontend/src/main/js/src/pages/gruppe/PersonVisning/PersonVisning.js
- apps/dolly-frontend/src/main/js/src/pages/testnorgePage/search/SearchView.tsx
- apps/dolly-frontend/src/main/js/src/pages/testnorgePage/utils.ts
- apps/dolly-frontend/src/main/js/src/service/services/dolly/DollyEndpoints.js
- apps/dolly-frontend/src/main/js/src/service/services/dolly/DollyService.js
- apps/dolly-frontend/src/main/js/src/service/services/personsearch/types.ts
Viser advarsel om at testnorge ident allerede kan være i Arena hvis ident har ARENASYNT tag.
> Dolly frontend/info tag arenasynt

- apps/dolly-frontend/src/main/js/src/assets/index.html
- apps/endringsmelding-frontend/src/main/js/public/index.html
- apps/faste-data-frontend/src/main/js/public/index.html
- apps/organisasjon-tilgang-frontend/src/main/js/public/index.html
- apps/oversikt-frontend/src/main/js/public/index.html
- apps/tps-messaging-service/build.gradle
Ser for øvrig at det brukes NB/NN i SelectOptions.tsx/Utils.js, men WCAG ønsker seg NO.
> WCAG 3.1.1: Endra "no" til "en

- apps/dolly-frontend/src/main/js/src/components/bestilling/sammendrag/BestillingSammendrag.js
- apps/dolly-frontend/src/main/js/src/components/bestilling/sammendrag/kriterier/BestillingKriterieMapper.js
- apps/dolly-frontend/src/main/js/src/components/bestilling/sammendrag/kriterier/Bestillingskriterier.js
- apps/dolly-frontend/src/main/js/src/components/bestillingsveileder/bestillingTypes.ts
- apps/dolly-frontend/src/main/js/src/components/bestillingsveileder/options/options.js
- apps/dolly-frontend/src/main/js/src/components/bestillingsveileder/stegVelger/steg/steg3/IdentVelger.tsx
- apps/dolly-frontend/src/main/js/src/components/fagsystem/pdlf/form/initialValues.ts
- apps/dolly-frontend/src/main/js/src/components/fagsystem/pdlf/form/partials/familierelasjoner/sivilstand/Sivilstand.tsx
- apps/dolly-frontend/src/main/js/src/components/fagsystem/pdlf/form/partials/fullmakt/Fullmakt.tsx
- apps/dolly-frontend/src/main/js/src/components/fagsystem/pdlf/form/partials/nyIdent/nyIdent.tsx
- apps/dolly-frontend/src/main/js/src/components/fagsystem/pdlf/form/partials/pdlPerson/PdlEksisterendePerson.tsx
- apps/dolly-frontend/src/main/js/src/components/fagsystem/pdlf/form/partials/pdlPerson/PdlNyPerson.tsx
- apps/dolly-frontend/src/main/js/src/components/fagsystem/pdlf/form/partials/utils.js
- apps/dolly-frontend/src/main/js/src/components/fagsystem/pdlf/form/partials/vergemaal/Vergemaal.tsx
Har byttet til at NAV syntetisk ident er default identtype. Har også oppdatert koden sånn at "syntetisk" verdi på nye relaterte personen blir det samme som valgt til hovedperson.
> Dolly frontend/bytte til syntetisk

- apps/dolly-frontend/src/main/js/src/pages/gruppeOversikt/FinnPersonBestilling.tsx
Gjør alle personsøk parallellt for raskere respons. Fortsatt ikke kjemperaskt, men mye bedre 😁
> Personsøk parallelle kall

- apps/dolly-frontend/src/main/js/src/components/fagsystem/krrstub/visning/KrrVisning.tsx
- apps/dolly-frontend/src/main/js/src/components/ui/historikk/ArrayHistorikk.js
- apps/dolly-frontend/src/main/js/src/components/ui/historikk/historikk.less
Har oppdatert ArrayHistorikk komponent og KrrVisning. 
For KRR er det "gyldig fra"-datoene på de forskjellige radene som dikterer hva som er gyldig på et gitt tidspunkt. Har oppdatert visningen sånn all fremtidig data og den siste gyldige raden viser som gjeldende, mens resten av radene er i historikk.
> Dolly frontend/oppdatere krr visning

- proxies/sykemelding-api-proxy/config.yml
Glemte å oppdatere inbound rules for synt-sykemelding-proxy.
> Oppdatert inbound

- apps/dolly-backend/config.dev.yml
- apps/dolly-backend/config.yml
- apps/dolly-backend/src/main/java/no/nav/dolly/bestilling/sykemelding/SykemeldingClient.java
- apps/dolly-backend/src/main/java/no/nav/dolly/bestilling/sykemelding/SyntSykemeldingConsumer.java
- apps/dolly-backend/src/main/java/no/nav/dolly/bestilling/sykemelding/command/PostSyntSykemeldingCommand.java
- apps/dolly-backend/src/main/java/no/nav/dolly/config/credentials/SyntSykemeldingApiProperties.java
- apps/dolly-backend/src/main/java/no/nav/dolly/provider/api/EnvironmentIsAliveController.java
- apps/dolly-backend/src/main/java/no/nav/dolly/util/CheckAliveUtil.java
- apps/dolly-backend/src/main/resources/application.yaml
- proxies/sykemelding-api-proxy/config.yml
- proxies/sykemelding-api-proxy/src/main/java/no/nav/testnav/proxies/sykemeldingapiproxy/SykemeldingApiProxyApplicationStarter.java
Synt-sykemelding PR må merges inn før denne.
> Dolly-backend/bytte til ny synt sykemelding

- apps/arbeidsforhold-service/config.yml
- apps/helsepersonell-service/config.yml
- apps/organisasjon-service/config.yml
- proxies/sykemelding-api-proxy/src/main/java/no/nav/testnav/proxies/sykemeldingapiproxy/SykemeldingApiProxyApplicationStarter.java
Har blitt erstattet av testnav-synt-sykemelding-api
> Fjernet testnorge-synt-sykemelding-api

- apps/import-fra-tpsf-service/src/main/resources/application-local.yaml
Fikset dolly-backend-dev url i application-local.yml
> Oppdatert local properties

- apps/bruker-service/config.yml
> Fjernet inbound

- apps/dolly-frontend/src/main/js/src/app/App.tsx
- apps/dolly-frontend/src/main/resources/application-prod.yml
Fiks for bankid utlogging ved feil
> Dolly frontend/bankid utlogging ved feil

- apps/dolly-backend/config.dev.yml
- apps/dolly-backend/config.yml
Fant jwt secret for gcp som brukes ved bankid innlogging :)
> Dolly backend / jwt secret fiks

- apps/dolly-frontend/src/main/js/src/pages/gruppe/Gruppe.tsx
- apps/dolly-frontend/src/main/js/src/pages/gruppe/ManglerTilgang/ManglerTilgang.less
- apps/dolly-frontend/src/main/js/src/pages/gruppe/ManglerTilgang/ManglerTilgang.tsx
- apps/dolly-frontend/src/main/js/src/pages/gruppeOversikt/GruppeOversikt.tsx
Har fjernet visning av søk og andres grupper for bankidbrukere. Har også gjort at hvis de går inn på en gruppe som ikke er deres så ser de kun "Du mangler tilgang til denne gruppen".
> Dolly frontend/blokkere gruppevisning bankid

- apps/dolly-frontend/src/main/js/src/components/ui/button/FrigjoerButton/FrigjoerButton.tsx
- apps/dolly-frontend/src/main/js/src/components/ui/button/PartnerImportButton/PartnerImportButton.less
- apps/dolly-frontend/src/main/js/src/components/ui/button/PartnerImportButton/PartnerImportButton.tsx
- apps/dolly-frontend/src/main/js/src/components/ui/button/RelatertPersonImportButton/RelatertPersonImportButton.less
- apps/dolly-frontend/src/main/js/src/components/ui/button/RelatertPersonImportButton/RelatertPersonImportButton.tsx
- apps/dolly-frontend/src/main/js/src/components/ui/form/inputs/checbox/Checkbox.js
- apps/dolly-frontend/src/main/js/src/components/velgGruppe/EksisterendeGruppe.tsx
- apps/dolly-frontend/src/main/js/src/ducks/fagsystem/index.js
- apps/dolly-frontend/src/main/js/src/pages/gruppe/PersonListe/PersonListe.js
- apps/dolly-frontend/src/main/js/src/pages/gruppe/PersonVisning/PersonVisning.js
- apps/dolly-frontend/src/main/js/src/pages/gruppe/PersonVisning/PersonVisningConnector.js
- apps/dolly-frontend/src/main/js/src/service/services/dolly/DollyService.js
Mulig å importere barn i tillegg til partner. Er laget slik at vi enkelt kan legge til import av andre relaterte personer dersom det blir nødvendig.
> Dolly frontend/importer barn

- apps/dolly-frontend/src/main/js/src/components/ui/button/RelatertPersonImportButton/RelatertPersonImportButton.tsx
- apps/dolly-frontend/src/main/js/src/ducks/fagsystem/index.js
- apps/dolly-frontend/src/main/js/src/pages/gruppe/PersonListe/PersonListe.js
Fiks for å hente importert relatert person umiddelbart.
Fiks for å hente oppdatert person rett etter legg til/endre.
Takk til @stigus for mye hjelp 😄
> Dolly frontend/bugfix rendring av person gruppe

- apps/bruker-service/src/main/java/no/nav/testnav/apps/brukerservice/controller/BrukerController.java
- apps/bruker-service/src/main/java/no/nav/testnav/apps/brukerservice/controller/StatusController.java
Oppdatert endepunkt for å sjekke om to bankid brukere er i samme org.
> Bruker service/check brukernavn

- apps/synt-vedtakshistorikk-service/src/main/java/no/nav/testnav/apps/syntvedtakshistorikkservice/consumer/ArenaForvalterConsumer.java
- apps/synt-vedtakshistorikk-service/src/main/java/no/nav/testnav/apps/syntvedtakshistorikkservice/provider/BatchController.java
- apps/synt-vedtakshistorikk-service/src/main/java/no/nav/testnav/apps/syntvedtakshistorikkservice/provider/BrukerController.java
- apps/synt-vedtakshistorikk-service/src/main/java/no/nav/testnav/apps/syntvedtakshistorikkservice/service/ArenaDagpengerService.java
- apps/synt-vedtakshistorikk-service/src/main/java/no/nav/testnav/apps/syntvedtakshistorikkservice/service/ArenaForvalterService.java
- libs/data-transfer-objects/src/main/java/no/nav/testnav/libs/dto/syntvedtakshistorikkservice/v1/DagpengerRequestDTO.java
- libs/data-transfer-objects/src/main/java/no/nav/testnav/libs/dto/syntvedtakshistorikkservice/v1/DagpengerResponseDTO.java
- libs/data-transfer-objects/src/main/java/no/nav/testnav/libs/dto/syntvedtakshistorikkservice/v1/DagpengevedtakDTO.java
- libs/data-transfer-objects/src/main/java/no/nav/testnav/libs/dto/syntvedtakshistorikkservice/v1/dagpenger/Dagpengeperiode.java
- libs/data-transfer-objects/src/main/java/no/nav/testnav/libs/dto/syntvedtakshistorikkservice/v1/dagpenger/GodkjenningerReellArbeidssoker.java
- libs/data-transfer-objects/src/main/java/no/nav/testnav/libs/dto/syntvedtakshistorikkservice/v1/dagpenger/TaptArbeidstid.java
- libs/data-transfer-objects/src/main/java/no/nav/testnav/libs/dto/syntvedtakshistorikkservice/v1/dagpenger/Vedtaksperiode.java
Lagd en forenklet versjon av innsending av dagpenger hvor ident får samme dagpenger vedtak som bruker i Dolly. 5 personer får dagpenger hver dag med denne metoden, mens vi venter på et bedre dagpenger uttrekk for synt-dagpenger.
> Synt vedtakshistorikk service/default dagpenger

- apps/dolly-frontend/src/main/js/src/api/index.ts
Import av logoutBruker metode manglet
> Dolly frontend - Import av logout bruker

- apps/dolly-frontend/src/main/js/src/components/bestillingsveileder/options/malOptions.ts
Så at kontaktinfo mal ikke funket helt, har fikset det nå :)
> Dolly frontend - Fiks for kontaktinfo mal

- apps/dolly-backend/src/main/java/no/nav/dolly/bestilling/aareg/AaregClient.java
- apps/dolly-backend/src/main/java/no/nav/dolly/bestilling/aareg/amelding/AmeldingService.java
- apps/dolly-backend/src/main/java/no/nav/dolly/bestilling/aareg/util/AaregUtil.java
- apps/dolly-backend/src/test/java/no/nav/dolly/bestilling/aareg/util/AaregUtilTest.java
Relatert til https://trello.com/c/8BLWHeke.
Flytter ut Amelding-kode i egen service for å strippe ned AaregClient.
> Flyttet Amelding-kode fra AaregClient til egen AmeldingService.

- apps/dolly-frontend/src/main/js/src/components/fagsystem/pdl/visning/PdlVisning.tsx
- apps/dolly-frontend/src/main/js/src/components/fagsystem/pdl/visning/partials/vergemaal/PdlVergemaal.tsx
- apps/dolly-frontend/src/main/js/src/components/fagsystem/pdl/visning/partials/vergemaal/Verge.tsx
- apps/dolly-frontend/src/main/js/src/components/fagsystem/pdlf/PdlTypes.ts
- apps/dolly-frontend/src/main/js/src/components/fagsystem/pdlf/visning/partials/Vergemaal.tsx
- apps/dolly-frontend/src/main/js/src/pages/gruppe/PersonVisning/PersonMiljoeinfo/PdlDataTyper.tsx
Har laget en egen visning av vergemål for PdlVisning og oppdatert visningen i PdlfVisning sånn at den kun er for PDLF data.
> Dolly frontend/oppdatere pdl vergemaal visning

- apps/dolly-frontend/src/main/js/src/components/fagsystem/pdlf/form/partials/adresser/adressebeskyttelse/Adressebeskyttelse.tsx
- apps/dolly-frontend/src/main/js/src/components/fagsystem/pdlf/visning/VisningRedigerbar.tsx
Har oppdatert options for adressebeskyttelse sånn at det alltid blir satt basert på identtype.
> Dolly frontend/adressebeskyttelse valg

- .nais/redis.yml
https://nav-it.slack.com/archives/C01DE3M9YBV/p1662028690092629?thread_ts=1659686661.223049&cid=C01DE3M9YBV
flagget ikke lenger ha noen effekt
> nais.io/security-does-not-matter flagget ikke lenger ha noen effekt

- apps/dolly-frontend/src/main/js/src/pages/testnorgePage/search/partials/Relasjoner.tsx
Oppdatert test-norge søk etter sivilstand
> Dolly frontend - Lagt til alle sivilstander i søk

- apps/dolly-frontend/src/main/js/src/components/fagsystem/pdlf/form/validation.js
Skal være mulig å registrere en sivilstand uten dato
> Dolly frontend - Fjernet validering sivilstandsdato

- apps/testnorge-statisk-data-forvalter/README.md
- apps/testnorge-statisk-data-forvalter/src/main/java/no/nav/registre/sdforvalter/consumer/rs/HodejegerenConsumer.java
- apps/testnorge-statisk-data-forvalter/src/main/java/no/nav/registre/sdforvalter/consumer/rs/TpConsumer.java
- apps/testnorge-statisk-data-forvalter/src/main/java/no/nav/registre/sdforvalter/consumer/rs/command/GetAlleIdenterCommand.java
- apps/testnorge-statisk-data-forvalter/src/main/java/no/nav/registre/sdforvalter/consumer/rs/command/GetLevendeIdenterCommand.java
- apps/testnorge-statisk-data-forvalter/src/main/java/no/nav/registre/sdforvalter/consumer/rs/command/OpprettPersonerTpCommand.java
- apps/testnorge-statisk-data-forvalter/src/main/java/no/nav/registre/sdforvalter/service/IdentService.java
- apps/testnorge-statisk-data-forvalter/src/main/resources/application.yml
- apps/testnorge-statisk-data-forvalter/src/test/resources/application-test.yml
Oppdatert HodejegerenConsumer og TpConsumer i testnorge-statisk-data-fovalter til å bruker webclient i stedet for resttemplate.
> Testnorge-statisk-data-fovalter - Oppdatert consumers

- apps/dolly-frontend/src/main/java/no/nav/dolly/web/provider/web/ForwardAndRedirectController.java
- apps/dolly-frontend/src/main/js/src/allRoutes.js
- apps/dolly-frontend/src/main/js/src/components/layout/header/Header.tsx
- apps/dolly-frontend/src/main/js/src/pages/dokumentasjon/Dokumentasjon.less
- apps/dolly-frontend/src/main/js/src/pages/dokumentasjon/Dokumentasjon.tsx
Flyttet link til brukerdokumentasjon og API-dokumentasjon til en egen "Dokumentasjon" side.
> Dolly frontend/egen dokumentasjon side

- apps/dolly-frontend/src/main/js/src/components/bestillingsveileder/stegVelger/Navigation/Navigation.js
- apps/dolly-frontend/src/main/js/src/components/bestillingsveileder/stegVelger/StegVelger.js
Kan ikke lenger trykke videre hvis ikke alle påkrevde felt i inntektstub er fylt ut.
> Dolly frontend - Fiks for inntektstub validering

- apps/dolly-frontend/src/main/js/src/components/bestillingsveileder/stegVelger/steg/steg1/paneler/Udi.js
Har fjernet muligheten til å bestille alias via udistub da det ikke funker for øyeblikket.
> Dolly frontend -Midlertidig fjerning alias

- proxies/tps-forvalteren-proxy/config.dev.yml
- proxies/tps-forvalteren-proxy/config.yml
Lagt til hodejegeren i inbound rules og fjernet duplikat av testnav-oversikt-frontend
> Tpsf-proxy /Oppdatert inbound rules

- apps/dolly-frontend/src/main/js/src/components/bestillingsveileder/stegVelger/Navigation/Navigation.js
- apps/dolly-frontend/src/main/js/src/components/bestillingsveileder/stegVelger/steg/steg2/Steg2.js
Disabled "Videre" knapp i steg 2 hvis det er en tom legg-til bestilling.
> Dolly frontend - Stoppet tom bestilling for legg til

- .github/workflows/app.dolly-frontend.yml
- .github/workflows/common.build-and-publish.backend.yml
- .github/workflows/common.build-and-publish.frontend.yml
- .github/workflows/common.deploy.yml
- .github/workflows/common.java-build.yml
- .github/workflows/common.js.build.yml
- .github/workflows/common.js.publish.yml
- .github/workflows/common.sonar.yml
Lagt til støtte for flere cores slik at build and deploy skal kjøre en god del raskere
> Implementert large runner

- apps/dolly-frontend/src/main/js/src/components/varslinger/VarslingerTekster.tsx
- docs/applications/dolly/brukerveiledning.md
Fjernet siste info angående import av grupper tilknyttet z-ident
> Dolly frontend/fjerne z ident dokumentasjon

- apps/dolly-frontend/src/main/js/src/components/fagsystem/sigrunstub/form/Form.js
Kan ha max en inntekt per år for sigrunstub.
> Dolly frontend - Oppdatert sigrunstub validering

- apps/dolly-frontend/src/main/js/src/components/miljoVelger/MiljoVelger.js
Kan ikke velge miljø QX eller T13 lenger i bestilling av person eller organisasjon.
> Dolly frontend - Fjernet miljø qx og t13 fra miljøvelger

- apps/dolly-frontend/src/main/js/src/components/bestillingsveileder/stegVelger/steg/steg1/paneler/Personinformasjon.tsx
Har endret kode sånn at en person uten hverken inn- eller utvandring kan bestille innvandring (tidligere var det kun utvandring)
> Dolly frotnend - Oppdatert inn- og utvandring disabling

- apps/dolly-frontend/src/main/js/src/pages/testnorgePage/search/SearchOptions.tsx
- apps/dolly-frontend/src/main/js/src/pages/testnorgePage/search/partials/Alder.tsx
- apps/dolly-frontend/src/main/js/src/pages/testnorgePage/search/partials/Identer.tsx
> når trykker Enter i input felt (i TestNorge søk), gjør søk

- apps/dolly-frontend/src/main/js/src/components/fagsystem/sigrunstub/form/Form.js
Har fikset sigrunstub validering sånn at bruker kan ha max en inntekt per år for hver tjeneste.
> Dolly frontend - Oppdatert sigrunstub validering for årstall

- apps/dolly-frontend/src/main/js/src/components/fagsystem/pdl/visning/PdlVisning.tsx
- apps/dolly-frontend/src/main/js/src/components/fagsystem/tpsmessaging/form/TpsMessagingData.tsx
- apps/dolly-frontend/src/main/js/src/pages/gruppe/PersonVisning/PersonMiljoeinfo/PdlDataVisning.tsx
- apps/dolly-frontend/src/main/js/src/pages/testnorgePage/utils.ts
Fikset en react feil i PdlVisning. Fikset også sånn at loading og error ikke er delt mellom "PDL" og "Q1" henting av data i PdlDataVisning.
> Dolly frontend/pdl visning fiks

- apps/dolly-backend/src/main/java/no/nav/dolly/domain/jpa/BestillingProgress.java
- apps/dolly-backend/src/main/resources/db/migration/V1.7.9__AlterTableBestillingProgressChangeDokarkivstatusLength.sql
> satt dokarkivStatus til varchar(4000)

- apps/dolly-frontend/src/main/js/src/components/fagsystem/bankkonto/visning/NorskBankkonto.tsx
Har lagt til punktum i visning av norsk bankkontonummer sånn at det blir vist på formatet: 1234.56.78910
> Dolly frontend - Punktum i norsk bankkonto nummer

- apps/jenkins-batch-status-service/src/main/java/no/nav/registre/testnorge/jenkinsbatchstatusservice/consumer/OrganisasjonBestillingConsumer.java
- apps/profil-api/src/main/java/no/nav/registre/testnorge/profil/consumer/AzureAdProfileConsumer.java
- apps/profil-api/src/main/java/no/nav/registre/testnorge/profil/service/AzureAdTokenService.java
- libs/reactive-security/src/main/java/no/nav/testnav/libs/reactivesecurity/decoder/JwtDecoder.java
- libs/reactive-security/src/main/java/no/nav/testnav/libs/reactivesecurity/exchange/azuread/AzureAdTokenService.java
- libs/reactive-security/src/main/java/no/nav/testnav/libs/reactivesecurity/exchange/azuread/NavAzureAdTokenService.java
- libs/reactive-security/src/main/java/no/nav/testnav/libs/reactivesecurity/exchange/azuread/TrygdeetatenAzureAdTokenService.java
- libs/servlet-insecure-security/src/main/java/no/nav/testnav/libs/standalone/servletsecurity/exchange/AzureAdTokenService.java
- libs/servlet-security/src/main/java/no/nav/testnav/libs/servletsecurity/exchange/AzureAdTokenService.java
- libs/slack/src/main/java/no/nav/testnav/libs/slack/consumer/SlackConsumer.java
Pluss et par mindre warnings i berørte filer.
> Fjerner bruk av deprecated HttpClient.tcpConfiguration(...)

- apps/dolly-frontend/src/main/js/src/components/ui/button/FrigjoerButton/FrigjoerButton.tsx
- apps/dolly-frontend/src/main/js/src/components/ui/button/SlettButton/SlettButton.tsx
Henter gruppe på nytt etter sletting.
> Bugfix - fjern visning av slettet person

- apps/helsepersonell-service/src/main/java/no/nav/registre/testnorge/helsepersonellservice/consumer/SamhandlerregisteretConsumer.java
- apps/helsepersonell-service/src/main/java/no/nav/registre/testnorge/helsepersonellservice/consumer/command/GetSamhandlerCommand.java
- apps/helsepersonell-service/src/main/java/no/nav/registre/testnorge/helsepersonellservice/exception/IdentNotFoundException.java
- apps/helsepersonell-service/src/main/java/no/nav/registre/testnorge/helsepersonellservice/exception/SamhandlerException.java
- apps/helsepersonell-service/src/main/java/no/nav/registre/testnorge/helsepersonellservice/exception/SamhandlereNotFoundException.java
- apps/helsepersonell-service/src/main/java/no/nav/registre/testnorge/helsepersonellservice/service/HelsepersonellService.java
- apps/helsepersonell-service/src/main/java/no/nav/registre/testnorge/helsepersonellservice/util/WebClientFilter.java
- apps/helsepersonell-service/src/main/resources/application-dev.yml
- apps/helsepersonell-service/src/main/resources/application.yml
- apps/helsepersonell-service/src/test/java/no/nav/registre/testnorge/helsepersonellservice/consumer/SamhandlerregisteretConsumerTest.java
Har ryddet litt og forenklet kode i helsepersonell-service
> Helsepersonell service/oppdatert kode

- apps/dolly-frontend/src/main/js/src/components/infostripe/DollyInfoAlert.less
- apps/dolly-frontend/src/main/js/src/components/infostripe/InfoStripe.tsx
> Dolly frontend - Oppdatert cursor for close knapper i infostripe

- apps/dolly-backend/src/main/java/no/nav/dolly/bestilling/pensjonforvalter/PensjonforvalterClient.java
og ytelser opprettes etter forhold er ferdig
> Dolly backend/pensjonforvalter lagretp med flux concat

- apps/dolly-frontend/src/main/js/src/components/fagsystem/pdl/visning/partials/relasjoner/PdlPartner.tsx
- apps/dolly-frontend/src/main/js/src/components/fagsystem/pdl/visning/partials/relasjoner/PdlRelasjoner.tsx
Viser nå sivilstand UGIFT i PdlVisning
> Dolly frontend - Viser sivilstand ugift for PDL

- apps/dolly-frontend/src/main/js/src/components/bestilling/statusListe/BestillingResultat/BestillingResultat.tsx
- apps/dolly-frontend/src/main/js/src/components/bestilling/statusListe/StatusListe.tsx
Fikset sånn at lukking av en ferdig bestilling ikke lenger også lukker alle andre bestillinger som ikke er ferdig. Ble litt kode rydding også.
> Dolly frontend - Oppdatert lukking av bestilling

- apps/dolly-frontend/src/main/js/src/components/bestilling/gjenopprett/GjenopprettBestilling.js
- apps/dolly-frontend/src/main/js/src/components/bestilling/statusListe/BestillingProgresjon/BestillingProgresjon.tsx
- apps/dolly-frontend/src/main/js/src/pages/gruppe/Gruppe.tsx
- apps/dolly-frontend/src/main/js/src/pages/gruppe/PersonListe/PersonListe.js
- apps/dolly-frontend/src/main/js/src/pages/gruppe/PersonVisning/PersonVisning.js
Nå funker refetch av persondata etter legg til /endre.
Fant ikke noe sted i personvisning hvor mountedref ble brukt, så fjernet det også.
> Dolly frontend/fiks for refetch etter legg til

- apps/dolly-frontend/src/main/js/src/ducks/fagsystem/index.js
- apps/dolly-frontend/src/main/js/src/pages/gruppe/PersonListe/PersonListe.js
- apps/dolly-frontend/src/main/js/src/pages/gruppe/PersonListe/PersonListeConnector.js
Status på siste bestilling til person blir nå vist ordentlig i personliste
> Dolly frontend/fikset visning av status på siste bestilling

- apps/dolly-frontend/src/main/js/src/components/bestilling/sammendrag/kriterier/Bestillingskriterier.js
- apps/dolly-frontend/src/main/js/src/components/fagsystem/aareg/visning/Visning.tsx
- apps/dolly-frontend/src/main/js/src/components/fagsystem/brregstub/visning/BrregVisning.js
- apps/dolly-frontend/src/main/js/src/components/fagsystem/inntektstub/visning/Visning.tsx
- apps/dolly-frontend/src/main/js/src/components/fagsystem/inst/visning/InstVisning.js
- apps/dolly-frontend/src/main/js/src/components/fagsystem/krrstub/visning/KrrVisning.tsx
- apps/dolly-frontend/src/main/js/src/components/fagsystem/pensjon/visning/PensjonVisning.js
- apps/dolly-frontend/src/main/js/src/components/fagsystem/sigrunstub/visning/Visning.js
- apps/dolly-frontend/src/main/js/src/components/fagsystem/tjenestepensjon/visning/TpVisning.js
- apps/dolly-frontend/src/main/js/src/components/fagsystem/udistub/visning/UdiVisning.js
- apps/dolly-frontend/src/main/js/src/pages/testnorgePage/search/optionsPanel/OptionsPanel.less
Fikset css for søkealternativer i testnorge søk, key warning for bestillingkriterier og info tekst for manglende fagsystemdata.
> Dolly frontend/små fiks

- apps/dolly-frontend/src/main/js/src/components/fagsystem/pdlf/form/partials/familierelasjoner/foreldreansvar/Foreldreansvar.tsx
- apps/dolly-frontend/src/main/js/src/components/fagsystem/pdlf/form/validation/partials/familierelasjoner.tsx
Tar høyde for allerede eksisterende verdier ved legg til/endre.
> Ny validering foreldreansvar

- apps/dolly-backend/src/main/java/no/nav/dolly/bestilling/aareg/AaregClient.java
- apps/dolly-backend/src/main/java/no/nav/dolly/bestilling/aareg/amelding/AmeldingService.java
- apps/dolly-backend/src/main/java/no/nav/dolly/bestilling/organisasjonforvalter/OrganisasjonClient.java
- apps/dolly-backend/src/main/java/no/nav/dolly/bestilling/organisasjonforvalter/domain/DeployRequest.java
- apps/dolly-backend/src/main/java/no/nav/dolly/bestilling/service/DollyBestillingService.java
- apps/dolly-backend/src/main/java/no/nav/dolly/domain/resultset/RsDollyBestilling.java
- apps/dolly-backend/src/main/java/no/nav/dolly/domain/resultset/RsOrganisasjonBestilling.java
- apps/dolly-backend/src/main/java/no/nav/dolly/domain/resultset/entity/bestilling/RsBestillingStatus.java
- apps/dolly-backend/src/main/java/no/nav/dolly/domain/resultset/entity/bestilling/RsMalBestillingWrapper.java
- apps/dolly-backend/src/main/java/no/nav/dolly/domain/resultset/entity/bestilling/RsOrganisasjonBestillingStatus.java
- apps/dolly-backend/src/main/java/no/nav/dolly/domain/resultset/entity/testgruppe/RsTestgruppeMedBestillingId.java
- apps/dolly-backend/src/main/java/no/nav/dolly/mapper/strategy/BestillingStatusMappingStrategy.java
- apps/dolly-backend/src/main/java/no/nav/dolly/provider/api/OrganisasjonController.java
- apps/dolly-backend/src/main/java/no/nav/dolly/service/OrganisasjonBestillingService.java
- apps/dolly-backend/src/main/java/no/nav/dolly/util/EnvironmentsCrossConnect.java
- apps/dolly-backend/src/main/resources/application-local.yaml
- apps/dolly-backend/src/test/java/no/nav/dolly/api/TestgruppeControllerTest.java
- apps/dolly-backend/src/test/java/no/nav/dolly/bestilling/aareg/AaregClientTest.java
- apps/dolly-backend/src/test/java/no/nav/dolly/bestilling/arenaforvalter/ArenaForvalterClientTest.java
- apps/dolly-backend/src/test/java/no/nav/dolly/bestilling/instdata/InstdataClientTest.java
- apps/dolly-backend/src/test/java/no/nav/dolly/bestilling/organisasjonforvalter/OrganisasjonClientTest.java
- apps/dolly-backend/src/test/java/no/nav/dolly/bestilling/pdlforvalter/PdlForvalterClientTest.java
- apps/dolly-backend/src/test/java/no/nav/dolly/bestilling/pensjonforvalter/PensjonforvalterClientTest.java
- apps/dolly-backend/src/test/java/no/nav/dolly/service/BestillingServiceTest.java
- apps/dolly-backend/src/test/java/no/nav/dolly/util/EnvironmentsCrossConnectTest.java
- apps/dolly-backend/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
Ref. https://trello.com/c/0bv8z6B2.
> Krysskoble AAREG-bestillinger mellom Q1 og Q2

- apps/dolly-frontend/src/main/js/cypress/mocks/BasicMocks.tsx
- apps/dolly-frontend/src/main/js/src/components/fagsystem/tpsf/visning/partials/MidlertidigAdresse.tsx
Hadde ikke tester for midlertidig adresse i Cypress der feilen skjedde, la til test av denne og fikset feil
> Bugfix formatDate og Cypress test for denne

- apps/dolly-frontend/src/main/js/src/components/utlogging/logoutBruker.tsx
- apps/dolly-frontend/src/main/js/src/pages/loginPage/LoginModal.tsx
- apps/dolly-frontend/src/main/js/src/service/services/personOrganisasjonTilgang/PersonOrganisasjonTilgangService.tsx
Bedre tilbakemelding til bruker også
> Mindre endring på idporten ved feilet kall mot person-org-tilgang-service

- apps/dolly-backend/src/main/java/no/nav/dolly/bestilling/histark/mapper/HistarkMappingStrategy.java
Histark baserer nå sjekksum basert på binærkode av innsendt fil, endrer sjekksum kalkulering hos oss for at de skal stemme overens
> Endret histark sjekksum kalkulering i samarbeid med Lars Jensen

- apps/dolly-frontend/src/main/js/src/components/bestilling/sammendrag/kriterier/BestillingKriterieMapper.tsx
- apps/dolly-frontend/src/main/js/src/components/fagsystem/pdlf/visning/partials/UkjentBosted.tsx
- apps/dolly-frontend/src/main/js/src/components/ui/form/inputs/select/Select.tsx
Setter "uoppgitt" som første valg på kommune (for ukjent bosted), og viser label på bostedskommune
> Fix bostedskommune

- apps/pdl-forvalter/src/main/java/no/nav/pdl/forvalter/service/MetadataTidspunkterService.java
Oppdatert innsending av metadata:
Hensyntar at relasjonsdato ikke er/var satt på alle innsendinger.
> Fix for gyldighetstidspunkt ved sivilstand

- apps/dolly-frontend/src/main/js/src/components/fagsystem/krrstub/form/Form.tsx
Tel nummer format er ikke i sync med KRR.
> Fiks ugyldig telefonnummer format

- apps/dolly-backend/src/main/java/no/nav/dolly/bestilling/arenaforvalter/service/ArenaAap115Service.java
- apps/dolly-backend/src/main/java/no/nav/dolly/bestilling/arenaforvalter/utils/ArenaStatusUtil.java
- apps/dolly-backend/src/main/java/no/nav/dolly/domain/resultset/arenaforvalter/ArenaNyeBrukereResponse.java
- apps/dolly-backend/src/test/java/no/nav/dolly/bestilling/arenaforvalter/service/ArenaBrukerServiceTest.java
- apps/dolly-backend/src/test/java/no/nav/dolly/bestilling/arenaforvalter/utils/ArenaStatusUtilTest.java
Skrevet noen tester for dette.
> Fikset nytt case for statusResponse AAP og DAGP i tillegg til BrukerResponse

- apps/pdl-forvalter/src/main/java/no/nav/pdl/forvalter/service/DoedsfallService.java
- apps/pdl-forvalter/src/main/java/no/nav/pdl/forvalter/service/FoedselService.java
- apps/pdl-forvalter/src/main/java/no/nav/pdl/forvalter/service/SikkerhetstiltakService.java
- apps/pdl-forvalter/src/main/java/no/nav/pdl/forvalter/utils/ArtifactUtils.java
Forbedret robusthet på visse opplysningstyper uten historikk, visning og innsending
> Oppdatert innsending uten historikk #deploy-pdl-forvalter-dev

- apps/dolly-backend/src/main/java/no/nav/dolly/provider/api/BrukerController.java
- apps/dolly-backend/src/main/java/no/nav/dolly/service/BrukerService.java
Ref [denne](https://nav-it.slack.com/archives/CA3P9NGA2/p1704793363538469) på dolly kanalen, hvor nye teammedlemmer ikke havner i alleBrukere når den kalles.
> Fiks for manglende entries på hentAlleBrukere i backend

- apps/dolly-backend/src/main/java/no/nav/dolly/bestilling/inntektsmelding/mapper/InntektsmeldingMappingStrategy.java
- apps/dolly-backend/src/main/java/no/nav/dolly/domain/resultset/inntektsmeldingstub/RsInntektsmelding.java
- apps/dolly-backend/src/test/java/no/nav/dolly/bestilling/inntektsmelding/mapper/InntektsmeldingMappingStrategyTest.java
- libs/data-transfer-objects/src/main/java/no/nav/testnav/libs/dto/inntektsmeldinggeneratorservice/v1/rs/RsArbeidsgiver.java
- libs/data-transfer-objects/src/main/java/no/nav/testnav/libs/dto/inntektsmeldinggeneratorservice/v1/rs/RsArbeidsgiverPrivat.java
- libs/data-transfer-objects/src/main/java/no/nav/testnav/libs/dto/inntektsmeldinggeneratorservice/v1/rs/RsOmsorgspenger.java
The changes have been made in several classes and methods related to Inntektsmelding service. This includes modification in builder patterns in various DTOs, mapping strategies and related test cases. The refactoring aims to improve the efficiency of data mapping and enhance readability.
> Modify classes and methods for Inntektsmelding service

- apps/dolly-frontend/src/main/js/package-lock.json
- apps/dolly-frontend/src/main/js/src/components/fagsystem/inntektsmelding/form/Form.tsx
Var ikke så mye som skulle til heldigvis 😅
> Fikset feil på mal for inntektsmelding

- apps/adresse-service/config.yml
- apps/dolly-frontend/config.idporten.yml
- apps/dolly-frontend/config.test.yml
- apps/dolly-frontend/config.unstable.yml
- apps/dolly-frontend/config.yml
- apps/endringsmelding-frontend/config.yml
- apps/miljoer-service/config.yml
- apps/oppsummeringsdokument-service/config.yml
Disse appene utnytter kun <1% av denne verdien under normal last, sjekket ved nais console ressursbruk. Ser en del andre apper i samme båt, men de har satt ganske lav verdi fra før eller har forventede spikes i CPU bruk så lot de være
> Senker kravene til CPU for flere applikasjoner

- apps/dolly-frontend/src/main/js/src/components/ui/form/inputs/datepicker/Datepicker.tsx
@stigus du som vet hvorfor ting er gjort som de er gjort - fint om du kan ta en kjapp titt 🤓
> Fix dato som ikke vises

- apps/dolly-frontend/src/main/js/package-lock.json
- apps/dolly-frontend/src/main/js/src/service/services/dolly/DollyEndpoints.tsx
Fix for oppslag som routet til backend istedenfor kodeverk-service i DollyEndpoints oppsettet
> Fix for kodeverk frontend

- apps/pdl-forvalter/src/main/java/no/nav/pdl/forvalter/service/FolkeregisterPersonstatusService.java
#deploy-pdl-forvalter #deploy-test-pdl-forvalter
> Oppdaterer personstatus ved doedsfall

- apps/dolly-backend/src/main/java/no/nav/dolly/bestilling/dokarkiv/domain/DokarkivRequest.java
- apps/dolly-backend/src/main/java/no/nav/dolly/bestilling/dokarkiv/mapper/DokarkivMappingStrategy.java
Denne er påkrevd nå, har testet på dev at det fungerer når den sendes med.
> Lagt på required eksternReferanseId mot dokarkiv

- apps/dolly-frontend/src/main/js/package-lock.json
- apps/dolly-frontend/src/main/js/src/components/bestilling/sammendrag/BestillingSammendrag.tsx
- apps/dolly-frontend/src/main/js/src/components/bestilling/sammendrag/BestillingSammendragModal.tsx
- apps/dolly-frontend/src/main/js/src/components/bestilling/sammendrag/kriterier/BestillingKriterieMapper.tsx
- apps/dolly-frontend/src/main/js/src/components/bestilling/sammendrag/kriterier/Bestillingskriterier.tsx
- apps/dolly-frontend/src/main/js/src/components/bestilling/statusListe/BestillingResultat/BestillingResultat.tsx
- apps/dolly-frontend/src/main/js/src/components/fagsystem/organisasjoner/visning/Visning.tsx
- apps/dolly-frontend/src/main/js/src/pages/gruppe/PersonVisning/PersonVisning.tsx
* Lagt til navigering mellom bestillingsdetaljer dersom en ident har flere tilknyttede bestillinger
* Fikset bug som viste Test-Norge ident ved legg til/endre selv om det var på NAV-Syntetisk #deploy-test-frontend
> Navigering i bestillingsdetaljer

- apps/levende-arbeidsforhold-service/src/main/java/no/nav/registre/testnorge/levendearbeidsforhold/config/ApplicationConfig.java
- apps/levende-arbeidsforhold-service/src/main/java/no/nav/registre/testnorge/levendearbeidsforhold/config/KafkaConfig.java
- apps/levende-arbeidsforhold-service/src/main/java/no/nav/registre/testnorge/levendearbeidsforhold/consumers/AaregConsumer.java
- apps/levende-arbeidsforhold-service/src/main/java/no/nav/registre/testnorge/levendearbeidsforhold/consumers/command/EndreArbeidsforholdCommand.java
- apps/levende-arbeidsforhold-service/src/main/java/no/nav/registre/testnorge/levendearbeidsforhold/consumers/command/HentArbeidsforholdCommand.java
- apps/levende-arbeidsforhold-service/src/main/java/no/nav/registre/testnorge/levendearbeidsforhold/listener/DoedsfallListener.java
- apps/levende-arbeidsforhold-service/src/main/java/no/nav/registre/testnorge/levendearbeidsforhold/service/ArbeidsforholdService.java
#deploy-levende-arbeidsforhold-service
> Fjernet logging av suksess-scenarier. Logger kun for feilscenarier

- apps/levende-arbeidsforhold-ansettelse/src/main/java/no/nav/registre/testnorge/levendearbeidsforholdansettelse/config/Consumers.java
- apps/levende-arbeidsforhold-ansettelse/src/main/java/no/nav/registre/testnorge/levendearbeidsforholdansettelse/consumers/OrganisasjonFasteDataConsumer.java
- apps/levende-arbeidsforhold-ansettelse/src/main/java/no/nav/registre/testnorge/levendearbeidsforholdansettelse/consumers/command/GetOrganisasjonerCommand.java
- apps/levende-arbeidsforhold-ansettelse/src/main/java/no/nav/registre/testnorge/levendearbeidsforholdansettelse/consumers/pdl/GraphQLRequest.java
- apps/levende-arbeidsforhold-ansettelse/src/main/java/no/nav/registre/testnorge/levendearbeidsforholdansettelse/consumers/pdl/JacksonExchangeStrategyUtil.java
- apps/levende-arbeidsforhold-ansettelse/src/main/java/no/nav/registre/testnorge/levendearbeidsforholdansettelse/consumers/pdl/PdlPersonConsumer.java
- apps/levende-arbeidsforhold-ansettelse/src/main/java/no/nav/registre/testnorge/levendearbeidsforholdansettelse/consumers/pdl/TemaGrunnlag.java
- apps/levende-arbeidsforhold-ansettelse/src/main/java/no/nav/registre/testnorge/levendearbeidsforholdansettelse/consumers/pdl/commad/PdlBolkPersonCommand.java
- apps/levende-arbeidsforhold-ansettelse/src/main/java/no/nav/registre/testnorge/levendearbeidsforholdansettelse/consumers/pdl/commad/PdlPersonGetCommand.java
- apps/levende-arbeidsforhold-ansettelse/src/main/java/no/nav/registre/testnorge/levendearbeidsforholdansettelse/consumers/pdl/command/PdlBolkPersonCommand.java
- apps/levende-arbeidsforhold-ansettelse/src/main/java/no/nav/registre/testnorge/levendearbeidsforholdansettelse/consumers/pdl/command/PdlPersonGetCommand.java
- apps/levende-arbeidsforhold-ansettelse/src/main/java/no/nav/registre/testnorge/levendearbeidsforholdansettelse/consumers/pdl/domain/CommonKeysAndUtils.java
- apps/levende-arbeidsforhold-ansettelse/src/main/java/no/nav/registre/testnorge/levendearbeidsforholdansettelse/domain/organisasjon/Organisasjon2.java
- apps/levende-arbeidsforhold-ansettelse/src/main/java/no/nav/registre/testnorge/levendearbeidsforholdansettelse/provider/v2/PdlMiljoer.java
- apps/levende-arbeidsforhold-ansettelse/src/main/java/no/nav/registre/testnorge/levendearbeidsforholdansettelse/provider/v2/PdlPersonController.java
- apps/levende-arbeidsforhold-ansettelse/src/main/java/no/nav/registre/testnorge/levendearbeidsforholdansettelse/service/HentOrganisasjonNummerService.java
- apps/levende-arbeidsforhold-ansettelse/src/main/java/no/nav/registre/testnorge/levendearbeidsforholdansettelse/service/HentOrganisasjonService.java
- apps/levende-arbeidsforhold-ansettelse/src/main/java/no/nav/registre/testnorge/levendearbeidsforholdansettelse/service/HentPersonService.java
- apps/levende-arbeidsforhold-ansettelse/src/main/java/no/nav/registre/testnorge/levendearbeidsforholdansettelse/service/TenorPersonService.java
- apps/levende-arbeidsforhold-ansettelse/src/main/resources/application.yml
- apps/levende-arbeidsforhold-ansettelse/src/main/resources/pdl/graphql.config.yml
- apps/levende-arbeidsforhold-ansettelse/src/main/resources/pdl/pdl-api-schema.graphql
- apps/levende-arbeidsforhold-ansettelse/src/main/resources/pdl/pdlHentIdent.graphql
- apps/levende-arbeidsforhold-ansettelse/src/main/resources/pdl/pdlPerson2Query.graphql
- apps/levende-arbeidsforhold-ansettelse/src/main/resources/pdl/pdlPersonQuery.graphql
- apps/levende-arbeidsforhold-ansettelse/src/main/resources/pdl/pdlQuery.graphql
- apps/levende-arbeidsforhold-ansettelse/src/main/resources/pdl/pdlbolkquery.graphql
Satt inn slik at vi kan gjøre sperringer med graphQL opp mot pil og get kommand til organisasjon-faste-data-service for å hente organisasjoner
> 6 pdl graph ql

- apps/levende-arbeidsforhold-ansettelse/src/main/java/no/nav/registre/testnorge/levendearbeidsforholdansettelse/consumers/AaregConsumer.java
- apps/levende-arbeidsforhold-ansettelse/src/main/java/no/nav/registre/testnorge/levendearbeidsforholdansettelse/consumers/EregConsumer.java
- apps/levende-arbeidsforhold-ansettelse/src/main/java/no/nav/registre/testnorge/levendearbeidsforholdansettelse/consumers/OrganisasjonFasteDataConsumer.java
- apps/levende-arbeidsforhold-ansettelse/src/main/java/no/nav/registre/testnorge/levendearbeidsforholdansettelse/consumers/command/aareg/EndreArbeidsforholdCommand.java
- apps/levende-arbeidsforhold-ansettelse/src/main/java/no/nav/registre/testnorge/levendearbeidsforholdansettelse/consumers/command/aareg/HentArbeidsforholdCommand.java
- apps/levende-arbeidsforhold-ansettelse/src/main/java/no/nav/registre/testnorge/levendearbeidsforholdansettelse/consumers/command/aareg/OpprettArbeidsforholdCommand.java
- apps/levende-arbeidsforhold-ansettelse/src/main/java/no/nav/registre/testnorge/levendearbeidsforholdansettelse/consumers/command/ereg/HentOrganisasjonerCommand.java
- apps/levende-arbeidsforhold-ansettelse/src/main/java/no/nav/registre/testnorge/levendearbeidsforholdansettelse/consumers/command/organisasjonFasteData/GetOrganisasjonerCommand.java
- apps/levende-arbeidsforhold-ansettelse/src/main/java/no/nav/registre/testnorge/levendearbeidsforholdansettelse/consumers/command/tenor/HentPersonerCommand.java
- apps/levende-arbeidsforhold-ansettelse/src/main/java/no/nav/registre/testnorge/levendearbeidsforholdansettelse/service/AaregService.java
- apps/levende-arbeidsforhold-ansettelse/src/main/java/no/nav/registre/testnorge/levendearbeidsforholdansettelse/service/HentOrganisasjonerService.java
Lagt til OpprettArbeidsforhold
> 9.opprette arbeidsforhold

- .github/workflows/common.workflow.backend.yml
- .github/workflows/common.workflow.frontend.yml
Mindre cleanup, ref. https://nav-it.slack.com/archives/C01DE3M9YBV/p1720698185013939.
> Removing now-obsolete explicit dockerfile config.

- apps/dolly-backend/src/main/java/no/nav/dolly/service/MalBestillingService.java
- apps/dolly-frontend/src/main/js/package-lock.json
- apps/dolly-frontend/src/main/js/package.json
- apps/dolly-frontend/src/main/js/playwright/mocks/Selectors.tsx
- apps/dolly-frontend/src/main/js/playwright/tests/OpprettBestilling.spec.ts
- apps/dolly-frontend/src/main/js/src/components/bestillingsveileder/startModal/NyIdent/NyIdent.tsx
- apps/dolly-frontend/src/main/js/src/components/bestillingsveileder/stegVelger/StegVelger.tsx
- apps/dolly-frontend/src/main/js/src/components/fagsystem/pdlf/form/validation/partials/adresser.tsx
- apps/dolly-frontend/src/main/js/src/components/fagsystem/pdlf/form/validation/validation.tsx
- apps/dolly-frontend/src/main/js/src/components/fagsystem/pensjon/form/validation.tsx
- apps/dolly-frontend/src/main/js/src/components/ui/form/inputs/select/Select.tsx
* Lagt til playwright spec for alle de resterende artifakter som ikke blir huket av i miljøavhengig test
* Fikset personFoerLeggTil som ikke ble hentet riktig fra context flere steder i valideringen
* Byttet stepper til nyere stepper med funksjonalitet for avhuking og navigering ved klikk
* Oppdatering
> Personfoerleggtil validering frontend

- apps/brreg-stub/build.gradle
- apps/brreg-stub/src/main/java/no/nav/brregstub/api/common/Egenskap.java
- apps/brreg-stub/src/main/java/no/nav/brregstub/config/JacksonConfig.java
- apps/brreg-stub/src/main/java/no/nav/brregstub/service/RolleoversiktService.java
- apps/brreg-stub/src/test/java/no/nav/brregstub/endpoint/rs/v2/RolleoversiktControllerTest.java
> * Endret mapping av enum på brreg-stub og skrevet om litt

- apps/levende-arbeidsforhold-scheduler/build.gradle
- apps/levende-arbeidsforhold-service/build.gradle
Lagt til bruk av convention plugin dolly-apps.
> Bruker nå convention plugin dolly-apps.

- apps/dolly-frontend/src/main/js/src/components/fagsystem/pdlf/form/partials/familierelasjoner/sivilstand/Sivilstand.tsx
- apps/dolly-frontend/src/main/js/src/components/fagsystem/pdlf/form/partials/pdlPerson/PdlPersonForm.tsx
- apps/dolly-frontend/src/main/js/src/pages/gruppe/Gruppe.tsx
... og fjernet "fix" på avbryt bestilling, som skapte uheldige bivirkninger :(
> Vis relatert person-valg paa tenor-person

- apps/dolly-frontend/src/main/java/no/nav/dolly/web/DollyFrontendApplicationStarter.java
- apps/dolly-frontend/src/main/js/package-lock.json
- apps/dolly-frontend/src/main/js/package.json
- apps/dolly-frontend/src/main/js/src/api/index.ts
- apps/dolly-frontend/src/main/js/src/app/App.tsx
- apps/dolly-frontend/src/main/js/src/utils/hooks/useMaler.tsx
This pull request includes several changes to the `dolly-frontend` project, focusing on adding a new filter to remove cookies, updating dependencies, and refactoring JavaScript code for better readability and functionality. The most important changes are listed below:
* Added a `removeCookiesFilter` to the `DollyFrontendApplicationStarter` class to remove cookies from the request headers. [[1]](diffhunk://#diff-856fe9790bbc0f7d29fc09edc6922387fb63b3ae17e60a8ff99a2c0c680b5d67R25-R26) [[2]](diffhunk://#diff-856fe9790bbc0f7d29fc09edc6922387fb63b3ae17e60a8ff99a2c0c680b5d67R46-R56) [[3]](diffhunk://#diff-856fe9790bbc0f7d29fc09edc6922387fb63b3ae17e60a8ff99a2c0c680b5d67L135-R146)
* Updated the `uuid` package version from `^10.0.0` to `^11.0.3` in the `package.json` file.
* Refactored multiple …
> * Lagt på filter som forhindrer cookies fra å sendes videre til backend applikasjonen

- apps/dolly-frontend/src/main/js/src/pages/dollySoek/SoekForm.tsx
- apps/dolly-frontend/src/main/js/src/service/services/dollysearch/DollySearch.tsx
- apps/dolly-frontend/src/main/js/src/service/services/pdl/PdlForvalterService.tsx
- Navigering kallet ble kuttet av ved fragment over 11 tegn på personsearch
- Liten endring for dollySearch og intuitiv knapp eter manuell endring
> Fix for navigering i Dolly

- apps/pdl-forvalter/src/main/java/no/nav/pdl/forvalter/mapper/VergemaalMappingStrategy.java
This pull request introduces enhancements to the `VergemaalMappingStrategy` class to improve code readability, streamline logic, and add new functionality for handling `Folkeregistermetadata`. The key changes include refactoring the mapping logic for `personnavn` and adding support for setting `Folkeregistermetadata` fields.
* Simplified the logic for retrieving `personnavn` by replacing conditional checks with a streamlined `flatMap` and `orElse` approach. This reduces code complexity and improves readability. (`[apps/pdl-forvalter/src/main/java/no/nav/pdl/forvalter/mapper/VergemaalMappingStrategy.javaL72-R89](diffhunk://#diff-b242284cf9d4a6f6cd4d2253316c9eff2e411ad4f788249711808e9e750436c0L72-R89)`)
* Added support for initializing and setting `Folkeregistermetadata` fields …
> Bugfix datoer for vergemaal

- .github/copilot-instructions.md
- README.md
This pull request introduces a new set of Copilot instructions and updates the `README.md` to clarify local development practices and Copilot usage. The most important changes are the addition of detailed coding guidelines for Copilot, improvements to documentation for local setup and migration, and explicit references to the new Copilot instructions file.
**Copilot instructions and coding guidelines:**
* Added `.github/copilot-instructions.md` with comprehensive guidelines for generating code in Java (Spring Boot), TypeScript (React), REST APIs, and error handling, including style preferences and restrictions.
**Documentation improvements for local development:**
* Updated `README.md` with clearer instructions for running tests and applications locally, including environment variables …
> Add GitHub Copilot instructions for code generation and best practices
